var annotated_dup =
[
    [ "logger_module", "namespacelogger__module.html", [
      [ "access_control_filter", "classlogger__module_1_1access__control__filter.html", "classlogger__module_1_1access__control__filter" ],
      [ "base_formatter", "classlogger__module_1_1base__formatter.html", "classlogger__module_1_1base__formatter" ],
      [ "base_writer", "classlogger__module_1_1base__writer.html", "classlogger__module_1_1base__writer" ],
      [ "basic_monitor", "classlogger__module_1_1basic__monitor.html", "classlogger__module_1_1basic__monitor" ],
      [ "compact_formatter", "classlogger__module_1_1compact__formatter.html", "classlogger__module_1_1compact__formatter" ],
      [ "composite_filter", "classlogger__module_1_1composite__filter.html", "classlogger__module_1_1composite__filter" ],
      [ "composite_strategy", "classlogger__module_1_1composite__strategy.html", "classlogger__module_1_1composite__strategy" ],
      [ "config_strategy_factory", "classlogger__module_1_1config__strategy__factory.html", null ],
      [ "config_strategy_interface", "classlogger__module_1_1config__strategy__interface.html", "classlogger__module_1_1config__strategy__interface" ],
      [ "console_writer", "classlogger__module_1_1console__writer.html", "classlogger__module_1_1console__writer" ],
      [ "di_container_factory", "classlogger__module_1_1di__container__factory.html", "classlogger__module_1_1di__container__factory" ],
      [ "di_container_interface", "classlogger__module_1_1di__container__interface.html", "classlogger__module_1_1di__container__interface" ],
      [ "encrypted_writer", "classlogger__module_1_1encrypted__writer.html", "classlogger__module_1_1encrypted__writer" ],
      [ "environment_strategy", "classlogger__module_1_1environment__strategy.html", "classlogger__module_1_1environment__strategy" ],
      [ "file_writer", "classlogger__module_1_1file__writer.html", "classlogger__module_1_1file__writer" ],
      [ "function_filter", "classlogger__module_1_1function__filter.html", "classlogger__module_1_1function__filter" ],
      [ "health_check_result", "classlogger__module_1_1health__check__result.html", "classlogger__module_1_1health__check__result" ],
      [ "json_formatter", "classlogger__module_1_1json__formatter.html", "classlogger__module_1_1json__formatter" ],
      [ "level_filter", "classlogger__module_1_1level__filter.html", "classlogger__module_1_1level__filter" ],
      [ "lightweight_di_container", "classlogger__module_1_1lightweight__di__container.html", "classlogger__module_1_1lightweight__di__container" ],
      [ "log_aggregator", "classlogger__module_1_1log__aggregator.html", "classlogger__module_1_1log__aggregator" ],
      [ "log_analyzer", "classlogger__module_1_1log__analyzer.html", "classlogger__module_1_1log__analyzer" ],
      [ "log_collector", "classlogger__module_1_1log__collector.html", "classlogger__module_1_1log__collector" ],
      [ "log_entry", "structlogger__module_1_1log__entry.html", "structlogger__module_1_1log__entry" ],
      [ "log_filter", "classlogger__module_1_1log__filter.html", "classlogger__module_1_1log__filter" ],
      [ "log_filter_interface", "classlogger__module_1_1log__filter__interface.html", "classlogger__module_1_1log__filter__interface" ],
      [ "log_formatter_interface", "classlogger__module_1_1log__formatter__interface.html", "classlogger__module_1_1log__formatter__interface" ],
      [ "log_route", "structlogger__module_1_1log__route.html", "structlogger__module_1_1log__route" ],
      [ "log_router", "classlogger__module_1_1log__router.html", "classlogger__module_1_1log__router" ],
      [ "log_sanitizer", "classlogger__module_1_1log__sanitizer.html", "classlogger__module_1_1log__sanitizer" ],
      [ "log_server", "classlogger__module_1_1log__server.html", "classlogger__module_1_1log__server" ],
      [ "log_sink_interface", "classlogger__module_1_1log__sink__interface.html", "classlogger__module_1_1log__sink__interface" ],
      [ "log_writer_interface", "classlogger__module_1_1log__writer__interface.html", "classlogger__module_1_1log__writer__interface" ],
      [ "logger", "classlogger__module_1_1logger.html", "classlogger__module_1_1logger" ],
      [ "logger_builder", "classlogger__module_1_1logger__builder.html", "classlogger__module_1_1logger__builder" ],
      [ "logger_config", "structlogger__module_1_1logger__config.html", "structlogger__module_1_1logger__config" ],
      [ "logger_metrics_collector", "classlogger__module_1_1logger__metrics__collector.html", "classlogger__module_1_1logger__metrics__collector" ],
      [ "metric_value", "structlogger__module_1_1metric__value.html", "structlogger__module_1_1metric__value" ],
      [ "monitoring_data", "classlogger__module_1_1monitoring__data.html", "classlogger__module_1_1monitoring__data" ],
      [ "monitoring_factory", "classlogger__module_1_1monitoring__factory.html", "classlogger__module_1_1monitoring__factory" ],
      [ "monitoring_interface", "classlogger__module_1_1monitoring__interface.html", "classlogger__module_1_1monitoring__interface" ],
      [ "network_writer", "classlogger__module_1_1network__writer.html", "classlogger__module_1_1network__writer" ],
      [ "performance_metrics", "structlogger__module_1_1performance__metrics.html", "structlogger__module_1_1performance__metrics" ],
      [ "performance_tuning_strategy", "classlogger__module_1_1performance__tuning__strategy.html", "classlogger__module_1_1performance__tuning__strategy" ],
      [ "plain_formatter", "classlogger__module_1_1plain__formatter.html", "classlogger__module_1_1plain__formatter" ],
      [ "regex_filter", "classlogger__module_1_1regex__filter.html", "classlogger__module_1_1regex__filter" ],
      [ "result", "classlogger__module_1_1result.html", "classlogger__module_1_1result" ],
      [ "result_void", "classlogger__module_1_1result__void.html", "classlogger__module_1_1result__void" ],
      [ "rotating_file_writer", "classlogger__module_1_1rotating__file__writer.html", "classlogger__module_1_1rotating__file__writer" ],
      [ "router_builder", "classlogger__module_1_1router__builder.html", "classlogger__module_1_1router__builder" ],
      [ "sanitizing_filter", "classlogger__module_1_1sanitizing__filter.html", "classlogger__module_1_1sanitizing__filter" ],
      [ "source_location", "structlogger__module_1_1source__location.html", "structlogger__module_1_1source__location" ],
      [ "standard_fields", "structlogger__module_1_1standard__fields.html", null ],
      [ "structured_log_entry", "classlogger__module_1_1structured__log__entry.html", "classlogger__module_1_1structured__log__entry" ],
      [ "structured_logger", "classlogger__module_1_1structured__logger.html", "classlogger__module_1_1structured__logger" ],
      [ "template_strategy", "classlogger__module_1_1template__strategy.html", "classlogger__module_1_1template__strategy" ],
      [ "thread_system_monitor_adapter", "classlogger__module_1_1thread__system__monitor__adapter.html", "classlogger__module_1_1thread__system__monitor__adapter" ],
      [ "writer_metrics", "structlogger__module_1_1writer__metrics.html", "structlogger__module_1_1writer__metrics" ]
    ] ],
    [ "thread_module", "namespacethread__module.html", [
      [ "logger_interface", "classthread__module_1_1logger__interface.html", "classthread__module_1_1logger__interface" ],
      [ "logger_registry", "classthread__module_1_1logger__registry.html", null ]
    ] ]
];