var annotated_dup =
[
    [ "logger_module", "namespacelogger__module.html", [
      [ "v1_compat", "namespacelogger__module_1_1v1__compat.html", [
        [ "logger_config_v1", "structlogger__module_1_1v1__compat_1_1logger__config__v1.html", "structlogger__module_1_1v1__compat_1_1logger__config__v1" ]
      ] ],
      [ "access_control_filter", "classlogger__module_1_1access__control__filter.html", "classlogger__module_1_1access__control__filter" ],
      [ "adaptive_backpressure", "classlogger__module_1_1adaptive__backpressure.html", "classlogger__module_1_1adaptive__backpressure" ],
      [ "async_writer", "classlogger__module_1_1async__writer.html", "classlogger__module_1_1async__writer" ],
      [ "base_formatter", "classlogger__module_1_1base__formatter.html", "classlogger__module_1_1base__formatter" ],
      [ "base_writer", "classlogger__module_1_1base__writer.html", "classlogger__module_1_1base__writer" ],
      [ "basic_monitor", "classlogger__module_1_1basic__monitor.html", "classlogger__module_1_1basic__monitor" ],
      [ "batch_writer", "classlogger__module_1_1batch__writer.html", "classlogger__module_1_1batch__writer" ],
      [ "block_policy", "classlogger__module_1_1block__policy.html", "classlogger__module_1_1block__policy" ],
      [ "buffer_health_info", "structlogger__module_1_1buffer__health__info.html", "structlogger__module_1_1buffer__health__info" ],
      [ "compact_formatter", "classlogger__module_1_1compact__formatter.html", "classlogger__module_1_1compact__formatter" ],
      [ "composite_filter", "classlogger__module_1_1composite__filter.html", "classlogger__module_1_1composite__filter" ],
      [ "composite_strategy", "classlogger__module_1_1composite__strategy.html", "classlogger__module_1_1composite__strategy" ],
      [ "config_strategy_factory", "classlogger__module_1_1config__strategy__factory.html", "classlogger__module_1_1config__strategy__factory" ],
      [ "config_strategy_interface", "classlogger__module_1_1config__strategy__interface.html", "classlogger__module_1_1config__strategy__interface" ],
      [ "console_writer", "classlogger__module_1_1console__writer.html", "classlogger__module_1_1console__writer" ],
      [ "custom_overflow_policy", "classlogger__module_1_1custom__overflow__policy.html", "classlogger__module_1_1custom__overflow__policy" ],
      [ "di_container_factory", "classlogger__module_1_1di__container__factory.html", "classlogger__module_1_1di__container__factory" ],
      [ "di_container_interface", "classlogger__module_1_1di__container__interface.html", "classlogger__module_1_1di__container__interface" ],
      [ "drop_newest_policy", "classlogger__module_1_1drop__newest__policy.html", "classlogger__module_1_1drop__newest__policy" ],
      [ "drop_oldest_policy", "classlogger__module_1_1drop__oldest__policy.html", "classlogger__module_1_1drop__oldest__policy" ],
      [ "encrypted_writer", "classlogger__module_1_1encrypted__writer.html", "classlogger__module_1_1encrypted__writer" ],
      [ "environment_strategy", "classlogger__module_1_1environment__strategy.html", "classlogger__module_1_1environment__strategy" ],
      [ "file_writer", "classlogger__module_1_1file__writer.html", "classlogger__module_1_1file__writer" ],
      [ "function_filter", "classlogger__module_1_1function__filter.html", "classlogger__module_1_1function__filter" ],
      [ "grow_policy", "classlogger__module_1_1grow__policy.html", "classlogger__module_1_1grow__policy" ],
      [ "health_check_criteria", "structlogger__module_1_1health__check__criteria.html", "structlogger__module_1_1health__check__criteria" ],
      [ "health_check_result", "classlogger__module_1_1health__check__result.html", "classlogger__module_1_1health__check__result" ],
      [ "health_check_system", "classlogger__module_1_1health__check__system.html", "classlogger__module_1_1health__check__system" ],
      [ "health_check_utils", "classlogger__module_1_1health__check__utils.html", "classlogger__module_1_1health__check__utils" ],
      [ "json_formatter", "classlogger__module_1_1json__formatter.html", "classlogger__module_1_1json__formatter" ],
      [ "level_filter", "classlogger__module_1_1level__filter.html", "classlogger__module_1_1level__filter" ],
      [ "lightweight_container", "classlogger__module_1_1lightweight__container.html", "classlogger__module_1_1lightweight__container" ],
      [ "lightweight_di_container", "classlogger__module_1_1lightweight__di__container.html", "classlogger__module_1_1lightweight__di__container" ],
      [ "log_aggregator", "classlogger__module_1_1log__aggregator.html", "classlogger__module_1_1log__aggregator" ],
      [ "log_analyzer", "classlogger__module_1_1log__analyzer.html", "classlogger__module_1_1log__analyzer" ],
      [ "log_collector", "classlogger__module_1_1log__collector.html", "classlogger__module_1_1log__collector" ],
      [ "log_entry", "structlogger__module_1_1log__entry.html", "structlogger__module_1_1log__entry" ],
      [ "log_filter", "classlogger__module_1_1log__filter.html", "classlogger__module_1_1log__filter" ],
      [ "log_filter_interface", "classlogger__module_1_1log__filter__interface.html", "classlogger__module_1_1log__filter__interface" ],
      [ "log_formatter_interface", "classlogger__module_1_1log__formatter__interface.html", "classlogger__module_1_1log__formatter__interface" ],
      [ "log_route", "structlogger__module_1_1log__route.html", "structlogger__module_1_1log__route" ],
      [ "log_router", "classlogger__module_1_1log__router.html", "classlogger__module_1_1log__router" ],
      [ "log_sanitizer", "classlogger__module_1_1log__sanitizer.html", "classlogger__module_1_1log__sanitizer" ],
      [ "log_server", "classlogger__module_1_1log__server.html", "classlogger__module_1_1log__server" ],
      [ "log_sink_interface", "classlogger__module_1_1log__sink__interface.html", "classlogger__module_1_1log__sink__interface" ],
      [ "log_writer_interface", "classlogger__module_1_1log__writer__interface.html", "classlogger__module_1_1log__writer__interface" ],
      [ "logger", "classlogger__module_1_1logger.html", "classlogger__module_1_1logger" ],
      [ "logger_builder", "classlogger__module_1_1logger__builder.html", "classlogger__module_1_1logger__builder" ],
      [ "logger_config", "structlogger__module_1_1logger__config.html", "structlogger__module_1_1logger__config" ],
      [ "logger_metrics_collector", "classlogger__module_1_1logger__metrics__collector.html", "classlogger__module_1_1logger__metrics__collector" ],
      [ "metric_value", "structlogger__module_1_1metric__value.html", "structlogger__module_1_1metric__value" ],
      [ "monitoring_data", "classlogger__module_1_1monitoring__data.html", "classlogger__module_1_1monitoring__data" ],
      [ "monitoring_factory", "classlogger__module_1_1monitoring__factory.html", "classlogger__module_1_1monitoring__factory" ],
      [ "monitoring_interface", "classlogger__module_1_1monitoring__interface.html", "classlogger__module_1_1monitoring__interface" ],
      [ "network_writer", "classlogger__module_1_1network__writer.html", "classlogger__module_1_1network__writer" ],
      [ "overflow_policy_base", "classlogger__module_1_1overflow__policy__base.html", "classlogger__module_1_1overflow__policy__base" ],
      [ "overflow_policy_factory", "classlogger__module_1_1overflow__policy__factory.html", "classlogger__module_1_1overflow__policy__factory" ],
      [ "overflow_queue", "classlogger__module_1_1overflow__queue.html", "classlogger__module_1_1overflow__queue" ],
      [ "overflow_stats", "structlogger__module_1_1overflow__stats.html", "structlogger__module_1_1overflow__stats" ],
      [ "performance_metrics", "structlogger__module_1_1performance__metrics.html", "structlogger__module_1_1performance__metrics" ],
      [ "performance_tuning_strategy", "classlogger__module_1_1performance__tuning__strategy.html", "classlogger__module_1_1performance__tuning__strategy" ],
      [ "plain_formatter", "classlogger__module_1_1plain__formatter.html", "classlogger__module_1_1plain__formatter" ],
      [ "queue_health_info", "structlogger__module_1_1queue__health__info.html", "structlogger__module_1_1queue__health__info" ],
      [ "regex_filter", "classlogger__module_1_1regex__filter.html", "classlogger__module_1_1regex__filter" ],
      [ "rotating_file_writer", "classlogger__module_1_1rotating__file__writer.html", "classlogger__module_1_1rotating__file__writer" ],
      [ "router_builder", "classlogger__module_1_1router__builder.html", "classlogger__module_1_1router__builder" ],
      [ "sanitizing_filter", "classlogger__module_1_1sanitizing__filter.html", "classlogger__module_1_1sanitizing__filter" ],
      [ "scoped_health_registration", "classlogger__module_1_1scoped__health__registration.html", "classlogger__module_1_1scoped__health__registration" ],
      [ "small_string", "classlogger__module_1_1small__string.html", "classlogger__module_1_1small__string" ],
      [ "source_location", "structlogger__module_1_1source__location.html", "structlogger__module_1_1source__location" ],
      [ "standard_fields", "structlogger__module_1_1standard__fields.html", "structlogger__module_1_1standard__fields" ],
      [ "structured_log_entry", "classlogger__module_1_1structured__log__entry.html", "classlogger__module_1_1structured__log__entry" ],
      [ "structured_logger", "classlogger__module_1_1structured__logger.html", "classlogger__module_1_1structured__logger" ],
      [ "template_strategy", "classlogger__module_1_1template__strategy.html", "classlogger__module_1_1template__strategy" ],
      [ "thread_system_di_adapter", "classlogger__module_1_1thread__system__di__adapter.html", "classlogger__module_1_1thread__system__di__adapter" ],
      [ "thread_system_monitor_adapter", "classlogger__module_1_1thread__system__monitor__adapter.html", "classlogger__module_1_1thread__system__monitor__adapter" ],
      [ "writer_health_info", "structlogger__module_1_1writer__health__info.html", "structlogger__module_1_1writer__health__info" ],
      [ "writer_metrics", "structlogger__module_1_1writer__metrics.html", "structlogger__module_1_1writer__metrics" ]
    ] ],
    [ "logger_system", "namespacelogger__system.html", [
      [ "template_config", "structlogger__system_1_1template__config.html", "structlogger__system_1_1template__config" ]
    ] ],
    [ "thread_module", "namespacethread__module.html", [
      [ "logger_interface", "classthread__module_1_1logger__interface.html", "classthread__module_1_1logger__interface" ],
      [ "logger_registry", "classthread__module_1_1logger__registry.html", "classthread__module_1_1logger__registry" ]
    ] ]
];