Logger System: logger_module::di_container_factory Class Reference
logger_module::di_container_factory Class Reference
Factory for creating DI containers.
#include <di_container_factory.h>
Public Types
enum class container_type { lightweight , thread_system , automatic }
Container types available.
Static Public Member Functions
template<typename T >
static std::unique_ptr< di_container_interface< T > > create_container (container_type type=container_type::automatic)
Create a DI container of specified type.
template<typename T >
static std::unique_ptr< di_container_interface< T > > create_best_available ()
Create the best available container.
static bool is_thread_system_available ()
Check if thread_system is available.
static const char * get_container_type_name (container_type type)
Get the name of the container type.
static container_type get_available_type ()
Get the currently available container type.
Detailed Description
Factory for creating DI containers.
This factory provides methods to create the appropriate DI container based on configuration and available dependencies.
Definition at line 31 of file di_container_factory.h.
Member Enumeration Documentation
container_type
enum class logger_module::di_container_factory::container_type strong
Container types available.
Enumerator
lightweight
Built-in lightweight container.
thread_system
thread_system container (if available)
automatic
Automatically choose best available.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/logger.h.
Definition at line 36 of file di_container_factory.h.
Member Function Documentation
create_best_available()
template<typename T > static std::unique_ptr< di_container_interface< T > > logger_module::di_container_factory::create_best_available () inline static
Create the best available container.
Attempts to create a thread_system container if available, otherwise falls back to lightweight implementation.
Template Parameters
T The type of objects the container will manage
Returns
Unique pointer to the created container
Definition at line 84 of file di_container_factory.h.
References is_thread_system_available().
create_container()
template<typename T > static std::unique_ptr< di_container_interface< T > > logger_module::di_container_factory::create_container (container_type type = container_type::automatic) inline static
Create a DI container of specified type.
Template Parameters
T The type of objects the container will manage
Parameters
type The type of container to create
Returns
Unique pointer to the created container
Definition at line 49 of file di_container_factory.h.
References automatic, lightweight, and thread_system.
get_available_type()
static container_type logger_module::di_container_factory::get_available_type () inline static
Get the currently available container type.
Returns
The best available container type
Definition at line 137 of file di_container_factory.h.
References is_thread_system_available(), lightweight, and thread_system.
get_container_type_name()
static const char * logger_module::di_container_factory::get_container_type_name (container_type type) inline static
Get the name of the container type.
Parameters
type The container type
Returns
String representation of the type
Definition at line 120 of file di_container_factory.h.
References automatic, lightweight, and thread_system.
is_thread_system_available()
static bool logger_module::di_container_factory::is_thread_system_available () inline static
Check if thread_system is available.
Returns
true if thread_system can be used
Definition at line 101 of file di_container_factory.h.
Referenced by create_best_available(), and get_available_type().
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/di/di_container_factory.h