Logger System: logger_module::compact_formatter Class Reference
logger_module::compact_formatter Class Reference
Compact formatter for minimal output.
#include <base_formatter.h>
Public Member Functions
std::string format (const log_entry &entry) const override
Format a log entry into a string.
std::string get_format_type () const override
Get the format type name.
Protected Member Functions
std::string level_to_string (thread_module::log_level level) const
Convert log level to string.
std::string format_timestamp (const std::chrono::system_clock::time_point &timestamp) const
Format timestamp to ISO8601 string.
std::string get_thread_id () const
Get current thread ID as string.
Detailed Description
Compact formatter for minimal output.
Definition at line 169 of file base_formatter.h.
Member Function Documentation
format()
std::string logger_module::compact_formatter::format (const log_entry & entry) const inline override virtual
Format a log entry into a string.
Parameters
entry The log entry to format
Returns
Formatted string representation
Implements logger_module::base_formatter.
Definition at line 171 of file base_formatter.h.
References logger_module::log_entry::level, logger_module::base_formatter::level_to_string(), and logger_module::log_entry::message.
format_timestamp()
std::string logger_module::base_formatter::format_timestamp (const std::chrono::system_clock::time_point & timestamp) const inline protected inherited
Format timestamp to ISO8601 string.
Parameters
timestamp Time point to format
Returns
ISO8601 formatted string
Definition at line 58 of file base_formatter.h.
Referenced by logger_module::plain_formatter::format(), and logger_module::json_formatter::format().
get_format_type()
std::string logger_module::compact_formatter::get_format_type () const inline override virtual
Get the format type name.
Returns
Format type (e.g., "json", "plain", "xml")
Implements logger_module::log_formatter_interface.
Definition at line 180 of file base_formatter.h.
get_thread_id()
std::string logger_module::base_formatter::get_thread_id () const inline protected inherited
Get current thread ID as string.
Returns
Thread ID string
Definition at line 69 of file base_formatter.h.
Referenced by logger_module::plain_formatter::format(), and logger_module::json_formatter::format().
level_to_string()
std::string logger_module::base_formatter::level_to_string (thread_module::log_level level) const inline protected inherited
Convert log level to string.
Parameters
level Log level
Returns
String representation
Definition at line 41 of file base_formatter.h.
Referenced by logger_module::plain_formatter::format(), logger_module::json_formatter::format(), and format().
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/formatters/base_formatter.h