Logger System: logger_module::health_check_system::impl Class Reference
logger_module::health_check_system::impl Class Reference
Public Member Functions
impl (const health_check_criteria &criteria)
~impl ()
void register_writer (const std::string &name, base_writer *writer)
void unregister_writer (const std::string &name)
void register_collector (log_collector *collector)
health_check_result perform_health_check ()
result< writer_health_info > check_writer_health (const std::string &name)
buffer_health_info check_buffer_health_internal ()
queue_health_info check_queue_health_internal ()
void update_writer_stats (const std::string &name, bool success, std::chrono::milliseconds latency)
void update_buffer_stats (size_t used, size_t total, bool allocation_failed)
void update_queue_stats (size_t current_size, size_t max_size, bool dropped, std::chrono::milliseconds wait_time)
void start_monitoring (std::chrono::seconds interval, std::function< void(const health_check_result &)> callback)
void stop_monitoring ()
bool is_monitoring () const
std::unordered_map< std::string, writer_health_info > get_all_writer_health () const
void reset_stats ()
void register_custom_check (const std::string &name, std::function< health_status()> check)
void configure_checks (bool check_writers, bool check_buffers, bool check_queues)
Public Attributes
health_check_criteria criteria_
Detailed Description
Definition at line 43 of file health_check_system.cpp.
Constructor & Destructor Documentation
impl()
logger_module::health_check_system::impl::impl (const health_check_criteria & criteria) inline explicit
Definition at line 45 of file health_check_system.cpp.
~impl()
logger_module::health_check_system::impl::~impl () inline
Definition at line 53 of file health_check_system.cpp.
References stop_monitoring().
Member Function Documentation
check_buffer_health_internal()
buffer_health_info logger_module::health_check_system::impl::check_buffer_health_internal () inline
Definition at line 150 of file health_check_system.cpp.
References logger_module::buffer_health_info::available_capacity, criteria_, logger_module::degraded, logger_module::healthy, logger_module::health_check_criteria::max_buffer_usage_percent, logger_module::health_check_criteria::min_available_buffer_size, logger_module::buffer_health_info::status, logger_module::buffer_health_info::total_capacity, logger_module::unhealthy, logger_module::buffer_health_info::usage_percent, and logger_module::buffer_health_info::used_capacity.
Referenced by perform_health_check().
check_queue_health_internal()
queue_health_info logger_module::health_check_system::impl::check_queue_health_internal () inline
Definition at line 173 of file health_check_system.cpp.
References criteria_, logger_module::queue_health_info::current_size, logger_module::degraded, logger_module::queue_health_info::dropped_messages, logger_module::log_collector::get_queue_metrics(), logger_module::healthy, logger_module::health_check_criteria::max_queue_size, logger_module::health_check_criteria::max_queue_usage_percent, logger_module::health_check_criteria::max_queue_wait_time, logger_module::queue_health_info::max_size, logger_module::queue_health_info::max_wait_time, logger_module::queue_health_info::status, logger_module::unhealthy, and logger_module::queue_health_info::usage_percent.
Referenced by perform_health_check().
check_writer_health()
result< writer_health_info > logger_module::health_check_system::impl::check_writer_health (const std::string & name) inline
Definition at line 139 of file health_check_system.cpp.
References logger_module::component_not_found.
configure_checks()
void logger_module::health_check_system::impl::configure_checks (bool check_writers, bool check_buffers, bool check_queues) inline
Definition at line 372 of file health_check_system.cpp.
get_all_writer_health()
std::unordered_map< std::string, writer_health_info > logger_module::health_check_system::impl::get_all_writer_health () const inline
Definition at line 336 of file health_check_system.cpp.
is_monitoring()
bool logger_module::health_check_system::impl::is_monitoring () const inline
Definition at line 332 of file health_check_system.cpp.
perform_health_check()
health_check_result logger_module::health_check_system::impl::perform_health_check () inline
Definition at line 80 of file health_check_system.cpp.
References logger_module::health_check_result::add_issue(), logger_module::health_check_utils::aggregate_health_status(), check_buffer_health_internal(), check_queue_health_internal(), logger_module::degraded, logger_module::health_check_result::get_status(), logger_module::healthy, logger_system::info, logger_module::health_check_result::set_message(), and logger_module::health_check_result::set_status().
Referenced by start_monitoring().
register_collector()
void logger_module::health_check_system::impl::register_collector (log_collector * collector) inline
Definition at line 75 of file health_check_system.cpp.
register_custom_check()
void logger_module::health_check_system::impl::register_custom_check (const std::string & name, std::function< health_status()> check) inline
Definition at line 366 of file health_check_system.cpp.
register_writer()
void logger_module::health_check_system::impl::register_writer (const std::string & name, base_writer * writer) inline
Definition at line 57 of file health_check_system.cpp.
References logger_module::healthy, logger_system::info, and logger_module::writer_health_info::writer_name.
reset_stats()
void logger_module::health_check_system::impl::reset_stats () inline
Definition at line 341 of file health_check_system.cpp.
References logger_module::healthy, and logger_system::info.
start_monitoring()
void logger_module::health_check_system::impl::start_monitoring (std::chrono::seconds interval, std::function< void(const health_check_result &)> callback) inline
Definition at line 298 of file health_check_system.cpp.
References perform_health_check().
stop_monitoring()
void logger_module::health_check_system::impl::stop_monitoring () inline
Definition at line 320 of file health_check_system.cpp.
Referenced by ~impl().
unregister_writer()
void logger_module::health_check_system::impl::unregister_writer (const std::string & name) inline
Definition at line 69 of file health_check_system.cpp.
update_buffer_stats()
void logger_module::health_check_system::impl::update_buffer_stats (size_t used, size_t total, bool allocation_failed) inline
Definition at line 250 of file health_check_system.cpp.
References logger_module::buffer_health_info::failed_allocations, logger_module::buffer_health_info::total_allocations, logger_module::buffer_health_info::total_capacity, and logger_module::buffer_health_info::used_capacity.
update_queue_stats()
void logger_module::health_check_system::impl::update_queue_stats (size_t current_size, size_t max_size, bool dropped, std::chrono::milliseconds wait_time) inline
Definition at line 262 of file health_check_system.cpp.
References logger_module::queue_health_info::avg_wait_time, logger_module::queue_health_info::current_size, logger_module::queue_health_info::dropped_messages, logger_module::queue_health_info::max_size, logger_module::queue_health_info::max_wait_time, logger_module::queue_health_info::total_dequeued, and logger_module::queue_health_info::total_enqueued.
update_writer_stats()
void logger_module::health_check_system::impl::update_writer_stats (const std::string & name, bool success, std::chrono::milliseconds latency) inline
Definition at line 201 of file health_check_system.cpp.
References criteria_, logger_module::degraded, logger_module::healthy, logger_system::info, logger_module::health_check_criteria::max_consecutive_write_failures, logger_module::health_check_criteria::max_write_latency, logger_module::success, and logger_module::unhealthy.
Member Data Documentation
criteria_
health_check_criteria logger_module::health_check_system::impl::criteria_
Definition at line 378 of file health_check_system.cpp.
Referenced by check_buffer_health_internal(), check_queue_health_internal(), and update_writer_stats().
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/health/health_check_system.cpp