Logger System: kcenon::logger::console_writer Class Reference
kcenon::logger::console_writer Class Reference
Core console writer for logging to stdout/stderr.
#include <console_writer.h>
Public Member Functions
console_writer (bool use_stderr=false, bool auto_detect_color=true, std::unique_ptr< log_formatter_interface > formatter=nullptr)
Constructor.
~console_writer () override
Destructor.
console_writer (const console_writer &)=delete
console_writer & operator= (const console_writer &)=delete
console_writer (console_writer &&)=delete
console_writer & operator= (console_writer &&)=delete
common::VoidResult write (const log_entry &entry) override
Write a log entry to console.
common::VoidResult flush () override
Flush console streams.
std::string get_name () const override
Get writer name.
bool is_healthy () const override
Check if writer is healthy.
void set_use_stderr (bool use_stderr)
Set whether to use stderr for all output.
void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
virtual common::VoidResult close ()
Close the writer and release resources.
virtual auto is_open () const -> bool
Check if writer is open and ready.
Protected Member Functions
std::string format_entry (const log_entry &entry) const
Format a log entry using the current formatter.
std::mutex & get_mutex () const
Access the writer mutex for extended operations.
Private Member Functions
bool is_color_supported () const
Check if terminal supports color.
Private Attributes
bool use_stderr_
bool use_color_ {true}
std::unique_ptr< log_formatter_interface > formatter_
std::mutex mutex_
Additional Inherited Members
Static Public Attributes inherited from kcenon::logger::sync_writer_tag
static constexpr writer_category category = writer_category::synchronous
Detailed Description
Core console writer for logging to stdout/stderr.
Pure console I/O implementation with direct mutex management. Designed to serve as the base layer in Decorator pattern compositions.
Features:
Color support for different log levels (if terminal supports it)
Thread-safe console output with internal mutex synchronization
Error levels go to stderr, others to stdout
Category: Synchronous (blocking I/O to console)
Since
1.0.0
1.3.0 Refactored to use thread_safe_writer base class
1.4.0 Added sync_writer_tag for category classification
4.0.0 Refactored for Decorator pattern with simplified inheritance
4.1.0 Directly implements log_writer_interface as core writer
Examples
composite_writer_example.cpp, and decorator_usage.cpp.
Definition at line 46 of file console_writer.h.
Constructor & Destructor Documentation
console_writer() [1/3]
kcenon::logger::console_writer::console_writer (bool use_stderr = false, bool auto_detect_color = true, std::unique_ptr< log_formatter_interface > formatter = nullptr) explicit
Constructor.
Parameters
use_stderr If true, all output goes to stderr (default: false)
auto_detect_color Auto-detect terminal color support (default: true)
formatter Custom log formatter (default: timestamp formatter)
Definition at line 25 of file console_writer.cpp.
    : use_stderr_(use_stderr)
    , formatter_(formatter ? std::move(formatter) : std::make_unique<timestamp_formatter>()) {
    if (auto_detect_color) {
        set_use_color(is_color_supported());
    } else {
        // Apply color setting to formatter
        auto opts = formatter_->get_options();
        opts.use_colors = use_color_;
        formatter_->set_options(opts);
    }
}
References formatter_, is_color_supported(), set_use_color(), and use_color_.
~console_writer()
kcenon::logger::console_writer::~console_writer () override
Destructor.
Definition at line 40 of file console_writer.cpp.
{
    flush();
}
References flush().
console_writer() [2/3]
kcenon::logger::console_writer::console_writer (const console_writer &) delete
console_writer() [3/3]
kcenon::logger::console_writer::console_writer (console_writer &&) delete
Member Function Documentation
flush()
common::VoidResult kcenon::logger::console_writer::flush () override virtual
Flush console streams.
Returns
common::VoidResult Success or error code
Implements kcenon::logger::log_writer_interface.
Definition at line 90 of file console_writer.cpp.
{
    std::lock_guard<std::mutex> lock(mutex_);
    return utils::try_write_operation([&]() -> common::VoidResult {
        std::cout.flush();
        std::cerr.flush();
        if (std::cout.fail() || std::cerr.fail()) {
            return make_logger_void_result(logger_error_code::flush_timeout, "Console flush failed");
        }
        return common::ok();
    }, logger_error_code::flush_timeout);
}
References kcenon::logger::flush_timeout, kcenon::logger::make_logger_void_result(), mutex_, kcenon::common::ok(), and kcenon::logger::utils::try_write_operation().
Referenced by ~console_writer().
format_entry()
std::string kcenon::logger::console_writer::format_entry (const log_entry & entry) const protected
Format a log entry using the current formatter.
Definition at line 126 of file console_writer.cpp.
{
    if (!formatter_) {
        // Fallback if formatter is somehow null
        return entry.message.to_string();
    }
    return formatter_->format(entry);
}
References formatter_, kcenon::logger::log_entry::message, and kcenon::logger::small_string< SSO_SIZE >::to_string().
Referenced by write().
get_mutex()
std::mutex & kcenon::logger::console_writer::get_mutex () const inline protected
Access the writer mutex for extended operations.
Returns
Reference to the internal mutex
Definition at line 120 of file console_writer.h.
{ return mutex_; }
get_name()
std::string kcenon::logger::console_writer::get_name () const inline override virtual
Get writer name.
Implements kcenon::logger::log_writer_interface.
Examples
decorator_usage.cpp.
Definition at line 85 of file console_writer.h.
{ return "console"; }
Referenced by example_core_writers().
is_color_supported()
bool kcenon::logger::console_writer::is_color_supported () const private
Check if terminal supports color.
Returns
true if color is supported
Definition at line 134 of file console_writer.cpp.
{
#ifdef _WIN32
    // Check if running in Windows Terminal or if ANSI is enabled
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    if (hOut == INVALID_HANDLE_VALUE) {
        return false;
    }
    DWORD dwMode = 0;
    if (!GetConsoleMode(hOut, &dwMode)) {
        return false;
    }
    // Check for ENABLE_VIRTUAL_TERMINAL_PROCESSING flag
    return (dwMode & 0x0004) != 0;
#else
    // Check if output is to a terminal and TERM is set
    const char* term = std::getenv("TERM");
    return isatty(STDOUT_FILENO) && term && std::string(term) != "dumb";
#endif
}
Referenced by console_writer().
is_healthy()
bool kcenon::logger::console_writer::is_healthy () const override virtual
Check if writer is healthy.
Implements kcenon::logger::log_writer_interface.
Definition at line 104 of file console_writer.cpp.
{
    return std::cout.good() && std::cerr.good();
}
operator=() [1/2]
console_writer & kcenon::logger::console_writer::operator= (console_writer &&) delete
operator=() [2/2]
console_writer & kcenon::logger::console_writer::operator= (const console_writer &) delete
set_use_color()
void kcenon::logger::console_writer::set_use_color (bool use_color)
Set whether to use color output (if supported)
Parameters
use_color true to enable color output, false to disable
Definition at line 113 of file console_writer.cpp.
{
    use_color_ = use_color;
    if (formatter_) {
        auto opts = formatter_->get_options();
        opts.use_colors = use_color_;
        formatter_->set_options(opts);
    }
}
References formatter_, use_color(), and use_color_.
Referenced by console_writer().
set_use_stderr()
void kcenon::logger::console_writer::set_use_stderr (bool use_stderr)
Set whether to use stderr for all output.
Parameters
use_stderr Enable/disable stderr usage
Definition at line 108 of file console_writer.cpp.
{
    std::lock_guard<std::mutex> lock(mutex_);
    use_stderr_ = use_stderr;
}
References mutex_, and use_stderr_.
use_color()
bool kcenon::logger::console_writer::use_color () const
Get current color output setting.
Returns
true if color output is enabled, false otherwise
Definition at line 122 of file console_writer.cpp.
{
    return use_color_;
}
References use_color_.
Referenced by set_use_color(), and write().
write()
common::VoidResult kcenon::logger::console_writer::write (const log_entry & entry) override virtual
Write a log entry to console.
Parameters
entry The log entry to write
Returns
common::VoidResult Success or error code
Implements kcenon::logger::log_writer_interface.
Examples
composite_writer_example.cpp.
Definition at line 44 of file console_writer.cpp.
{
    std::lock_guard<std::mutex> lock(mutex_);
    return utils::try_write_operation([&]() -> common::VoidResult {
        // Convert logger_system::log_level to common::interfaces::log_level for comparison
        auto level = static_cast<common::interfaces::log_level>(static_cast<int>(entry.level));
        auto& stream = (use_stderr_ || level <= common::interfaces::log_level::error)
                       ? std::cerr : std::cout;
        if (use_color()) {
            // Simple color mapping based on level
            switch (level) {
                case common::interfaces::log_level::fatal:
                case common::interfaces::log_level::error:
                    stream << "\033[31m"; // Red
                    break;
                case common::interfaces::log_level::warning:
                    stream << "\033[33m"; // Yellow
                    break;
                case common::interfaces::log_level::info:
                    stream << "\033[32m"; // Green
                    break;
                case common::interfaces::log_level::debug:
                    stream << "\033[36m"; // Cyan
                    break;
                case common::interfaces::log_level::trace:
                    stream << "\033[37m"; // White
                    break;
                default:
                    break;
            }
        }
        stream << format_entry(entry);
        if (use_color()) {
            stream << "\033[0m"; // Reset color
        }
        stream << '\n';
        // Verify stream state
        return utils::check_stream_state(stream, "console write");
    }, logger_error_code::processing_failed);
}
References kcenon::logger::utils::check_stream_state(), format_entry(), kcenon::logger::log_entry::level, mutex_, kcenon::logger::processing_failed, kcenon::logger::utils::try_write_operation(), use_color(), and use_stderr_.
Referenced by main().
Member Data Documentation
formatter_
std::unique_ptr<log_formatter_interface> kcenon::logger::console_writer::formatter_ private
Definition at line 132 of file console_writer.h.
Referenced by console_writer(), format_entry(), and set_use_color().
mutex_
std::mutex kcenon::logger::console_writer::mutex_ mutable private
Definition at line 133 of file console_writer.h.
Referenced by flush(), set_use_stderr(), and write().
use_color_
bool kcenon::logger::console_writer::use_color_ {true} private
Definition at line 131 of file console_writer.h.
{true};
Referenced by console_writer(), set_use_color(), and use_color().
use_stderr_
bool kcenon::logger::console_writer::use_stderr_ private
Definition at line 130 of file console_writer.h.
Referenced by set_use_stderr(), and write().
The documentation for this class was generated from the following files:
include/kcenon/logger/writers/console_writer.h
src/impl/writers/console_writer.cpp