Logger System: logger_module::composite_strategy Class Reference
logger_module::composite_strategy Class Reference
Combines multiple strategies in sequence.
#include <config_strategy_interface.h>
Public Member Functions
composite_strategy ()=default
void add_strategy (std::unique_ptr< config_strategy_interface > strategy)
Add a strategy to the composite.
result_void apply (logger_config &config) override
Apply the strategy to a configuration.
std::string get_name () const override
Get strategy name for identification.
std::string get_description () const override
Get strategy description.
result_void can_apply (const logger_config &config) const override
Validate if this strategy can be applied.
virtual int get_priority () const
Get the priority of this strategy (higher = applied first)
virtual bool should_override () const
Check if this strategy should override existing settings.
Detailed Description
Combines multiple strategies in sequence.
Definition at line 322 of file config_strategy_interface.h.
Constructor & Destructor Documentation
composite_strategy()
logger_module::composite_strategy::composite_strategy () default
Member Function Documentation
add_strategy()
void logger_module::composite_strategy::add_strategy (std::unique_ptr< config_strategy_interface > strategy) inline
Add a strategy to the composite.
Parameters
strategy Strategy to add
Definition at line 330 of file config_strategy_interface.h.
apply()
result_void logger_module::composite_strategy::apply (logger_config & config) inline override virtual
Apply the strategy to a configuration.
Parameters
config Configuration to modify
Returns
result_void indicating success or error
Implements logger_module::config_strategy_interface.
Definition at line 339 of file config_strategy_interface.h.
References can_apply().
can_apply()
result_void logger_module::composite_strategy::can_apply (const logger_config & config) const inline override virtual
Validate if this strategy can be applied.
Parameters
config Current configuration
Returns
result_void indicating if strategy is applicable
Implements logger_module::config_strategy_interface.
Definition at line 365 of file config_strategy_interface.h.
References can_apply(), logger_module::invalid_configuration, and logger_module::make_logger_error().
Referenced by apply(), and can_apply().
get_description()
std::string logger_module::composite_strategy::get_description () const inline override virtual
Get strategy description.
Returns
Human-readable description
Implements logger_module::config_strategy_interface.
Definition at line 356 of file config_strategy_interface.h.
get_name()
std::string logger_module::composite_strategy::get_name () const inline override virtual
Get strategy name for identification.
Returns
Strategy name
Implements logger_module::config_strategy_interface.
Definition at line 352 of file config_strategy_interface.h.
get_priority()
virtual int logger_module::config_strategy_interface::get_priority () const inline virtual inherited
Get the priority of this strategy (higher = applied first)
Returns
Priority value (0-100)
Implemented in logger_module::environment_strategy, and logger_module::performance_tuning_strategy.
Definition at line 64 of file config_strategy_interface.h.
should_override()
virtual bool logger_module::config_strategy_interface::should_override () const inline virtual inherited
Check if this strategy should override existing settings.
Returns
true if strategy should override, false to merge
Implemented in logger_module::template_strategy.
Definition at line 70 of file config_strategy_interface.h.
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/config/config_strategy_interface.h