Logger System: kcenon::logger::filter_factory::builder Class Reference
kcenon::logger::filter_factory::builder Class Reference
Filter builder for complex filter construction.
#include <filter_factory.h>
Public Member Functions
builder & with_min_level (log_level level)
Set minimum log level.
builder & include_pattern (const std::string &pattern)
Include messages matching pattern.
builder & exclude_pattern (const std::string &pattern)
Exclude messages matching pattern.
builder & with_predicate (std::function< bool(const log_entry &)> pred)
Add custom filter function.
std::unique_ptr< log_filter_interface > build ()
Build the composite filter.
Private Attributes
std::vector< std::unique_ptr< log_filter_interface > > filters_
Detailed Description
Filter builder for complex filter construction.
Definition at line 159 of file filter_factory.h.
Member Function Documentation
build()
std::unique_ptr< log_filter_interface > kcenon::logger::filter_factory::builder::build () inline
Build the composite filter.
Returns
Unique pointer to composite filter
Definition at line 197 of file filter_factory.h.
{
            if (filters_.empty()) {
                return nullptr;
            }
            if (filters_.size() == 1) {
                return std::move(filters_[0]);
            }
            auto composite = create_composite_and();
            for (auto& filter : filters_) {
                composite->add_filter(std::move(filter));
            }
            return composite;
        }
References kcenon::logger::composite, kcenon::logger::filter_factory::create_composite_and(), and filters_.
exclude_pattern()
builder & kcenon::logger::filter_factory::builder::exclude_pattern (const std::string & pattern) inline
Exclude messages matching pattern.
Definition at line 180 of file filter_factory.h.
{
            filters_.push_back(create_regex(pattern, false));
            return *this;
        }
References kcenon::logger::filter_factory::create_regex(), and filters_.
include_pattern()
builder & kcenon::logger::filter_factory::builder::include_pattern (const std::string & pattern) inline
Include messages matching pattern.
Definition at line 172 of file filter_factory.h.
{
            filters_.push_back(create_regex(pattern, true));
            return *this;
        }
References kcenon::logger::filter_factory::create_regex(), and filters_.
with_min_level()
builder & kcenon::logger::filter_factory::builder::with_min_level (log_level level) inline
Set minimum log level.
Definition at line 164 of file filter_factory.h.
{
            filters_.push_back(create_level(level));
            return *this;
        }
References kcenon::logger::filter_factory::create_level(), and filters_.
with_predicate()
builder & kcenon::logger::filter_factory::builder::with_predicate (std::function< bool(const log_entry &)> pred) inline
Add custom filter function.
Definition at line 188 of file filter_factory.h.
{
            filters_.push_back(create_function(std::move(pred)));
            return *this;
        }
References kcenon::logger::filter_factory::create_function(), and filters_.
Member Data Documentation
filters_
std::vector<std::unique_ptr<log_filter_interface> > kcenon::logger::filter_factory::builder::filters_ private
Definition at line 213 of file filter_factory.h.
Referenced by build(), exclude_pattern(), include_pattern(), with_min_level(), and with_predicate().
The documentation for this class was generated from the following file:
include/kcenon/logger/factories/filter_factory.h