Logger System: logger_module::basic_monitor Class Reference
logger_module::basic_monitor Class Reference
Basic monitoring implementation.
#include <basic_monitor.h>
Public Member Functions
basic_monitor ()
Constructor.
~basic_monitor () override=default
Destructor.
result< monitoring_data > collect_metrics () const override
Collect current metrics.
result< health_check_result > check_health () const override
Perform health check.
result_void reset_metrics () override
Reset all metrics.
result_void set_enabled (bool enable) override
Enable or disable monitoring.
bool is_enabled () const override
Check if monitoring is enabled.
std::string get_backend_name () const override
Get backend name.
void increment_counter (const std::string &name, double value=1.0) override
Increment a counter.
void update_gauge (const std::string &name, double value) override
Update a gauge.
void record_histogram (const std::string &name, double value) override
Record a histogram value.
void add_health_issue (const std::string &issue)
Add a health issue.
void clear_health_issues ()
Clear health issues.
Detailed Description
Basic monitoring implementation.
This implementation provides essential monitoring capabilities with minimal overhead and no external dependencies.
Definition at line 36 of file basic_monitor.h.
Constructor & Destructor Documentation
basic_monitor()
logger_module::basic_monitor::basic_monitor () inline
Constructor.
Definition at line 73 of file basic_monitor.h.
~basic_monitor()
logger_module::basic_monitor::~basic_monitor () override default
Destructor.
Member Function Documentation
add_health_issue()
void logger_module::basic_monitor::add_health_issue (const std::string & issue) inline
Add a health issue.
Parameters
issue Issue description
Definition at line 416 of file basic_monitor.h.
check_health()
result< health_check_result > logger_module::basic_monitor::check_health () const inline override virtual
Perform health check.
Returns
Result containing health check result
Implements logger_module::monitoring_interface.
Definition at line 190 of file basic_monitor.h.
References logger_module::health_check_result::add_issue(), logger_module::degraded, logger_module::health_check_result::get_status(), logger_module::healthy, logger_module::health_check_result::is_healthy(), logger_module::health_check_result::set_message(), logger_module::health_check_result::set_status(), and logger_module::unhealthy.
clear_health_issues()
void logger_module::basic_monitor::clear_health_issues () inline
Clear health issues.
Definition at line 424 of file basic_monitor.h.
collect_metrics()
result< monitoring_data > logger_module::basic_monitor::collect_metrics () const inline override virtual
Collect current metrics.
Returns
Result containing monitoring data
Implements logger_module::monitoring_interface.
Definition at line 84 of file basic_monitor.h.
References logger_module::monitoring_data::add_metric(), logger_module::counter, logger_module::gauge, logger_module::metrics_not_available, and logger_module::summary.
get_backend_name()
std::string logger_module::basic_monitor::get_backend_name () const inline override virtual
Get backend name.
Returns
"basic" for this implementation
Implements logger_module::monitoring_interface.
Definition at line 318 of file basic_monitor.h.
increment_counter()
void logger_module::basic_monitor::increment_counter (const std::string & name, double value = 1.0) inline override virtual
Increment a counter.
Parameters
name Counter name
value Increment value
Implements logger_module::monitoring_interface.
Definition at line 327 of file basic_monitor.h.
is_enabled()
bool logger_module::basic_monitor::is_enabled () const inline override virtual
Check if monitoring is enabled.
Returns
true if enabled
Implements logger_module::monitoring_interface.
Definition at line 310 of file basic_monitor.h.
record_histogram()
void logger_module::basic_monitor::record_histogram (const std::string & name, double value) inline override virtual
Record a histogram value.
Parameters
name Histogram name
value Value to record
Implements logger_module::monitoring_interface.
Definition at line 379 of file basic_monitor.h.
reset_metrics()
result_void logger_module::basic_monitor::reset_metrics () inline override virtual
Reset all metrics.
Returns
Result indicating success
Implements logger_module::monitoring_interface.
Definition at line 268 of file basic_monitor.h.
set_enabled()
result_void logger_module::basic_monitor::set_enabled (bool enable) inline override virtual
Enable or disable monitoring.
Parameters
enable true to enable
Returns
Result indicating success
Implements logger_module::monitoring_interface.
Definition at line 301 of file basic_monitor.h.
update_gauge()
void logger_module::basic_monitor::update_gauge (const std::string & name, double value) inline override virtual
Update a gauge.
Parameters
name Gauge name
value New value
Implements logger_module::monitoring_interface.
Definition at line 349 of file basic_monitor.h.
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/monitoring/basic_monitor.h