Logger System: kcenon::logger::sampling::sampler_factory Class Reference
kcenon::logger::sampling::sampler_factory Class Reference
Factory for creating pre-configured samplers.
#include <log_sampler.h>
Static Public Member Functions
static std::unique_ptr< log_sampler > create_disabled ()
Create a disabled sampler (pass-through)
static std::unique_ptr< log_sampler > create_random (double rate)
Create a random sampling sampler.
static std::unique_ptr< log_sampler > create_rate_limited (std::size_t max_per_second)
Create a rate limiting sampler.
static std::unique_ptr< log_sampler > create_adaptive (std::size_t threshold=10000, double min_rate=0.01)
Create an adaptive sampler.
static std::unique_ptr< log_sampler > create_production (double base_rate=0.1, std::vector< log_level > critical_levels={ log_level::warn, log_level::error, log_level::fatal })
Create a production-ready sampler.
Detailed Description
Factory for creating pre-configured samplers.
Since
3.3.0
Definition at line 294 of file log_sampler.h.
Member Function Documentation
create_adaptive()
std::unique_ptr< log_sampler > kcenon::logger::sampling::sampler_factory::create_adaptive (std::size_t threshold = 10000, double min_rate = 0.01) static
Create an adaptive sampler.
Parameters
threshold Threshold to trigger adaptation
min_rate Minimum rate under load
Returns
Configured adaptive sampler
Definition at line 477 of file log_sampler.cpp.
                     {
    return std::make_unique<log_sampler>(sampling_config::adaptive(threshold, min_rate));
}
References kcenon::logger::sampling::sampling_config::adaptive().
create_disabled()
std::unique_ptr< log_sampler > kcenon::logger::sampling::sampler_factory::create_disabled () static
Create a disabled sampler (pass-through)
Returns
Sampler that passes all logs
Definition at line 465 of file log_sampler.cpp.
{
    return std::make_unique<log_sampler>(sampling_config::disabled());
}
References kcenon::logger::sampling::sampling_config::disabled().
create_production()
std::unique_ptr< log_sampler > kcenon::logger::sampling::sampler_factory::create_production (double base_rate = 0.1, std::vector< log_level > critical_levels = { log_level::warn, log_level::error, log_level::fatal }) static
Create a production-ready sampler.
Parameters
base_rate Base sampling rate
critical_levels Levels that bypass sampling
Returns
Production-configured sampler
Definition at line 483 of file log_sampler.cpp.
{
    sampling_config config;
    config.enabled = true;
    config.rate = base_rate;
    config.strategy = sampling_strategy::adaptive;
    config.adaptive_enabled = true;
    config.adaptive_threshold = 50000;
    config.adaptive_min_rate = 0.01;
    config.always_log_levels = std::move(critical_levels);
    return std::make_unique<log_sampler>(config);
}
References kcenon::logger::sampling::adaptive, kcenon::logger::sampling::sampling_config::adaptive_enabled, kcenon::logger::sampling::sampling_config::adaptive_min_rate, kcenon::logger::sampling::sampling_config::adaptive_threshold, kcenon::logger::sampling::sampling_config::always_log_levels, kcenon::logger::sampling::sampling_config::enabled, kcenon::logger::sampling::sampling_config::rate, and kcenon::logger::sampling::sampling_config::strategy.
create_random()
std::unique_ptr< log_sampler > kcenon::logger::sampling::sampler_factory::create_random (double rate) static
Create a random sampling sampler.
Parameters
rate Sampling rate (0.0 to 1.0)
Returns
Configured random sampler
Definition at line 469 of file log_sampler.cpp.
{
    return std::make_unique<log_sampler>(sampling_config::random_sampling(rate));
}
References kcenon::logger::sampling::sampling_config::random_sampling().
create_rate_limited()
std::unique_ptr< log_sampler > kcenon::logger::sampling::sampler_factory::create_rate_limited (std::size_t max_per_second) static
Create a rate limiting sampler.
Parameters
max_per_second Maximum logs per second
Returns
Configured rate limiting sampler
Definition at line 473 of file log_sampler.cpp.
{
    return std::make_unique<log_sampler>(sampling_config::rate_limited(max_per_second));
}
References kcenon::logger::sampling::sampling_config::rate_limited().
The documentation for this class was generated from the following files:
include/kcenon/logger/sampling/log_sampler.h
src/sampling/log_sampler.cpp