Logger System: kcenon::logger::decorator_writer_base Class Reference
kcenon::logger::decorator_writer_base Class Reference abstract
Abstract base class for decorator pattern log writers.
#include <decorator_writer_base.h>
Public Member Functions
decorator_writer_base (std::unique_ptr< log_writer_interface > wrapped, std::string_view decorator_name)
Construct a decorator writer base.
~decorator_writer_base () override=default
Virtual destructor for proper cleanup.
decorator_writer_base (const decorator_writer_base &)=delete
decorator_writer_base & operator= (const decorator_writer_base &)=delete
decorator_writer_base (decorator_writer_base &&) noexcept=default
decorator_writer_base & operator= (decorator_writer_base &&) noexcept=default
common::VoidResult write (const log_entry &entry) override=0
Write a log entry (must be implemented by derived classes)
common::VoidResult flush () override
Flush the wrapped writer.
std::string get_name () const override
Get the name of this writer.
bool is_healthy () const override
Check if the writer is healthy.
const log_writer_interface * get_wrapped_writer () const noexcept
Get the wrapped writer (const version)
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
virtual common::VoidResult close ()
Close the writer and release resources.
virtual auto is_open () const -> bool
Check if writer is open and ready.
Protected Member Functions
log_writer_interface & wrapped () noexcept
Access the wrapped writer (non-const)
const log_writer_interface & wrapped () const noexcept
Access the wrapped writer (const)
const std::string & decorator_name () const noexcept
Get the decorator name.
Private Attributes
std::unique_ptr< log_writer_interface > wrapped_
std::string decorator_name_
Additional Inherited Members
Static Public Attributes inherited from kcenon::logger::decorator_writer_tag
static constexpr writer_category category = writer_category::decorator
Detailed Description
Abstract base class for decorator pattern log writers.
This class provides common functionality for all decorator writers:
Wrapped writer storage and lifecycle management
Default implementations for get_name(), is_healthy(), and flush()
Protected access to wrapped writer for derived classes
Derived classes only need to implement write() with their specific behavior.
Key features:
Accepts any log_writer_interface implementation (not just base_writer)
Enables unlimited decorator stacking
Thread-safety depends on the wrapped writer
Follows Liskov Substitution Principle
Category: Decorator (wraps another writer)
Note
This is an abstract class; derived classes must implement write().
Since
4.0.0
Definition at line 71 of file decorator_writer_base.h.
Constructor & Destructor Documentation
decorator_writer_base() [1/3]
kcenon::logger::decorator_writer_base::decorator_writer_base (std::unique_ptr< log_writer_interface > wrapped, std::string_view decorator_name) explicit
Construct a decorator writer base.
Parameters
wrapped The writer to wrap with this decorator
decorator_name Name prefix for this decorator (e.g., "async", "filtered")
Exceptions
std::invalid_argument if wrapped is nullptr
Since
4.0.0
Definition at line 18 of file decorator_writer_base.cpp.
    : wrapped_(std::move(wrapped)), decorator_name_(decorator_name) {
    if (!wrapped_) {
        throw std::invalid_argument("decorator_writer_base: wrapped writer cannot be nullptr");
    }
}
References wrapped_.
~decorator_writer_base()
kcenon::logger::decorator_writer_base::~decorator_writer_base () override default
Virtual destructor for proper cleanup.
decorator_writer_base() [2/3]
kcenon::logger::decorator_writer_base::decorator_writer_base (const decorator_writer_base &) delete
decorator_writer_base() [3/3]
kcenon::logger::decorator_writer_base::decorator_writer_base (decorator_writer_base &&) default noexcept
Member Function Documentation
decorator_name()
const std::string & kcenon::logger::decorator_writer_base::decorator_name () const protected noexcept
Get the decorator name.
Returns
The decorator name string
Since
4.0.0
Definition at line 50 of file decorator_writer_base.cpp.
{
    return decorator_name_;
}
References decorator_name_.
flush()
common::VoidResult kcenon::logger::decorator_writer_base::flush () override virtual
Flush the wrapped writer.
Returns
common::VoidResult from the wrapped writer's flush operation
Default implementation delegates to wrapped writer. Override if additional flush behavior is needed.
Since
4.0.0
Implements kcenon::logger::log_writer_interface.
Definition at line 26 of file decorator_writer_base.cpp.
{
    return wrapped_->flush();
}
References wrapped_.
get_name()
std::string kcenon::logger::decorator_writer_base::get_name () const override virtual
Get the name of this writer.
Returns
String in format "<decorator_name>_<wrapped_name>"
Default implementation combines decorator name with wrapped writer's name. Override for custom naming behavior.
Since
4.0.0
Implements kcenon::logger::log_writer_interface.
Reimplemented in kcenon::logger::filtered_writer, and kcenon::logger::formatted_writer.
Examples
decorator_usage.cpp.
Definition at line 30 of file decorator_writer_base.cpp.
{
    return decorator_name_ + "_" + wrapped_->get_name();
}
References decorator_name_, and wrapped_.
Referenced by example_single_decorators(), kcenon::logger::filtered_writer::get_name(), and kcenon::logger::formatted_writer::get_name().
get_wrapped_writer()
const log_writer_interface * kcenon::logger::decorator_writer_base::get_wrapped_writer () const noexcept
Get the wrapped writer (const version)
Returns
Const pointer to the wrapped writer
Since
4.0.0
Definition at line 38 of file decorator_writer_base.cpp.
{
    return wrapped_.get();
}
References wrapped_.
is_healthy()
bool kcenon::logger::decorator_writer_base::is_healthy () const override virtual
Check if the writer is healthy.
Returns
Health status of the wrapped writer
Default implementation delegates to wrapped writer. Override to add additional health checks.
Since
4.0.0
Implements kcenon::logger::log_writer_interface.
Reimplemented in kcenon::logger::queued_writer_base< Container >, kcenon::logger::queued_writer_base< std::queue< log_entry > >, and kcenon::logger::queued_writer_base< std::vector< log_entry > >.
Definition at line 34 of file decorator_writer_base.cpp.
{
    return wrapped_->is_healthy();
}
References wrapped_.
operator=() [1/2]
decorator_writer_base & kcenon::logger::decorator_writer_base::operator= (const decorator_writer_base &) delete
operator=() [2/2]
decorator_writer_base & kcenon::logger::decorator_writer_base::operator= (decorator_writer_base &&) default noexcept
wrapped() [1/2]
const log_writer_interface & kcenon::logger::decorator_writer_base::wrapped () const protected noexcept
Access the wrapped writer (const)
Returns
Const reference to the wrapped writer
Since
4.0.0
Definition at line 46 of file decorator_writer_base.cpp.
{
    return *wrapped_;
}
References wrapped_.
wrapped() [2/2]
log_writer_interface & kcenon::logger::decorator_writer_base::wrapped () protected noexcept
Access the wrapped writer (non-const)
Returns
Reference to the wrapped writer
Note
Use this in derived classes to delegate operations
Since
4.0.0
Definition at line 42 of file decorator_writer_base.cpp.
{
    return *wrapped_;
}
References wrapped_.
Referenced by kcenon::logger::async_writer::flush(), kcenon::logger::batch_writer::flush_batch_unsafe(), kcenon::logger::buffered_writer::flush_buffer_unsafe(), kcenon::logger::async_writer::flush_remaining(), kcenon::logger::async_writer::get_name(), kcenon::logger::batch_writer::get_name(), kcenon::logger::filtered_writer::get_name(), kcenon::logger::formatted_writer::get_name(), kcenon::logger::async_writer::is_healthy(), kcenon::logger::batch_writer::is_healthy(), kcenon::logger::queued_writer_base< Container >::is_healthy(), kcenon::logger::async_writer::process_messages(), kcenon::logger::async_writer::write(), kcenon::logger::filtered_writer::write(), and kcenon::logger::formatted_writer::write().
write()
common::VoidResult kcenon::logger::decorator_writer_base::write (const log_entry & entry) override pure virtual
Write a log entry (must be implemented by derived classes)
Parameters
entry The log entry to write
Returns
common::VoidResult indicating success or failure
Since
4.0.0
Implements kcenon::logger::log_writer_interface.
Implemented in kcenon::logger::async_writer, kcenon::logger::batch_writer, kcenon::logger::buffered_writer, kcenon::logger::encrypted_writer, kcenon::logger::filtered_writer, and kcenon::logger::formatted_writer.
Member Data Documentation
decorator_name_
std::string kcenon::logger::decorator_writer_base::decorator_name_ private
Definition at line 186 of file decorator_writer_base.h.
Referenced by decorator_name(), and get_name().
wrapped_
std::unique_ptr<log_writer_interface> kcenon::logger::decorator_writer_base::wrapped_ private
Definition at line 185 of file decorator_writer_base.h.
Referenced by decorator_writer_base(), flush(), get_name(), get_wrapped_writer(), is_healthy(), wrapped(), and wrapped().
The documentation for this class was generated from the following files:
include/kcenon/logger/writers/decorator_writer_base.h
src/impl/writers/decorator_writer_base.cpp