Logger System: kcenon::logger::logger_config_builder Class Reference
kcenon::logger::logger_config_builder Class Reference
Fluent builder for logger_config.
#include <logger_config_builder.h>
Public Member Functions
logger_config_builder ()=default
Default constructor - starts with default configuration.
logger_config_builder & use_default_config ()
Use default configuration as base.
logger_config_builder & use_production_defaults ()
Use production configuration as base.
logger_config_builder & use_debug_defaults ()
Use debug configuration as base.
logger_config_builder & use_high_performance_defaults ()
Use high-performance configuration as base.
logger_config_builder & use_low_latency_defaults ()
Use low-latency configuration as base.
logger_config_builder & set_async (bool enabled)
Set asynchronous logging mode.
logger_config_builder & set_buffer_size (std::size_t size)
Set buffer size.
logger_config_builder & set_min_level (log_level level)
Set minimum log level.
logger_config_builder & set_batch_size (std::size_t size)
Set batch size for batch writing.
logger_config_builder & set_flush_interval (std::chrono::milliseconds interval)
Set flush interval.
logger_config_builder & use_lock_free (bool enabled)
Enable/disable lock-free queue.
logger_config_builder & set_max_writers (std::size_t max)
Set maximum number of writers.
logger_config_builder & enable_batch_writing (bool enabled)
Enable/disable batch writing.
logger_config_builder & set_writer_thread_count (std::size_t count)
Set writer thread count.
logger_config_builder & enable_metrics (bool enabled)
Enable/disable metrics collection.
logger_config_builder & enable_crash_handler (bool enabled)
Enable/disable crash handler.
logger_config_builder & enable_structured_logging (bool enabled)
Enable/disable structured logging.
logger_config_builder & enable_color_output (bool enabled)
Enable/disable color output.
logger_config_builder & enable_timestamp (bool enabled)
Enable/disable timestamp in log messages.
logger_config_builder & enable_source_location (bool enabled)
Enable/disable source location in log messages.
logger_config_builder & enable_compression (bool enabled)
Enable/disable compression.
logger_config_builder & set_max_queue_size (std::size_t size)
Set maximum queue size.
logger_config_builder & set_overflow_policy (logger_config::overflow_policy policy)
Set queue overflow policy.
logger_config_builder & set_max_file_size (std::size_t size)
Set maximum file size for rotation.
logger_config_builder & set_max_file_count (std::size_t count)
Set maximum number of rotated files.
logger_config_builder & set_log_directory (const std::string &directory)
Set log directory.
logger_config_builder & set_log_file_prefix (const std::string &prefix)
Set log file prefix.
logger_config_builder & set_remote_logging (const std::string &host, uint16_t port)
Set remote logging host.
logger_config_builder & set_network_timeout (std::chrono::milliseconds timeout)
Set network timeout.
logger_config_builder & set_network_retry_count (std::size_t count)
Set network retry count.
result< logger_config > build () const
Build the logger_config.
logger_config build_unchecked () const
Build the logger_config without validation.
logger_config_builder & reset ()
Reset to default configuration.
Private Attributes
logger_config config_
Detailed Description
Fluent builder for logger_config.
Provides a convenient and type-safe builder pattern for constructing logger_config instances. Supports preset configurations and individual parameter customization.
Example usage:
auto config = logger_config_builder()
    .use_production_defaults()
    .set_min_level(log_level::warn)
    .set_buffer_size(32768)
    .enable_metrics(true)
    .build();
Note
This class is part of Sprint 4: Builder Pattern & Config initiative
Examples
logger_config_builder_example.cpp.
Definition at line 39 of file logger_config_builder.h.
Constructor & Destructor Documentation
logger_config_builder()
kcenon::logger::logger_config_builder::logger_config_builder () default
Default constructor - starts with default configuration.
Member Function Documentation
build()
result< logger_config > kcenon::logger::logger_config_builder::build () const inline
Build the logger_config.
Returns
result<logger_config> containing the config or validation error
Validates the configuration and returns it if valid.
Examples
logger_config_builder_example.cpp.
Definition at line 381 of file logger_config_builder.h.
{
        auto validation_result = config_.validate();
        if (!validation_result.is_ok()) {
            return result<logger_config>{
                logger_error_code::invalid_configuration,
                "Configuration validation failed: " + validation_result.error().message};
        }
        return result<logger_config>(config_);
    }
References config_, kcenon::logger::invalid_configuration, and kcenon::logger::logger_config::validate().
Referenced by main().
build_unchecked()
logger_config kcenon::logger::logger_config_builder::build_unchecked () const inline
Build the logger_config without validation.
Returns
logger_config instance
Warning
Use only if you are certain the configuration is valid
Definition at line 396 of file logger_config_builder.h.
{
        return config_;
    }
References config_.
enable_batch_writing()
logger_config_builder & kcenon::logger::logger_config_builder::enable_batch_writing (bool enabled) inline
Enable/disable batch writing.
Parameters
enabled true to enable batch writing
Returns
Reference to builder for chaining
Definition at line 178 of file logger_config_builder.h.
{
        config_.enable_batch_writing = enabled;
        return *this;
    }
References config_, and kcenon::logger::logger_config::enable_batch_writing.
enable_color_output()
logger_config_builder & kcenon::logger::logger_config_builder::enable_color_output (bool enabled) inline
Enable/disable color output.
Parameters
enabled true to enable color output
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 232 of file logger_config_builder.h.
{
        config_.enable_color_output = enabled;
        return *this;
    }
References config_, and kcenon::logger::logger_config::enable_color_output.
Referenced by main().
enable_compression()
logger_config_builder & kcenon::logger::logger_config_builder::enable_compression (bool enabled) inline
Enable/disable compression.
Parameters
enabled true to enable compression
Returns
Reference to builder for chaining
Definition at line 262 of file logger_config_builder.h.
{
        config_.enable_compression = enabled;
        return *this;
    }
References config_, and kcenon::logger::logger_config::enable_compression.
enable_crash_handler()
logger_config_builder & kcenon::logger::logger_config_builder::enable_crash_handler (bool enabled) inline
Enable/disable crash handler.
Parameters
enabled true to enable crash handler
Returns
Reference to builder for chaining
Definition at line 212 of file logger_config_builder.h.
{
        config_.enable_crash_handler = enabled;
        return *this;
    }
References config_, and kcenon::logger::logger_config::enable_crash_handler.
enable_metrics()
logger_config_builder & kcenon::logger::logger_config_builder::enable_metrics (bool enabled) inline
Enable/disable metrics collection.
Parameters
enabled true to enable metrics
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 202 of file logger_config_builder.h.
{
        config_.enable_metrics = enabled;
        return *this;
    }
References config_, and kcenon::logger::logger_config::enable_metrics.
Referenced by main().
enable_source_location()
logger_config_builder & kcenon::logger::logger_config_builder::enable_source_location (bool enabled) inline
Enable/disable source location in log messages.
Parameters
enabled true to enable source location
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 252 of file logger_config_builder.h.
{
        config_.enable_source_location = enabled;
        return *this;
    }
References config_, and kcenon::logger::logger_config::enable_source_location.
Referenced by main().
enable_structured_logging()
logger_config_builder & kcenon::logger::logger_config_builder::enable_structured_logging (bool enabled) inline
Enable/disable structured logging.
Parameters
enabled true to enable structured logging
Returns
Reference to builder for chaining
Definition at line 222 of file logger_config_builder.h.
{
        config_.enable_structured_logging = enabled;
        return *this;
    }
References config_, and kcenon::logger::logger_config::enable_structured_logging.
enable_timestamp()
logger_config_builder & kcenon::logger::logger_config_builder::enable_timestamp (bool enabled) inline
Enable/disable timestamp in log messages.
Parameters
enabled true to enable timestamp
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 242 of file logger_config_builder.h.
{
        config_.enable_timestamp = enabled;
        return *this;
    }
References config_, and kcenon::logger::logger_config::enable_timestamp.
Referenced by main().
reset()
logger_config_builder & kcenon::logger::logger_config_builder::reset () inline
Reset to default configuration.
Returns
Reference to builder for chaining
Definition at line 404 of file logger_config_builder.h.
{
        config_ = logger_config{};
        return *this;
    }
References config_.
set_async()
logger_config_builder & kcenon::logger::logger_config_builder::set_async (bool enabled) inline
Set asynchronous logging mode.
Parameters
enabled true to enable async logging
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 104 of file logger_config_builder.h.
{
        config_.async = enabled;
        return *this;
    }
References kcenon::logger::logger_config::async, and config_.
Referenced by main().
set_batch_size()
logger_config_builder & kcenon::logger::logger_config_builder::set_batch_size (std::size_t size) inline
Set batch size for batch writing.
Parameters
size Number of messages to batch together
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 138 of file logger_config_builder.h.
{
        config_.batch_size = size;
        return *this;
    }
References kcenon::logger::logger_config::batch_size, config_, and kcenon::logger::size.
Referenced by main().
set_buffer_size()
logger_config_builder & kcenon::logger::logger_config_builder::set_buffer_size (std::size_t size) inline
Set buffer size.
Parameters
size Buffer size in bytes
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 114 of file logger_config_builder.h.
{
        config_.buffer_size = size;
        return *this;
    }
References kcenon::logger::logger_config::buffer_size, config_, and kcenon::logger::size.
Referenced by main().
set_flush_interval()
logger_config_builder & kcenon::logger::logger_config_builder::set_flush_interval (std::chrono::milliseconds interval) inline
Set flush interval.
Parameters
interval Time between automatic flushes
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 148 of file logger_config_builder.h.
{
        config_.flush_interval = interval;
        return *this;
    }
References config_, and kcenon::logger::logger_config::flush_interval.
Referenced by main().
set_log_directory()
logger_config_builder & kcenon::logger::logger_config_builder::set_log_directory (const std::string & directory) inline
Set log directory.
Parameters
directory Directory path for log files
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 320 of file logger_config_builder.h.
{
        config_.log_directory = directory;
        return *this;
    }
References config_, and kcenon::logger::logger_config::log_directory.
Referenced by main().
set_log_file_prefix()
logger_config_builder & kcenon::logger::logger_config_builder::set_log_file_prefix (const std::string & prefix) inline
Set log file prefix.
Parameters
prefix Prefix for log file names
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 330 of file logger_config_builder.h.
{
        config_.log_file_prefix = prefix;
        return *this;
    }
References config_, and kcenon::logger::logger_config::log_file_prefix.
Referenced by main().
set_max_file_count()
logger_config_builder & kcenon::logger::logger_config_builder::set_max_file_count (std::size_t count) inline
Set maximum number of rotated files.
Parameters
count Maximum file count
Returns
Reference to builder for chaining
Definition at line 310 of file logger_config_builder.h.
{
        config_.max_file_count = count;
        return *this;
    }
References config_, and kcenon::logger::logger_config::max_file_count.
set_max_file_size()
logger_config_builder & kcenon::logger::logger_config_builder::set_max_file_size (std::size_t size) inline
Set maximum file size for rotation.
Parameters
size Maximum file size in bytes
Returns
Reference to builder for chaining
Definition at line 300 of file logger_config_builder.h.
{
        config_.max_file_size = size;
        return *this;
    }
References config_, kcenon::logger::logger_config::max_file_size, and kcenon::logger::size.
set_max_queue_size()
logger_config_builder & kcenon::logger::logger_config_builder::set_max_queue_size (std::size_t size) inline
Set maximum queue size.
Parameters
size Maximum queue size
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 276 of file logger_config_builder.h.
{
        config_.max_queue_size = size;
        return *this;
    }
References config_, kcenon::logger::logger_config::max_queue_size, and kcenon::logger::size.
Referenced by main().
set_max_writers()
logger_config_builder & kcenon::logger::logger_config_builder::set_max_writers (std::size_t max) inline
Set maximum number of writers.
Parameters
max Maximum writers
Returns
Reference to builder for chaining
Definition at line 168 of file logger_config_builder.h.
{
        config_.max_writers = max;
        return *this;
    }
References config_, and kcenon::logger::logger_config::max_writers.
set_min_level()
logger_config_builder & kcenon::logger::logger_config_builder::set_min_level (log_level level) inline
Set minimum log level.
Parameters
level Minimum log level to output
Returns
Reference to builder for chaining
Definition at line 124 of file logger_config_builder.h.
{
        config_.min_level = level;
        return *this;
    }
References config_, and kcenon::logger::logger_config::min_level.
set_network_retry_count()
logger_config_builder & kcenon::logger::logger_config_builder::set_network_retry_count (std::size_t count) inline
Set network retry count.
Parameters
count Number of retries
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 366 of file logger_config_builder.h.
{
        config_.network_retry_count = count;
        return *this;
    }
References config_, and kcenon::logger::logger_config::network_retry_count.
Referenced by main().
set_network_timeout()
logger_config_builder & kcenon::logger::logger_config_builder::set_network_timeout (std::chrono::milliseconds timeout) inline
Set network timeout.
Parameters
timeout Timeout duration
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 356 of file logger_config_builder.h.
{
        config_.network_timeout = timeout;
        return *this;
    }
References config_, and kcenon::logger::logger_config::network_timeout.
Referenced by main().
set_overflow_policy()
logger_config_builder & kcenon::logger::logger_config_builder::set_overflow_policy (logger_config::overflow_policy policy) inline
Set queue overflow policy.
Parameters
policy Overflow policy to use
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 286 of file logger_config_builder.h.
{
        config_.queue_overflow_policy = policy;
        return *this;
    }
References config_, and kcenon::logger::logger_config::queue_overflow_policy.
Referenced by main().
set_remote_logging()
logger_config_builder & kcenon::logger::logger_config_builder::set_remote_logging (const std::string & host, uint16_t port) inline
Set remote logging host.
Parameters
host Remote host address
port Remote port number
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 345 of file logger_config_builder.h.
{
        config_.remote_host = host;
        config_.remote_port = port;
        return *this;
    }
References config_, kcenon::logger::logger_config::remote_host, and kcenon::logger::logger_config::remote_port.
Referenced by main().
set_writer_thread_count()
logger_config_builder & kcenon::logger::logger_config_builder::set_writer_thread_count (std::size_t count) inline
Set writer thread count.
Parameters
count Number of writer threads
Returns
Reference to builder for chaining
Definition at line 188 of file logger_config_builder.h.
{
        config_.writer_thread_count = count;
        return *this;
    }
References config_, and kcenon::logger::logger_config::writer_thread_count.
use_debug_defaults()
logger_config_builder & kcenon::logger::logger_config_builder::use_debug_defaults () inline
Use debug configuration as base.
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 72 of file logger_config_builder.h.
{
        config_ = logger_config::debug_config();
        return *this;
    }
References config_, and kcenon::logger::logger_config::debug_config().
Referenced by main().
use_default_config()
logger_config_builder & kcenon::logger::logger_config_builder::use_default_config () inline
Use default configuration as base.
Returns
Reference to builder for chaining
Definition at line 54 of file logger_config_builder.h.
{
        config_ = logger_config::default_config();
        return *this;
    }
References config_, and kcenon::logger::logger_config::default_config().
use_high_performance_defaults()
logger_config_builder & kcenon::logger::logger_config_builder::use_high_performance_defaults () inline
Use high-performance configuration as base.
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 81 of file logger_config_builder.h.
{
        config_ = logger_config::high_performance();
        return *this;
    }
References config_, and kcenon::logger::logger_config::high_performance().
Referenced by main().
use_lock_free()
logger_config_builder & kcenon::logger::logger_config_builder::use_lock_free (bool enabled) inline
Enable/disable lock-free queue.
Parameters
enabled true to use lock-free queue
Returns
Reference to builder for chaining
Definition at line 158 of file logger_config_builder.h.
{
        config_.use_lock_free = enabled;
        return *this;
    }
References config_, and kcenon::logger::logger_config::use_lock_free.
use_low_latency_defaults()
logger_config_builder & kcenon::logger::logger_config_builder::use_low_latency_defaults () inline
Use low-latency configuration as base.
Returns
Reference to builder for chaining
Definition at line 90 of file logger_config_builder.h.
{
        config_ = logger_config::low_latency();
        return *this;
    }
References config_, and kcenon::logger::logger_config::low_latency().
use_production_defaults()
logger_config_builder & kcenon::logger::logger_config_builder::use_production_defaults () inline
Use production configuration as base.
Returns
Reference to builder for chaining
Examples
logger_config_builder_example.cpp.
Definition at line 63 of file logger_config_builder.h.
{
        config_ = logger_config::production();
        return *this;
    }
References config_, and kcenon::logger::logger_config::production().
Referenced by main().
Member Data Documentation
config_
logger_config kcenon::logger::logger_config_builder::config_ private
Definition at line 410 of file logger_config_builder.h.
Referenced by build(), build_unchecked(), enable_batch_writing(), enable_color_output(), enable_compression(), enable_crash_handler(), enable_metrics(), enable_source_location(), enable_structured_logging(), enable_timestamp(), reset(), set_async(), set_batch_size(), set_buffer_size(), set_flush_interval(), set_log_directory(), set_log_file_prefix(), set_max_file_count(), set_max_file_size(), set_max_queue_size(), set_max_writers(), set_min_level(), set_network_retry_count(), set_network_timeout(), set_overflow_policy(), set_remote_logging(), set_writer_thread_count(), use_debug_defaults(), use_default_config(), use_high_performance_defaults(), use_lock_free(), use_low_latency_defaults(), and use_production_defaults().
The documentation for this class was generated from the following file:
include/kcenon/logger/core/logger_config_builder.h