Logger System: kcenon::logger::otlp::otel_context_storage Class Reference
kcenon::logger::otlp::otel_context_storage Class Reference
Thread-local storage for OpenTelemetry context.
#include <otel_context.h>
Static Public Member Functions
static void set (const otel_context &ctx)
Set the OpenTelemetry context for the current thread.
static std::optional< otel_context > get ()
Get the OpenTelemetry context for the current thread.
static void clear ()
Clear the OpenTelemetry context for the current thread.
static bool has_context ()
Check if a context is set for the current thread.
Static Private Member Functions
static otel_context & get_storage ()
static bool & get_has_context ()
Detailed Description
Thread-local storage for OpenTelemetry context.
Provides thread-safe storage and retrieval of OpenTelemetry context using thread-local storage. This allows automatic context propagation within a thread.
Definition at line 215 of file otel_context.h.
Member Function Documentation
clear()
static void kcenon::logger::otlp::otel_context_storage::clear () inline static
Clear the OpenTelemetry context for the current thread.
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
Definition at line 242 of file otel_context.h.
{
        get_storage() = otel_context{};
        get_has_context() = false;
    }
References get_has_context(), and get_storage().
Referenced by kcenon::logger::otlp::otel_context_scope::~otel_context_scope().
get()
static std::optional< otel_context > kcenon::logger::otlp::otel_context_storage::get () inline static nodiscard
Get the OpenTelemetry context for the current thread.
Returns
Optional context, empty if not set
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
Definition at line 232 of file otel_context.h.
{
        if (get_has_context()) {
            return get_storage();
        }
        return std::nullopt;
    }
References get_has_context(), and get_storage().
Referenced by kcenon::logger::otlp_writer::write().
get_has_context()
static bool & kcenon::logger::otlp::otel_context_storage::get_has_context () inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
Definition at line 262 of file otel_context.h.
{
        thread_local bool has_ctx = false;
        return has_ctx;
    }
Referenced by clear(), get(), has_context(), and set().
get_storage()
static otel_context & kcenon::logger::otlp::otel_context_storage::get_storage () inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
Definition at line 257 of file otel_context.h.
{
        thread_local otel_context storage;
        return storage;
    }
Referenced by clear(), get(), and set().
has_context()
static bool kcenon::logger::otlp::otel_context_storage::has_context () inline static nodiscard
Check if a context is set for the current thread.
Returns
true if context is set
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
Definition at line 252 of file otel_context.h.
{
        return get_has_context();
    }
References get_has_context().
set()
static void kcenon::logger::otlp::otel_context_storage::set (const otel_context & ctx) inline static
Set the OpenTelemetry context for the current thread.
Parameters
ctx Context to set
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
Definition at line 222 of file otel_context.h.
{
        get_storage() = ctx;
        get_has_context() = true;
    }
References get_has_context(), and get_storage().
Referenced by kcenon::logger::otlp::otel_context_scope::otel_context_scope(), and kcenon::logger::otlp::otel_context_scope::~otel_context_scope().
The documentation for this class was generated from the following file:
include/kcenon/logger/otlp/otel_context.h