Logger System: logger_module::batch_writer Class Reference
logger_module::batch_writer Class Reference
Batch writer that accumulates log entries and writes them in batches.
#include <batch_writer.h>
Classes
struct batch_stats
Get batch statistics.
struct config
Configuration for batch writer.
Public Member Functions
batch_writer (std::unique_ptr< base_writer > underlying_writer, const config &cfg=config{})
Construct a batch writer.
~batch_writer () override
Destructor - ensures all pending entries are flushed.
result_void write (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write a log entry to the batch.
result_void flush () override
Flush the batch to the underlying writer.
std::string get_name () const override
Get writer name.
bool is_healthy () const override
Check if writer is healthy.
size_t get_current_batch_size () const
Get current batch size.
const batch_stats & get_stats () const
Get batch statistics.
void reset_stats ()
Reset batch statistics.
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
Protected Member Functions
std::string format_log_entry (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (thread_module::log_level level) const
Convert log level to string representation.
std::string level_to_color (thread_module::log_level level) const
Get ANSI color code for the specified log level.
Detailed Description
Batch writer that accumulates log entries and writes them in batches.
This writer wraps another writer and accumulates log entries up to a configurable batch size or timeout, then writes them all at once. This reduces the number of I/O operations and improves performance.
Features:
Configurable batch size
Automatic flush on timeout
Thread-safe batch accumulation
Preserves original timestamps
Definition at line 58 of file batch_writer.h.
Constructor & Destructor Documentation
batch_writer()
logger_module::batch_writer::batch_writer (std::unique_ptr< base_writer > underlying_writer, const config & cfg = config{}) explicit
Construct a batch writer.
Parameters
underlying_writer The actual writer to batch writes for
cfg Batch configuration
Definition at line 38 of file batch_writer.cpp.
References logger_module::batch_writer::config::max_batch_size.
~batch_writer()
logger_module::batch_writer::~batch_writer () override
Destructor - ensures all pending entries are flushed.
Definition at line 52 of file batch_writer.cpp.
References flush().
Member Function Documentation
flush()
result_void logger_module::batch_writer::flush () override virtual
Flush the batch to the underlying writer.
Returns
result_void indicating success or error
Implements logger_module::base_writer.
Definition at line 96 of file batch_writer.cpp.
References logger_module::batch_writer::batch_stats::manual_flushes.
Referenced by write(), and ~batch_writer().
format_log_entry()
std::string logger_module::base_writer::format_log_entry (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) protected inherited
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 131 of file console_writer.cpp.
References logger_module::base_writer::level_to_string().
Referenced by logger_module::console_writer::write(), logger_module::encrypted_writer::write(), and logger_module::file_writer::write().
get_current_batch_size()
size_t logger_module::batch_writer::get_current_batch_size () const
Get current batch size.
Returns
Number of entries currently in the batch
Definition at line 159 of file batch_writer.cpp.
get_name()
std::string logger_module::batch_writer::get_name () const override virtual
Get writer name.
Returns
Name of the batch writer
Implements logger_module::base_writer.
Definition at line 151 of file batch_writer.cpp.
get_stats()
const batch_stats & logger_module::batch_writer::get_stats () const inline
Get batch statistics.
Returns
Current batch statistics
Definition at line 149 of file batch_writer.h.
is_healthy()
bool logger_module::batch_writer::is_healthy () const override virtual
Check if writer is healthy.
Returns
true if both batch writer and underlying writer are healthy
Reimplemented from logger_module::base_writer.
Definition at line 155 of file batch_writer.cpp.
level_to_color()
std::string logger_module::base_writer::level_to_color (thread_module::log_level level) const protected inherited
Get ANSI color code for the specified log level.
Parameters
level Log level to get color for
Returns
ANSI escape sequence for color, or empty string if color is disabled
Returns appropriate ANSI color codes for terminal output:
trace -> Gray/Dim
debug -> Cyan
info -> Green
warning -> Yellow
error -> Red
Note
Returns empty string if use_color() is false.
Warning
Only use for terminals that support ANSI escape codes.
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 170 of file console_writer.cpp.
References logger_module::base_writer::use_color().
Referenced by logger_module::console_writer::write().
level_to_string()
std::string logger_module::base_writer::level_to_string (thread_module::log_level level) const protected inherited
Convert log level to string representation.
Parameters
level Log level to convert
Returns
String representation of the level
Maps log levels to human-readable strings:
trace -> "TRACE"
debug -> "DEBUG"
info -> "INFO"
warning -> "WARNING"
error -> "ERROR"
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 158 of file console_writer.cpp.
Referenced by logger_module::base_writer::format_log_entry().
reset_stats()
void logger_module::batch_writer::reset_stats ()
Reset batch statistics.
Definition at line 164 of file batch_writer.cpp.
References logger_module::batch_writer::batch_stats::dropped_entries, logger_module::batch_writer::batch_stats::flush_on_size, logger_module::batch_writer::batch_stats::flush_on_timeout, logger_module::batch_writer::batch_stats::manual_flushes, logger_module::batch_writer::batch_stats::total_batches, and logger_module::batch_writer::batch_stats::total_entries.
set_use_color()
virtual void logger_module::base_writer::set_use_color (bool use_color) inline virtual inherited
Set whether to use color output (if supported)
Parameters
use_color true to enable color output, false to disable
Enables or disables ANSI color codes in formatted output. Only affects writers that output to terminals supporting color.
Note
Has no effect on writers that don't support color (e.g., file writers).
Since
1.0.0
Reimplemented in logger_module::async_writer.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 209 of file base_writer.h.
References logger_module::base_writer::use_color().
Referenced by logger_module::console_writer::console_writer().
use_color()
bool logger_module::base_writer::use_color () const inline inherited
Get current color output setting.
Returns
true if color output is enabled, false otherwise
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 219 of file base_writer.h.
Referenced by logger_module::base_writer::level_to_color(), logger_module::base_writer::set_use_color(), logger_module::async_writer::set_use_color(), and logger_module::console_writer::write().
write() [1/2]
virtual result_void logger_module::base_writer::write (const log_entry & entry) inline override virtual inherited
Write a log entry using the new interface.
Parameters
entry The log entry to write
Returns
result_void Success or error code
This method provides compatibility with the modern log_entry structure. The default implementation converts the entry to the legacy API format for backward compatibility. Derived classes can override this for optimized handling.
Note
This method extracts source location information if present in the entry.
Since
1.0.0
Implements logger_module::log_writer_interface.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 140 of file base_writer.h.
References logger_module::log_entry::level, logger_module::log_entry::location, logger_module::log_entry::message, logger_module::log_entry::timestamp, and logger_module::base_writer::write().
Referenced by logger_module::base_writer::write().
write() [2/2]
result_void logger_module::batch_writer::write (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write a log entry to the batch.
Parameters
level Log level
message Log message
file Source file
line Source line
function Function name
timestamp Time of log entry
Returns
result_void indicating success or error
Implements logger_module::base_writer.
Definition at line 61 of file batch_writer.cpp.
References flush(), logger_module::batch_writer::batch_stats::flush_on_size, logger_module::make_logger_error(), logger_module::queue_stopped, and logger_module::batch_writer::batch_stats::total_entries.
The documentation for this class was generated from the following files:
/home/runner/work/logger_system/logger_system/sources/logger/writers/batch_writer.h
/home/runner/work/logger_system/logger_system/sources/logger/writers/batch_writer.cpp