Logger System: kcenon::logger::adapters::common_system_logger_adapter Class Reference
kcenon::logger::adapters::common_system_logger_adapter Class Reference
Adapter to expose kcenon::logger as common::interfaces::ILogger.
#include <common_system_adapter.h>
Public Member Functions
common_system_logger_adapter (std::shared_ptr< logger > lg)
Construct adapter with kcenon::logger logger.
~common_system_logger_adapter () override=default
::common::VoidResult log (::common::interfaces::log_level level, const std::string &message) override
Log a message with specified level.
::common::VoidResult log (::common::interfaces::log_level level, std::string_view message, const ::kcenon::common::source_location &loc=::kcenon::common::source_location::current()) override
Log a message with source location information (C++20 style)
::common::VoidResult log (const ::common::interfaces::log_entry &entry) override
Log a structured entry.
bool is_enabled (::common::interfaces::log_level level) const override
Check if logging is enabled for the specified level.
::common::VoidResult set_level (::common::interfaces::log_level level) override
Set the minimum log level.
::common::interfaces::log_level get_level () const override
Get the current minimum log level.
::common::VoidResult flush () override
Flush any buffered log messages.
std::shared_ptr< logger > get_impl () const
Get access to the underlying logger.
Static Private Member Functions
static log_level convert_level_from_common (::common::interfaces::log_level level)
Convert common log level to kcenon::logger log level.
::common::interfaces::log_level convert_level_to_common (log_level level)
Convert kcenon::logger log level to common log level.
Private Attributes
std::shared_ptr< logger > impl_
Detailed Description
Adapter to expose kcenon::logger as common::interfaces::ILogger.
This adapter allows kcenon::logger's logger to be used through the standard common_system logger interface.
Definition at line 35 of file common_system_adapter.h.
Constructor & Destructor Documentation
common_system_logger_adapter()
kcenon::logger::adapters::common_system_logger_adapter::common_system_logger_adapter (std::shared_ptr< logger > lg) inline explicit
Construct adapter with kcenon::logger logger.
Parameters
lg Shared pointer to kcenon::logger logger
Definition at line 41 of file common_system_adapter.h.
        : impl_(std::move(lg)) {}
~common_system_logger_adapter()
kcenon::logger::adapters::common_system_logger_adapter::~common_system_logger_adapter () override default
Member Function Documentation
convert_level_from_common()
static log_level kcenon::logger::adapters::common_system_logger_adapter::convert_level_from_common (::common::interfaces::log_level level) inline static private
Convert common log level to kcenon::logger log level.
Definition at line 182 of file common_system_adapter.h.
{
        switch(level) {
            case ::common::interfaces::log_level::trace:
                return log_level::trace;
            case ::common::interfaces::log_level::debug:
                return log_level::debug;
            case ::common::interfaces::log_level::info:
                return log_level::info;
            case ::common::interfaces::log_level::warning:
                return log_level::warning;
            case ::common::interfaces::log_level::error:
                return log_level::error;
            case ::common::interfaces::log_level::critical:
                return log_level::critical;
            case ::common::interfaces::log_level::off:
            default:
                return log_level::off;
        }
    }
Referenced by is_enabled(), log(), log(), and set_level().
convert_level_to_common()
::common::interfaces::log_level kcenon::logger::adapters::common_system_logger_adapter::convert_level_to_common (log_level level) inline static private
Convert kcenon::logger log level to common log level.
Definition at line 205 of file common_system_adapter.h.
{
        switch(level) {
            case log_level::trace:
                return ::common::interfaces::log_level::trace;
            case log_level::debug:
                return ::common::interfaces::log_level::debug;
            case log_level::info:
                return ::common::interfaces::log_level::info;
            case log_level::warning:
                return ::common::interfaces::log_level::warning;
            case log_level::error:
                return ::common::interfaces::log_level::error;
            case log_level::critical:
                return ::common::interfaces::log_level::critical;
            case log_level::off:
            default:
                return ::common::interfaces::log_level::off;
        }
    }
Referenced by get_level().
flush()
::common::VoidResult kcenon::logger::adapters::common_system_logger_adapter::flush () inline override
Flush any buffered log messages.
Definition at line 155 of file common_system_adapter.h.
{
        if (!impl_) {
            return ::common::VoidResult(
                ::common::error_info(1, "Logger not initialized", "kcenon::logger"));
        }
        try {
            impl_->flush();
            return ::common::VoidResult(std::monostate{});
        } catch (const std::exception& e) {
            return ::common::VoidResult(
                ::common::error_info(2, e.what(), "kcenon::logger"));
        }
    }
References impl_.
get_impl()
std::shared_ptr< logger > kcenon::logger::adapters::common_system_logger_adapter::get_impl () const inline
Get access to the underlying logger.
Returns
Shared pointer to the logger
Definition at line 174 of file common_system_adapter.h.
{ return impl_; }
References impl_.
get_level()
::common::interfaces::log_level kcenon::logger::adapters::common_system_logger_adapter::get_level () const inline override
Get the current minimum log level.
Definition at line 144 of file common_system_adapter.h.
{
        if (!impl_) {
            return ::common::interfaces::log_level::info;
        }
        auto logger_level = impl_->get_level();
        return convert_level_to_common(logger_level);
    }
References convert_level_to_common(), and impl_.
is_enabled()
bool kcenon::logger::adapters::common_system_logger_adapter::is_enabled (::common::interfaces::log_level level) const inline override
Check if logging is enabled for the specified level.
Definition at line 113 of file common_system_adapter.h.
{
        if (!impl_) {
            return false;
        }
        auto logger_level = convert_level_from_common(level);
        return impl_->is_enabled(logger_level);
    }
References convert_level_from_common(), and impl_.
log() [1/3]
::common::VoidResult kcenon::logger::adapters::common_system_logger_adapter::log (::common::interfaces::log_level level, const std::string & message) inline override
Log a message with specified level.
Definition at line 49 of file common_system_adapter.h.
{
        if (!impl_) {
            return ::common::VoidResult(
                ::common::error_info(1, "Logger not initialized", "kcenon::logger"));
        }
        try {
            auto logger_level = convert_level_from_common(level);
            impl_->log(logger_level, message);
            return ::common::VoidResult(std::monostate{});
        } catch (const std::exception& e) {
            return ::common::VoidResult(
                ::common::error_info(2, e.what(), "kcenon::logger"));
        }
    }
References convert_level_from_common(), and impl_.
log() [2/3]
::common::VoidResult kcenon::logger::adapters::common_system_logger_adapter::log (::common::interfaces::log_level level, std::string_view message, const ::kcenon::common::source_location & loc = ::kcenon::common::source_location::current()) inline override
Log a message with source location information (C++20 style)
Definition at line 70 of file common_system_adapter.h.
{
        if (!impl_) {
            return ::common::VoidResult(
                ::common::error_info(1, "Logger not initialized", "kcenon::logger"));
        }
        try {
            auto logger_level = convert_level_from_common(level);
            impl_->log(logger_level, message, loc);
            return ::common::VoidResult(std::monostate{});
        } catch (const std::exception& e) {
            return ::common::VoidResult(
                ::common::error_info(2, e.what(), "kcenon::logger"));
        }
    }
References convert_level_from_common(), and impl_.
log() [3/3]
::common::VoidResult kcenon::logger::adapters::common_system_logger_adapter::log (const ::common::interfaces::log_entry & entry) inline override
Log a structured entry.
Definition at line 92 of file common_system_adapter.h.
{
        if (!impl_) {
            return ::common::VoidResult(
                ::common::error_info(1, "Logger not initialized", "kcenon::logger"));
        }
        try {
            // Delegate directly to logger's log_entry overload, which extracts
            // file/line/function from the entry without constructing a
            // std::source_location (not possible in C++20).
            return impl_->log(entry);
        } catch (const std::exception& e) {
            return ::common::VoidResult(
                ::common::error_info(2, e.what(), "kcenon::logger"));
        }
    }
References impl_.
set_level()
::common::VoidResult kcenon::logger::adapters::common_system_logger_adapter::set_level (::common::interfaces::log_level level) inline override
Set the minimum log level.
Definition at line 124 of file common_system_adapter.h.
{
        if (!impl_) {
            return ::common::VoidResult(
                ::common::error_info(1, "Logger not initialized", "kcenon::logger"));
        }
        try {
            auto logger_level = convert_level_from_common(level);
            impl_->set_level(logger_level);
            return ::common::VoidResult(std::monostate{});
        } catch (const std::exception& e) {
            return ::common::VoidResult(
                ::common::error_info(2, e.what(), "kcenon::logger"));
        }
    }
References convert_level_from_common(), and impl_.
Member Data Documentation
impl_
std::shared_ptr<logger> kcenon::logger::adapters::common_system_logger_adapter::impl_ private
Definition at line 177 of file common_system_adapter.h.
Referenced by flush(), get_impl(), get_level(), is_enabled(), log(), log(), log(), and set_level().
The documentation for this class was generated from the following file:
include/kcenon/logger/adapters/common_system_adapter.h