Logger System: kcenon::logger::result< T > Class Template Reference
kcenon::logger::result< T > Class Template Reference
#include <error_codes.h>
Public Member Functions
result (T &&value)
result (const T &value)
result (logger_error_code code, const std::string &msg="")
result (const common::error_info &error)
result (common::error_info &&error)
bool has_value () const
operator bool () const
T & value ()
const T & value () const
logger_error_code error_code () const
const std::string & error_message () const
const common::Result< T > & raw () const
Static Public Member Functions
static result ok_value (const T &value)
Private Attributes
common::Result< T > value_
Detailed Description
template<typename T>
class kcenon::logger::result< T >
Examples
critical_logging_example.cpp, custom_writer_example.cpp, di_pattern_example.cpp, and monitoring_integration_example.cpp.
Definition at line 436 of file error_codes.h.
Constructor & Destructor Documentation
result() [1/5]
template<typename T > kcenon::logger::result< T >::result (T && value) inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 439 of file error_codes.h.
        : value_(common::ok<T>(std::move(value))) {}
result() [2/5]
template<typename T > kcenon::logger::result< T >::result (const T & value) inline
Definition at line 443 of file error_codes.h.
        : value_(common::ok<T>(value)) {}
result() [3/5]
template<typename T > kcenon::logger::result< T >::result (logger_error_code code, const std::string & msg = "") inline
Definition at line 446 of file error_codes.h.
        : value_(common::error_info{
              static_cast<int>(code),
              msg.empty() ? logger_error_to_string(code) : msg,
              "logger_system"}) {}
result() [4/5]
template<typename T > kcenon::logger::result< T >::result (const common::error_info & error) inline explicit
Definition at line 452 of file error_codes.h.
        : value_(error) {}
result() [5/5]
template<typename T > kcenon::logger::result< T >::result (common::error_info && error) inline explicit
Definition at line 455 of file error_codes.h.
        : value_(std::move(error)) {}
Member Function Documentation
error_code()
template<typename T > logger_error_code kcenon::logger::result< T >::error_code () const inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 472 of file error_codes.h.
{
        return static_cast<logger_error_code>(value_.error().code);
    }
References kcenon::logger::result< T >::value_.
error_message()
template<typename T > const std::string & kcenon::logger::result< T >::error_message () const inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h, and critical_logging_example.cpp.
Definition at line 476 of file error_codes.h.
{
        return value_.error().message;
    }
References kcenon::logger::result< T >::value_.
Referenced by example_production_setup().
has_value()
template<typename T > bool kcenon::logger::result< T >::has_value () const inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h, and custom_writer_example.cpp.
Definition at line 466 of file error_codes.h.
{ return value_.is_ok(); }
References kcenon::logger::result< T >::value_.
Referenced by main(), and kcenon::logger::result< T >::operator bool().
ok_value()
template<typename T > static result kcenon::logger::result< T >::ok_value (const T & value) inline static
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 459 of file error_codes.h.
{
        result res(logger_error_code::success);
        // Directly assign common::Result value
        res.value_ = common::ok<T>(value);
        return res;
    }
References kcenon::common::ok(), kcenon::logger::success, kcenon::logger::result< T >::value(), and kcenon::logger::result< T >::value_.
Referenced by kcenon::logger::logger::get_current_metrics().
operator bool()
template<typename T > kcenon::logger::result< T >::operator bool () const inline explicit
Definition at line 467 of file error_codes.h.
{ return has_value(); }
References kcenon::logger::result< T >::has_value().
raw()
template<typename T > const common::Result< T > & kcenon::logger::result< T >::raw () const inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 480 of file error_codes.h.
{ return value_; }
References kcenon::logger::result< T >::value_.
value() [1/2]
template<typename T > T & kcenon::logger::result< T >::value () inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h, critical_logging_example.cpp, and custom_writer_example.cpp.
Definition at line 469 of file error_codes.h.
{ return value_.value(); }
References kcenon::logger::result< T >::value_.
Referenced by example_production_setup(), main(), and kcenon::logger::result< T >::ok_value().
value() [2/2]
template<typename T > const T & kcenon::logger::result< T >::value () const inline
Definition at line 470 of file error_codes.h.
{ return value_.value(); }
References kcenon::logger::result< T >::value_.
Member Data Documentation
value_
template<typename T > common::Result<T> kcenon::logger::result< T >::value_ private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 483 of file error_codes.h.
Referenced by kcenon::logger::result< T >::error_code(), kcenon::logger::result< T >::error_message(), kcenon::logger::result< T >::has_value(), kcenon::logger::result< T >::ok_value(), kcenon::logger::result< T >::raw(), kcenon::logger::result< T >::value(), and kcenon::logger::result< T >::value().
The documentation for this class was generated from the following file:
include/kcenon/logger/core/error_codes.h