Logger System: kcenon::logger::scoped_context Class Reference
kcenon::logger::scoped_context Class Reference
Convenience class for setting a single context field with RAII.
#include <log_context_scope.h>
Public Member Functions
scoped_context (const std::string &key, const std::string &value)
Construct with string value.
scoped_context (const std::string &key, int64_t value)
Construct with integer value.
scoped_context (const std::string &key, int value)
Construct with int value (converts to int64_t)
scoped_context (const std::string &key, double value)
Construct with double value.
scoped_context (const std::string &key, bool value)
Construct with boolean value.
~scoped_context ()
Destructor - restores or removes the context field.
scoped_context (const scoped_context &)=delete
scoped_context & operator= (const scoped_context &)=delete
scoped_context (scoped_context &&)=delete
scoped_context & operator= (scoped_context &&)=delete
Private Attributes
std::string key_
log_value previous_value_
bool had_previous_
Detailed Description
Convenience class for setting a single context field with RAII.
Provides a simpler interface for setting a single context field that will be automatically removed when the scope exits.
Examples
structured_logging_example.cpp.
Definition at line 347 of file log_context_scope.h.
Constructor & Destructor Documentation
scoped_context() [1/7]
kcenon::logger::scoped_context::scoped_context (const std::string & key, const std::string & value) inline
Construct with string value.
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 352 of file log_context_scope.h.
        : key_(key), had_previous_(false) {
        auto prev = log_context_storage::get_field(key);
        if (prev) {
            had_previous_ = true;
            previous_value_ = *prev;
        }
        log_context_storage::set(key, value);
    }
References kcenon::logger::log_context_storage::get_field(), had_previous_, previous_value_, and kcenon::logger::log_context_storage::set().
scoped_context() [2/7]
kcenon::logger::scoped_context::scoped_context (const std::string & key, int64_t value) inline
Construct with integer value.
Definition at line 365 of file log_context_scope.h.
        : key_(key), had_previous_(false) {
        auto prev = log_context_storage::get_field(key);
        if (prev) {
            had_previous_ = true;
            previous_value_ = *prev;
        }
        log_context_storage::set(key, value);
    }
References kcenon::logger::log_context_storage::get_field(), had_previous_, previous_value_, and kcenon::logger::log_context_storage::set().
scoped_context() [3/7]
kcenon::logger::scoped_context::scoped_context (const std::string & key, int value) inline
Construct with int value (converts to int64_t)
Definition at line 378 of file log_context_scope.h.
        : scoped_context(key, static_cast<int64_t>(value)) {}
scoped_context() [4/7]
kcenon::logger::scoped_context::scoped_context (const std::string & key, double value) inline
Construct with double value.
Definition at line 384 of file log_context_scope.h.
        : key_(key), had_previous_(false) {
        auto prev = log_context_storage::get_field(key);
        if (prev) {
            had_previous_ = true;
            previous_value_ = *prev;
        }
        log_context_storage::set(key, value);
    }
References kcenon::logger::log_context_storage::get_field(), had_previous_, previous_value_, and kcenon::logger::log_context_storage::set().
scoped_context() [5/7]
kcenon::logger::scoped_context::scoped_context (const std::string & key, bool value) inline
Construct with boolean value.
Definition at line 397 of file log_context_scope.h.
        : key_(key), had_previous_(false) {
        auto prev = log_context_storage::get_field(key);
        if (prev) {
            had_previous_ = true;
            previous_value_ = *prev;
        }
        log_context_storage::set(key, value);
    }
References kcenon::logger::log_context_storage::get_field(), had_previous_, previous_value_, and kcenon::logger::log_context_storage::set().
~scoped_context()
kcenon::logger::scoped_context::~scoped_context () inline
Destructor - restores or removes the context field.
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 410 of file log_context_scope.h.
                      {
        if (had_previous_) {
            log_context_storage::set(key_, previous_value_);
        } else {
            log_context_storage::remove(key_);
        }
    }
References had_previous_, key_, previous_value_, kcenon::logger::log_context_storage::remove(), and kcenon::logger::log_context_storage::set().
scoped_context() [6/7]
kcenon::logger::scoped_context::scoped_context (const scoped_context &) delete
scoped_context() [7/7]
kcenon::logger::scoped_context::scoped_context (scoped_context &&) delete
Member Function Documentation
operator=() [1/2]
scoped_context & kcenon::logger::scoped_context::operator= (const scoped_context &) delete
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
operator=() [2/2]
scoped_context & kcenon::logger::scoped_context::operator= (scoped_context &&) delete
Member Data Documentation
had_previous_
bool kcenon::logger::scoped_context::had_previous_ private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 427 of file log_context_scope.h.
Referenced by scoped_context(), scoped_context(), scoped_context(), scoped_context(), and ~scoped_context().
key_
std::string kcenon::logger::scoped_context::key_ private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 425 of file log_context_scope.h.
Referenced by ~scoped_context().
previous_value_
log_value kcenon::logger::scoped_context::previous_value_ private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 426 of file log_context_scope.h.
Referenced by scoped_context(), scoped_context(), scoped_context(), scoped_context(), and ~scoped_context().
The documentation for this class was generated from the following file:
include/kcenon/logger/core/log_context_scope.h