Logger System: kcenon::logger::timestamp_formatter Class Reference
kcenon::logger::timestamp_formatter Class Reference
Default formatter with human-readable timestamp format.
#include <timestamp_formatter.h>
Public Member Functions
timestamp_formatter (const format_options &opts=format_options{})
Constructor with optional format options.
std::string format (const log_entry &entry) const override
Format a log entry to human-readable string.
std::string get_name () const override
Get formatter name.
Public Member Functions inherited from kcenon::logger::log_formatter_interface
virtual ~log_formatter_interface ()=default
virtual void set_options (const format_options &opts)
Set formatting options.
virtual format_options get_options () const
Get current formatting options.
Additional Inherited Members
Protected Attributes inherited from kcenon::logger::log_formatter_interface
format_options options_
Detailed Description
Default formatter with human-readable timestamp format.
Provides the traditional log format with timestamps, levels, and optional source location. This is the default formatter used by the logger system and is optimized for human readability.
Features:
Millisecond-precision timestamps
Color-coded log levels (if enabled)
Thread ID tracking
Source location information (file, line, function)
Automatic filename extraction from paths
Thread-safety: This formatter is stateless and thread-safe.
Since
1.2.0
Definition at line 57 of file timestamp_formatter.h.
Constructor & Destructor Documentation
timestamp_formatter()
kcenon::logger::timestamp_formatter::timestamp_formatter (const format_options & opts = format_options{}) inline explicit
Constructor with optional format options.
Parameters
opts Initial format options
Since
1.2.0
Definition at line 65 of file timestamp_formatter.h.
                                                                            {}) {
        options_ = opts;
    }
Member Function Documentation
format()
std::string kcenon::logger::timestamp_formatter::format (const log_entry & entry) const inline override virtual
Format a log entry to human-readable string.
Parameters
entry The log entry to format
Returns
Formatted string with timestamp, level, message, and location
Produces output in the format: [YYYY-MM-DD HH:MM:SS.mmm] [LEVEL] [thread:TID] message [file:line in function()]
Note
Thread-safe. Can be called concurrently.
Since
1.2.0
Implements kcenon::logger::log_formatter_interface.
Definition at line 81 of file timestamp_formatter.h.
{
        std::ostringstream oss;
        // Timestamp
        if (options_.include_timestamp) {
            oss << "[" << utils::time_utils::format_timestamp(entry.timestamp) << "] ";
        }
        // Level (with color)
        if (options_.include_level) {
            if (options_.use_colors) {
                oss << utils::string_utils::level_to_color(entry.level, true);
            }
            oss << "[" << utils::string_utils::level_to_string(entry.level) << "] ";
            if (options_.use_colors) {
                oss << utils::string_utils::color_reset();
            }
        }
        // Thread ID
        if (options_.include_thread_id && entry.thread_id) {
            oss << "[thread:" << entry.thread_id->to_string() << "] ";
        }
        // Message
        oss << entry.message.to_string();
        // Source location
        if (options_.include_source_location && entry.location) {
            oss << " [";
            // Extract filename from path
            std::string file_path = entry.location->file.to_string();
            if (!file_path.empty()) {
                std::string filename = utils::string_utils::extract_filename(file_path);
                oss << filename << ":" << entry.location->line;
            }
            // Function name
            std::string func = entry.location->function.to_string();
            if (!func.empty()) {
                oss << " in " << func << "()";
            }
            oss << "]";
        }
        return oss.str();
    }
References kcenon::logger::utils::string_utils::color_reset(), kcenon::logger::utils::string_utils::extract_filename(), kcenon::logger::utils::time_utils::format_timestamp(), kcenon::logger::format_options::include_level, kcenon::logger::format_options::include_source_location, kcenon::logger::format_options::include_thread_id, kcenon::logger::format_options::include_timestamp, kcenon::logger::log_entry::level, kcenon::logger::utils::string_utils::level_to_color(), kcenon::logger::utils::string_utils::level_to_string(), kcenon::logger::log_entry::location, kcenon::logger::log_entry::message, kcenon::logger::log_formatter_interface::options_, kcenon::logger::log_entry::thread_id, kcenon::logger::log_entry::timestamp, kcenon::logger::small_string< SSO_SIZE >::to_string(), and kcenon::logger::format_options::use_colors.
get_name()
std::string kcenon::logger::timestamp_formatter::get_name () const inline override virtual
Get formatter name.
Returns
"timestamp_formatter"
Since
1.2.0
Implements kcenon::logger::log_formatter_interface.
Definition at line 137 of file timestamp_formatter.h.
{
        return "timestamp_formatter";
    }
The documentation for this class was generated from the following file:
include/kcenon/logger/formatters/timestamp_formatter.h