Logger System: kcenon::logger::adapters::logger_from_common_adapter Class Reference
kcenon::logger::adapters::logger_from_common_adapter Class Reference
Adapter to use common::interfaces::ILogger in logger_system.
#include <common_logger_adapter.h>
Public Member Functions
logger_from_common_adapter (std::shared_ptr<::common::interfaces::ILogger > common_logger)
Construct adapter with common logger.
void log (log_level level, const std::string &message)
Log a message.
void log_with_location (log_level level, const std::string &message, const std::string &file, int line, const std::string &function)
Log with source location.
void set_level (log_level level)
Set log level.
log_level get_level () const
Get log level.
void flush ()
Flush logs.
Private Attributes
std::shared_ptr<::common::interfaces::ILogger > common_logger_
Detailed Description
Adapter to use common::interfaces::ILogger in logger_system.
Definition at line 218 of file common_logger_adapter.h.
Constructor & Destructor Documentation
logger_from_common_adapter()
kcenon::logger::adapters::logger_from_common_adapter::logger_from_common_adapter (std::shared_ptr<::common::interfaces::ILogger > common_logger) inline explicit
Construct adapter with common logger.
Definition at line 223 of file common_logger_adapter.h.
        : common_logger_(common_logger) {}
Member Function Documentation
flush()
void kcenon::logger::adapters::logger_from_common_adapter::flush () inline
Flush logs.
Definition at line 279 of file common_logger_adapter.h.
                 {
        if (common_logger_) {
            common_logger_->flush();
        }
    }
References common_logger_.
get_level()
log_level kcenon::logger::adapters::logger_from_common_adapter::get_level () const inline
Get log level.
Definition at line 268 of file common_logger_adapter.h.
{
        if (!common_logger_) {
            return log_level::off;
        }
        return from_common_level(common_logger_->get_level());
    }
References common_logger_, and kcenon::logger::adapters::from_common_level().
log()
void kcenon::logger::adapters::logger_from_common_adapter::log (log_level level, const std::string & message) inline
Log a message.
Definition at line 230 of file common_logger_adapter.h.
{
        if (!common_logger_) {
            return;
        }
        auto result = common_logger_->log(to_common_level(level), message);
        // Silently ignore errors for now
    }
References common_logger_, and kcenon::logger::adapters::to_common_level().
log_with_location()
void kcenon::logger::adapters::logger_from_common_adapter::log_with_location (log_level level, const std::string & message, const std::string & file, int line, const std::string & function) inline
Log with source location.
Definition at line 242 of file common_logger_adapter.h.
{
        if (!common_logger_) {
            return;
        }
        auto result = common_logger_->log_with_location(
            to_common_level(level), message, file, line, function);
        // Silently ignore errors for now
    }
References common_logger_, and kcenon::logger::adapters::to_common_level().
set_level()
void kcenon::logger::adapters::logger_from_common_adapter::set_level (log_level level) inline
Set log level.
Definition at line 259 of file common_logger_adapter.h.
{
        if (common_logger_) {
            common_logger_->set_level(to_common_level(level));
        }
    }
References common_logger_, and kcenon::logger::adapters::to_common_level().
Member Data Documentation
common_logger_
std::shared_ptr<::common::interfaces::ILogger> kcenon::logger::adapters::logger_from_common_adapter::common_logger_ private
Definition at line 286 of file common_logger_adapter.h.
Referenced by flush(), get_level(), log(), log_with_location(), and set_level().
The documentation for this class was generated from the following file:
include/kcenon/logger/adapters/common_logger_adapter.h