Logger System: logger_module::health_check_utils Class Reference
logger_module::health_check_utils Class Reference
Health check utilities.
#include <health_check_system.h>
Static Public Member Functions
static std::string health_status_to_string (health_status status)
Convert health status to string.
static health_status aggregate_health_status (const std::vector< health_status > &statuses)
Determine overall health from multiple statuses.
static std::string format_as_json (const health_check_result &result)
Format health check result as JSON.
static std::string format_writer_health (const writer_health_info &info)
Format writer health info as string.
Detailed Description
Health check utilities.
Definition at line 316 of file health_check_system.h.
Member Function Documentation
aggregate_health_status()
health_status logger_module::health_check_utils::aggregate_health_status (const std::vector< health_status > & statuses) static
Determine overall health from multiple statuses.
Parameters
statuses Vector of health statuses
Returns
Worst health status
Definition at line 597 of file health_check_system.cpp.
References logger_module::degraded, logger_module::healthy, logger_module::unhealthy, and logger_module::unknown.
Referenced by logger_module::health_check_system::impl::perform_health_check().
format_as_json()
std::string logger_module::health_check_utils::format_as_json (const health_check_result & result) static
Format health check result as JSON.
Parameters
result Health check result
Returns
JSON string representation
Definition at line 628 of file health_check_system.cpp.
References logger_module::health_check_result::get_check_time(), logger_module::health_check_result::get_issues(), logger_module::health_check_result::get_message(), logger_module::health_check_result::get_status(), and health_status_to_string().
format_writer_health()
std::string logger_module::health_check_utils::format_writer_health (const writer_health_info & info) static
Format writer health info as string.
Parameters
info Writer health information
Returns
Formatted string
Definition at line 653 of file health_check_system.cpp.
References logger_system::error, health_status_to_string(), and logger_system::info.
health_status_to_string()
std::string logger_module::health_check_utils::health_status_to_string (health_status status) static
Convert health status to string.
Parameters
status Health status
Returns
String representation
Definition at line 582 of file health_check_system.cpp.
References logger_module::degraded, logger_module::healthy, logger_module::unhealthy, and logger_module::unknown.
Referenced by format_as_json(), and format_writer_health().
The documentation for this class was generated from the following files:
/home/runner/work/logger_system/logger_system/sources/logger/health/health_check_system.h
/home/runner/work/logger_system/logger_system/sources/logger/health/health_check_system.cpp