Logger System: logger_module::template_strategy Class Reference
logger_module::template_strategy Class Reference
Strategy for applying predefined configuration templates.
#include <config_strategy_interface.h>
Public Types
enum class template_type {
default_config , high_performance , low_latency , debug ,
production
}
Public Member Functions
template_strategy (template_type type)
result_void apply (logger_config &config) override
Apply the strategy to a configuration.
std::string get_name () const override
Get strategy name for identification.
std::string get_description () const override
Get strategy description.
result_void can_apply (const logger_config &) const override
Validate if this strategy can be applied.
bool should_override () const override
Check if this strategy should override existing settings.
virtual int get_priority () const
Get the priority of this strategy (higher = applied first)
Detailed Description
Strategy for applying predefined configuration templates.
Definition at line 77 of file config_strategy_interface.h.
Member Enumeration Documentation
template_type
enum class logger_module::template_strategy::template_type strong
Enumerator
default_config
high_performance
low_latency
debug
production
Definition at line 79 of file config_strategy_interface.h.
Constructor & Destructor Documentation
template_strategy()
logger_module::template_strategy::template_strategy (template_type type) inline explicit
Definition at line 87 of file config_strategy_interface.h.
Member Function Documentation
apply()
result_void logger_module::template_strategy::apply (logger_config & config) inline override virtual
Apply the strategy to a configuration.
Parameters
config Configuration to modify
Returns
result_void indicating success or error
Implements logger_module::config_strategy_interface.
Definition at line 89 of file config_strategy_interface.h.
References debug, logger_module::logger_config::debug_config(), logger_module::logger_config::default_config(), high_performance, logger_module::logger_config::high_performance(), low_latency, logger_module::logger_config::low_latency(), production, and logger_module::logger_config::production().
can_apply()
result_void logger_module::template_strategy::can_apply (const logger_config & config) const inline override virtual
Validate if this strategy can be applied.
Parameters
config Current configuration
Returns
result_void indicating if strategy is applicable
Implements logger_module::config_strategy_interface.
Definition at line 140 of file config_strategy_interface.h.
get_description()
std::string logger_module::template_strategy::get_description () const inline override virtual
Get strategy description.
Returns
Human-readable description
Implements logger_module::config_strategy_interface.
Definition at line 125 of file config_strategy_interface.h.
References debug, high_performance, low_latency, and production.
get_name()
std::string logger_module::template_strategy::get_name () const inline override virtual
Get strategy name for identification.
Returns
Strategy name
Implements logger_module::config_strategy_interface.
Definition at line 110 of file config_strategy_interface.h.
References debug, high_performance, low_latency, and production.
get_priority()
virtual int logger_module::config_strategy_interface::get_priority () const inline virtual inherited
Get the priority of this strategy (higher = applied first)
Returns
Priority value (0-100)
Implemented in logger_module::environment_strategy, and logger_module::performance_tuning_strategy.
Definition at line 64 of file config_strategy_interface.h.
should_override()
bool logger_module::template_strategy::should_override () const inline override virtual
Check if this strategy should override existing settings.
Returns
true if strategy should override, false to merge
Implements logger_module::config_strategy_interface.
Definition at line 144 of file config_strategy_interface.h.
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/config/config_strategy_interface.h