Logger System: logger_module::adaptive_backpressure::impl Class Reference
logger_module::adaptive_backpressure::impl Class Reference
Public Member Functions
impl (const config &cfg)
void update_metrics (double queue_usage, std::chrono::milliseconds processing_time)
void adapt_internal ()
void increase_pressure ()
void decrease_pressure ()
void reset ()
size_t get_batch_size () const
std::chrono::milliseconds get_flush_interval () const
double get_current_load () const
void set_enabled (bool enabled)
bool is_enabled () const
adaptive_backpressure::adaptation_stats get_stats () const
Detailed Description
Definition at line 136 of file overflow_policy.cpp.
Constructor & Destructor Documentation
impl()
logger_module::adaptive_backpressure::impl::impl (const config & cfg) inline explicit
Definition at line 138 of file overflow_policy.cpp.
References logger_module::adaptive_backpressure::config::sample_count.
Member Function Documentation
adapt_internal()
void logger_module::adaptive_backpressure::impl::adapt_internal () inline
Definition at line 203 of file overflow_policy.cpp.
References decrease_pressure(), increase_pressure(), logger_module::adaptive_backpressure::config::load_threshold_high, and logger_module::adaptive_backpressure::config::load_threshold_low.
Referenced by update_metrics().
decrease_pressure()
void logger_module::adaptive_backpressure::impl::decrease_pressure () inline
Definition at line 231 of file overflow_policy.cpp.
References logger_module::adaptive_backpressure::config::adaptation_rate, logger_module::adaptive_backpressure::config::max_flush_interval, and logger_module::adaptive_backpressure::config::min_batch_size.
Referenced by adapt_internal().
get_batch_size()
size_t logger_module::adaptive_backpressure::impl::get_batch_size () const inline
Definition at line 259 of file overflow_policy.cpp.
get_current_load()
double logger_module::adaptive_backpressure::impl::get_current_load () const inline
Definition at line 269 of file overflow_policy.cpp.
get_flush_interval()
std::chrono::milliseconds logger_module::adaptive_backpressure::impl::get_flush_interval () const inline
Definition at line 264 of file overflow_policy.cpp.
get_stats()
adaptive_backpressure::adaptation_stats logger_module::adaptive_backpressure::impl::get_stats () const inline
Definition at line 284 of file overflow_policy.cpp.
increase_pressure()
void logger_module::adaptive_backpressure::impl::increase_pressure () inline
Definition at line 217 of file overflow_policy.cpp.
References logger_module::adaptive_backpressure::config::adaptation_rate, logger_module::adaptive_backpressure::config::max_batch_size, and logger_module::adaptive_backpressure::config::min_flush_interval.
Referenced by adapt_internal().
is_enabled()
bool logger_module::adaptive_backpressure::impl::is_enabled () const inline
Definition at line 279 of file overflow_policy.cpp.
reset()
void logger_module::adaptive_backpressure::impl::reset () inline
Definition at line 245 of file overflow_policy.cpp.
References logger_module::adaptive_backpressure::config::initial_batch_size, and logger_module::adaptive_backpressure::config::initial_flush_interval.
set_enabled()
void logger_module::adaptive_backpressure::impl::set_enabled (bool enabled) inline
Definition at line 274 of file overflow_policy.cpp.
update_metrics()
void logger_module::adaptive_backpressure::impl::update_metrics (double queue_usage, std::chrono::milliseconds processing_time) inline
Definition at line 150 of file overflow_policy.cpp.
References adapt_internal(), logger_module::adaptive_backpressure::config::metrics_window, and logger_module::adaptive_backpressure::config::sample_count.
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/flow/overflow_policy.cpp