Logger System: kcenon::common::Result< T > Class Template Reference
kcenon::common::Result< T > Class Template Reference
#include <error_codes.h>
Public Member Functions
Result ()=default
Result (T value)
Result (error_info info)
bool has_value () const
bool has_error () const
T & value ()
const T & value () const
error_info & error ()
const error_info & error () const
Private Attributes
std::optional< T > value_
std::optional< error_info > error_
Detailed Description
template<typename T>
class kcenon::common::Result< T >
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h, di_pattern_example.cpp, and monitoring_integration_example.cpp.
Definition at line 70 of file error_codes.h.
Constructor & Destructor Documentation
Result() [1/3]
template<typename T > kcenon::common::Result< T >::Result () default
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Result() [2/3]
template<typename T > kcenon::common::Result< T >::Result (T value) inline explicit
Definition at line 74 of file error_codes.h.
        : value_(std::move(value)) {}
Result() [3/3]
template<typename T > kcenon::common::Result< T >::Result (error_info info) inline explicit
Definition at line 77 of file error_codes.h.
        : error_(std::move(info)) {}
Member Function Documentation
error() [1/2]
template<typename T > error_info & kcenon::common::Result< T >::error () inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 97 of file error_codes.h.
{
        if (!error_) {
            throw std::logic_error("Result does not contain an error");
        }
        return *error_;
    }
References kcenon::common::Result< T >::error_.
Referenced by kcenon::common::get_error(), and kcenon::common::get_error().
error() [2/2]
template<typename T > const error_info & kcenon::common::Result< T >::error () const inline
Definition at line 104 of file error_codes.h.
{
        if (!error_) {
            throw std::logic_error("Result does not contain an error");
        }
        return *error_;
    }
References kcenon::common::Result< T >::error_.
has_error()
template<typename T > bool kcenon::common::Result< T >::has_error () const inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 81 of file error_codes.h.
{ return error_.has_value(); }
References kcenon::common::Result< T >::error_.
Referenced by kcenon::common::is_error().
has_value()
template<typename T > bool kcenon::common::Result< T >::has_value () const inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 80 of file error_codes.h.
{ return value_.has_value(); }
References kcenon::common::Result< T >::value_.
Referenced by kcenon::common::is_ok().
value() [1/2]
template<typename T > T & kcenon::common::Result< T >::value () inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 83 of file error_codes.h.
               {
        if (!value_) {
            throw std::logic_error("Result does not contain a value");
        }
        return *value_;
    }
References kcenon::common::Result< T >::value_.
Referenced by kcenon::common::get_value(), and kcenon::common::get_value().
value() [2/2]
template<typename T > const T & kcenon::common::Result< T >::value () const inline
Definition at line 90 of file error_codes.h.
{
        if (!value_) {
            throw std::logic_error("Result does not contain a value");
        }
        return *value_;
    }
References kcenon::common::Result< T >::value_.
Member Data Documentation
error_
template<typename T > std::optional<error_info> kcenon::common::Result< T >::error_ private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 113 of file error_codes.h.
Referenced by kcenon::common::Result< T >::error(), kcenon::common::Result< T >::error(), and kcenon::common::Result< T >::has_error().
value_
template<typename T > std::optional<T> kcenon::common::Result< T >::value_ private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 112 of file error_codes.h.
Referenced by kcenon::common::Result< T >::has_value(), kcenon::common::Result< T >::value(), and kcenon::common::Result< T >::value().
The documentation for this class was generated from the following file:
include/kcenon/logger/core/error_codes.h