Logger System: logger_module::thread_system_monitor_adapter Class Reference
logger_module::thread_system_monitor_adapter Class Reference
Adapter to use thread_system's monitoring capabilities.
#include <thread_system_monitor_adapter.h>
Public Member Functions
thread_system_monitor_adapter (thread_module::monitorable_interface *monitorable)
Constructor with external monitorable.
thread_system_monitor_adapter ()
Default constructor with fallback to basic monitor.
~thread_system_monitor_adapter () override
Destructor.
result< monitoring_data > collect_metrics () const override
Collect current metrics.
result< health_check_result > check_health () const override
Perform health check.
result_void reset_metrics () override
Reset all metrics.
result_void set_enabled (bool enable) override
Enable or disable monitoring.
bool is_enabled () const override
Check if monitoring is enabled.
std::string get_backend_name () const override
Get backend name.
void increment_counter (const std::string &name, double value=1.0) override
Increment a counter.
void update_gauge (const std::string &name, double value) override
Update a gauge.
void record_histogram (const std::string &name, double value) override
Record a histogram value.
void set_monitorable (thread_module::monitorable_interface *monitorable, bool take_ownership=false)
Set the thread_system monitorable.
basic_monitor * get_fallback_monitor ()
Get the fallback monitor for direct access.
Detailed Description
Adapter to use thread_system's monitoring capabilities.
This adapter wraps thread_system's monitorable_interface to provide compatibility with our monitoring interface, enabling advanced monitoring features when thread_system is available.
Definition at line 33 of file thread_system_monitor_adapter.h.
Constructor & Destructor Documentation
thread_system_monitor_adapter() [1/2]
logger_module::thread_system_monitor_adapter::thread_system_monitor_adapter (thread_module::monitorable_interface * monitorable) inline explicit
Constructor with external monitorable.
Parameters
monitorable Pointer to existing monitorable interface
Definition at line 45 of file thread_system_monitor_adapter.h.
thread_system_monitor_adapter() [2/2]
logger_module::thread_system_monitor_adapter::thread_system_monitor_adapter () inline
Default constructor with fallback to basic monitor.
Definition at line 58 of file thread_system_monitor_adapter.h.
~thread_system_monitor_adapter()
logger_module::thread_system_monitor_adapter::~thread_system_monitor_adapter () inline override
Destructor.
Definition at line 66 of file thread_system_monitor_adapter.h.
Member Function Documentation
check_health()
result< health_check_result > logger_module::thread_system_monitor_adapter::check_health () const inline override virtual
Perform health check.
Returns
Result containing health check result
Implements logger_module::monitoring_interface.
Definition at line 124 of file thread_system_monitor_adapter.h.
References logger_module::health_check_result::add_issue(), logger_module::degraded, logger_module::health_check_result::get_status(), logger_module::healthy, logger_module::health_check_result::is_healthy(), logger_module::health_check_result::set_message(), logger_module::health_check_result::set_status(), and logger_module::unhealthy.
collect_metrics()
result< monitoring_data > logger_module::thread_system_monitor_adapter::collect_metrics () const inline override virtual
Collect current metrics.
Returns
Result containing monitoring data
Implements logger_module::monitoring_interface.
Definition at line 76 of file thread_system_monitor_adapter.h.
References logger_module::monitoring_data::add_metric(), and logger_module::metrics_not_available.
get_backend_name()
std::string logger_module::thread_system_monitor_adapter::get_backend_name () const inline override virtual
Get backend name.
Returns
"thread_system" or "thread_system+basic"
Implements logger_module::monitoring_interface.
Definition at line 238 of file thread_system_monitor_adapter.h.
get_fallback_monitor()
basic_monitor * logger_module::thread_system_monitor_adapter::get_fallback_monitor () inline
Get the fallback monitor for direct access.
Returns
Pointer to fallback monitor
Definition at line 324 of file thread_system_monitor_adapter.h.
increment_counter()
void logger_module::thread_system_monitor_adapter::increment_counter (const std::string & name, double value = 1.0) inline override virtual
Increment a counter.
Parameters
name Counter name
value Increment value
Implements logger_module::monitoring_interface.
Definition at line 250 of file thread_system_monitor_adapter.h.
is_enabled()
bool logger_module::thread_system_monitor_adapter::is_enabled () const inline override virtual
Check if monitoring is enabled.
Returns
true if enabled
Implements logger_module::monitoring_interface.
Definition at line 230 of file thread_system_monitor_adapter.h.
record_histogram()
void logger_module::thread_system_monitor_adapter::record_histogram (const std::string & name, double value) inline override virtual
Record a histogram value.
Parameters
name Histogram name
value Value to record
Implements logger_module::monitoring_interface.
Definition at line 296 of file thread_system_monitor_adapter.h.
reset_metrics()
result_void logger_module::thread_system_monitor_adapter::reset_metrics () inline override virtual
Reset all metrics.
Returns
Result indicating success
Implements logger_module::monitoring_interface.
Definition at line 185 of file thread_system_monitor_adapter.h.
References logger_module::operation_failed.
set_enabled()
result_void logger_module::thread_system_monitor_adapter::set_enabled (bool enable) inline override virtual
Enable or disable monitoring.
Parameters
enable true to enable
Returns
Result indicating success
Implements logger_module::monitoring_interface.
Definition at line 216 of file thread_system_monitor_adapter.h.
set_monitorable()
void logger_module::thread_system_monitor_adapter::set_monitorable (thread_module::monitorable_interface * monitorable, bool take_ownership = false) inline
Set the thread_system monitorable.
Parameters
monitorable Pointer to monitorable interface
take_ownership Whether to take ownership
Definition at line 310 of file thread_system_monitor_adapter.h.
update_gauge()
void logger_module::thread_system_monitor_adapter::update_gauge (const std::string & name, double value) inline override virtual
Update a gauge.
Parameters
name Gauge name
value New value
Implements logger_module::monitoring_interface.
Definition at line 273 of file thread_system_monitor_adapter.h.
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/monitoring/thread_system_monitor_adapter.h