Logger System: logger_module::config_strategy_factory Class Reference
logger_module::config_strategy_factory Class Reference
Factory for creating configuration strategies.
#include <config_strategy_interface.h>
Static Public Member Functions
static std::unique_ptr< config_strategy_interface > create_template (const std::string &name)
Create a template strategy.
static std::unique_ptr< config_strategy_interface > create_environment (const std::string &env)
Create an environment strategy.
static std::unique_ptr< config_strategy_interface > create_tuning (const std::string &level)
Create a performance tuning strategy.
static std::unique_ptr< config_strategy_interface > from_environment ()
Create a strategy from environment variable.
Detailed Description
Factory for creating configuration strategies.
Definition at line 384 of file config_strategy_interface.h.
Member Function Documentation
create_environment()
static std::unique_ptr< config_strategy_interface > logger_module::config_strategy_factory::create_environment (const std::string & env) inline static
Create an environment strategy.
Parameters
env Environment name
Returns
Strategy instance or nullptr if environment is invalid
Examples
/home/runner/work/logger_system/logger_system/sources/logger/config/logger_builder.h.
Definition at line 411 of file config_strategy_interface.h.
References logger_module::environment_strategy::development, logger_module::environment_strategy::production, logger_module::environment_strategy::staging, and logger_module::environment_strategy::testing.
Referenced by logger_module::logger_builder::for_environment(), and from_environment().
create_template()
static std::unique_ptr< config_strategy_interface > logger_module::config_strategy_factory::create_template (const std::string & name) inline static
Create a template strategy.
Parameters
name Template name
Returns
Strategy instance or nullptr if name is invalid
Examples
/home/runner/work/logger_system/logger_system/sources/logger/config/logger_builder.h.
Definition at line 391 of file config_strategy_interface.h.
References logger_module::template_strategy::debug, logger_module::template_strategy::default_config, logger_module::template_strategy::high_performance, logger_module::template_strategy::low_latency, and logger_module::template_strategy::production.
Referenced by from_environment(), and logger_module::logger_builder::use_template().
create_tuning()
static std::unique_ptr< config_strategy_interface > logger_module::config_strategy_factory::create_tuning (const std::string & level) inline static
Create a performance tuning strategy.
Parameters
level Tuning level name
Returns
Strategy instance
Examples
/home/runner/work/logger_system/logger_system/sources/logger/config/logger_builder.h.
Definition at line 429 of file config_strategy_interface.h.
References logger_module::performance_tuning_strategy::aggressive, logger_module::performance_tuning_strategy::balanced, and logger_module::performance_tuning_strategy::conservative.
Referenced by logger_module::logger_builder::with_performance_tuning().
from_environment()
static std::unique_ptr< config_strategy_interface > logger_module::config_strategy_factory::from_environment () inline static
Create a strategy from environment variable.
Returns
Strategy based on LOG_ENV or nullptr
Examples
/home/runner/work/logger_system/logger_system/sources/logger/config/logger_builder.h.
Definition at line 445 of file config_strategy_interface.h.
References create_environment(), and create_template().
Referenced by logger_module::logger_builder::auto_configure().
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/config/config_strategy_interface.h