Logger System: kcenon::logger::filter_factory Class Reference
kcenon::logger::filter_factory Class Reference
Factory for creating log filter instances.
#include <filter_factory.h>
Classes
class builder
Filter builder for complex filter construction.
Public Types
using creator_fn = std::function<std::unique_ptr<log_filter_interface>()>
Static Public Member Functions
static std::unique_ptr< log_filter_interface > create_level (log_level min_level)
Create a level filter.
static std::unique_ptr< log_filter_interface > create_regex (const std::string &pattern, bool include_matches=true)
Create a regex filter.
static std::unique_ptr< log_filter_interface > create_function (std::function< bool(const log_entry &)> predicate)
Create a function-based filter.
static std::unique_ptr< filters::composite_filter > create_composite_and ()
Create a composite filter with AND logic.
static std::unique_ptr< filters::composite_filter > create_composite_or ()
Create a composite filter with OR logic.
static std::unique_ptr< log_filter_interface > create_development ()
Create a development filter.
static std::unique_ptr< log_filter_interface > create_production ()
Create a production filter.
static std::unique_ptr< log_filter_interface > create_errors_only ()
Create an error-only filter.
static std::unique_ptr< log_filter_interface > create_component_filter (const std::string &component)
Create a debug filter for specific component.
static std::unique_ptr< log_filter_interface > create_sensitive_filter ()
Create a sensitive data filter.
static builder create_builder ()
Start building a filter.
static void register_type (const std::string &name, creator_fn creator)
Register a custom filter type.
static std::unique_ptr< log_filter_interface > create (const std::string &name)
Create a filter by registered name.
static bool has_type (const std::string &name)
Check if a filter type is registered.
Static Private Member Functions
static std::unordered_map< std::string, creator_fn > & registry ()
Detailed Description
Factory for creating log filter instances.
Provides static factory methods for all built-in filter types and a registry pattern for custom filter types.
Since
2.0.0
Definition at line 36 of file filter_factory.h.
Member Typedef Documentation
creator_fn
using kcenon::logger::filter_factory::creator_fn = std::function<std::unique_ptr<log_filter_interface>()>
Definition at line 38 of file filter_factory.h.
Member Function Documentation
create()
static std::unique_ptr< log_filter_interface > kcenon::logger::filter_factory::create (const std::string & name) inline static
Create a filter by registered name.
Parameters
name Registered type name
Returns
Unique pointer to filter, or nullptr if not found
Definition at line 242 of file filter_factory.h.
{
        auto it = registry().find(name);
        if (it == registry().end()) {
            return nullptr;
        }
        return it->second();
    }
References registry().
create_builder()
static builder kcenon::logger::filter_factory::create_builder () inline static
Start building a filter.
Returns
Filter builder
Definition at line 220 of file filter_factory.h.
{
        return builder{};
    }
create_component_filter()
static std::unique_ptr< log_filter_interface > kcenon::logger::filter_factory::create_component_filter (const std::string & component) inline static
Create a debug filter for specific component.
Parameters
component Component name to filter
Returns
Filter that matches messages containing the component
Definition at line 135 of file filter_factory.h.
      {
        return create_regex("\\[" + component + "\\]", true);
    }
References create_regex().
create_composite_and()
static std::unique_ptr< filters::composite_filter > kcenon::logger::filter_factory::create_composite_and () inline static
Create a composite filter with AND logic.
Returns
Unique pointer to composite filter
Definition at line 83 of file filter_factory.h.
{
        return std::make_unique<filters::composite_filter>(
            filters::composite_filter::logic_type::AND
        );
    }
References kcenon::logger::filters::composite_filter::AND.
Referenced by kcenon::logger::filter_factory::builder::build(), and create_production().
create_composite_or()
static std::unique_ptr< filters::composite_filter > kcenon::logger::filter_factory::create_composite_or () inline static
Create a composite filter with OR logic.
Returns
Unique pointer to composite filter
Definition at line 93 of file filter_factory.h.
{
        return std::make_unique<filters::composite_filter>(
            filters::composite_filter::logic_type::OR
        );
    }
References kcenon::logger::filters::composite_filter::OR.
create_development()
static std::unique_ptr< log_filter_interface > kcenon::logger::filter_factory::create_development () inline static
Create a development filter.
Returns
Filter that passes all messages (trace and above)
Definition at line 107 of file filter_factory.h.
{
        return create_level(log_level::trace);
    }
References create_level().
create_errors_only()
static std::unique_ptr< log_filter_interface > kcenon::logger::filter_factory::create_errors_only () inline static
Create an error-only filter.
Returns
Filter that only passes error and fatal messages
Definition at line 126 of file filter_factory.h.
{
        return create_level(log_level::error);
    }
References create_level().
create_function()
static std::unique_ptr< log_filter_interface > kcenon::logger::filter_factory::create_function (std::function< bool(const log_entry &)> predicate) inline static
Create a function-based filter.
Parameters
predicate Filter function
Returns
Unique pointer to function filter
Definition at line 73 of file filter_factory.h.
      {
        return std::make_unique<filters::function_filter>(std::move(predicate));
    }
Referenced by kcenon::logger::filter_factory::builder::with_predicate().
create_level()
static std::unique_ptr< log_filter_interface > kcenon::logger::filter_factory::create_level (log_level min_level) inline static
Create a level filter.
Parameters
min_level Minimum log level to pass through
Returns
Unique pointer to level filter
Definition at line 49 of file filter_factory.h.
      {
        return std::make_unique<filters::level_filter>(min_level);
    }
Referenced by create_development(), create_errors_only(), create_production(), and kcenon::logger::filter_factory::builder::with_min_level().
create_production()
static std::unique_ptr< log_filter_interface > kcenon::logger::filter_factory::create_production () inline static
Create a production filter.
Returns
Composite filter: warning+ and no sensitive data
Definition at line 115 of file filter_factory.h.
{
        auto composite = create_composite_and();
        composite->add_filter(create_level(log_level::warning));
        composite->add_filter(create_regex("password|secret|token|api.?key", false));
        return composite;
    }
References kcenon::logger::composite, create_composite_and(), create_level(), and create_regex().
create_regex()
static std::unique_ptr< log_filter_interface > kcenon::logger::filter_factory::create_regex (const std::string & pattern, bool include_matches = true) inline static
Create a regex filter.
Parameters
pattern Regex pattern to match
include_matches true to include matches, false to exclude
Returns
Unique pointer to regex filter
Definition at line 61 of file filter_factory.h.
      {
        return std::make_unique<filters::regex_filter>(pattern, include_matches);
    }
Referenced by create_component_filter(), create_production(), create_sensitive_filter(), kcenon::logger::filter_factory::builder::exclude_pattern(), and kcenon::logger::filter_factory::builder::include_pattern().
create_sensitive_filter()
static std::unique_ptr< log_filter_interface > kcenon::logger::filter_factory::create_sensitive_filter () inline static
Create a sensitive data filter.
Returns
Filter that excludes messages with sensitive patterns
Definition at line 145 of file filter_factory.h.
{
        return create_regex(
            "password|secret|token|api.?key|credential|auth|bearer",
            false  // Exclude matches
        );
    }
References create_regex().
has_type()
static bool kcenon::logger::filter_factory::has_type (const std::string & name) inline static
Check if a filter type is registered.
Parameters
name Type name to check
Returns
true if registered
Definition at line 255 of file filter_factory.h.
{
        return registry().find(name) != registry().end();
    }
References registry().
register_type()
static void kcenon::logger::filter_factory::register_type (const std::string & name, creator_fn creator) inline static
Register a custom filter type.
Parameters
name Type name for the filter
creator Factory function to create the filter
Definition at line 233 of file filter_factory.h.
{
        registry()[name] = std::move(creator);
    }
References registry().
registry()
static std::unordered_map< std::string, creator_fn > & kcenon::logger::filter_factory::registry () inline static private
Definition at line 260 of file filter_factory.h.
{
        static std::unordered_map<std::string, creator_fn> instance;
        return instance;
    }
Referenced by create(), has_type(), and register_type().
The documentation for this class was generated from the following file:
include/kcenon/logger/factories/filter_factory.h