Logger System: logger_module::logger::impl Class Reference
logger_module::logger::impl Class Reference
Public Member Functions
impl (bool async, std::size_t buffer_size)
~impl ()
void log (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function)
void flush ()
result_void add_writer (std::unique_ptr< base_writer > writer)
void add_writer (const std::string &name, std::unique_ptr< base_writer > writer)
result_void clear_writers ()
result_void start ()
result_void stop ()
bool is_running () const
void set_min_level (thread_module::log_level level)
thread_module::log_level get_min_level () const
result_void enable_metrics_collection (bool enable)
bool is_metrics_collection_enabled () const
result< performance_metrics > get_current_metrics () const
result< std::unique_ptr< performance_metrics > > get_metrics_history (std::chrono::seconds duration) const
result_void reset_metrics ()
logger_metrics_collector * get_metrics_collector ()
bool remove_writer (const std::string &name)
base_writer * get_writer (const std::string &name)
void set_filter (std::unique_ptr< log_filter > filter)
log_router & get_router ()
Detailed Description
Definition at line 47 of file logger.cpp.
Constructor & Destructor Documentation
impl()
logger_module::logger::impl::impl (bool async, std::size_t buffer_size) inline
Definition at line 49 of file logger.cpp.
~impl()
logger_module::logger::impl::~impl () inline
Definition at line 61 of file logger.cpp.
References stop().
Member Function Documentation
add_writer() [1/2]
void logger_module::logger::impl::add_writer (const std::string & name, std::unique_ptr< base_writer > writer) inline
Definition at line 172 of file logger.cpp.
add_writer() [2/2]
result_void logger_module::logger::impl::add_writer (std::unique_ptr< base_writer > writer) inline
Definition at line 151 of file logger.cpp.
References logger_module::invalid_argument, and logger_module::make_logger_error().
clear_writers()
result_void logger_module::logger::impl::clear_writers () inline
Definition at line 181 of file logger.cpp.
enable_metrics_collection()
result_void logger_module::logger::impl::enable_metrics_collection (bool enable) inline
Definition at line 220 of file logger.cpp.
flush()
void logger_module::logger::impl::flush () inline
Definition at line 139 of file logger.cpp.
Referenced by stop().
get_current_metrics()
result< performance_metrics > logger_module::logger::impl::get_current_metrics () const inline
Definition at line 232 of file logger.cpp.
References logger_module::metrics_not_available.
get_metrics_collector()
logger_metrics_collector * logger_module::logger::impl::get_metrics_collector () inline
Definition at line 260 of file logger.cpp.
get_metrics_history()
result< std::unique_ptr< performance_metrics > > logger_module::logger::impl::get_metrics_history (std::chrono::seconds duration) const inline
Definition at line 240 of file logger.cpp.
References logger_module::metrics_not_available.
get_min_level()
thread_module::log_level logger_module::logger::impl::get_min_level () const inline
Definition at line 216 of file logger.cpp.
get_router()
log_router & logger_module::logger::impl::get_router () inline
Definition at line 288 of file logger.cpp.
get_writer()
base_writer * logger_module::logger::impl::get_writer (const std::string & name) inline
Definition at line 278 of file logger.cpp.
is_metrics_collection_enabled()
bool logger_module::logger::impl::is_metrics_collection_enabled () const inline
Definition at line 228 of file logger.cpp.
is_running()
bool logger_module::logger::impl::is_running () const inline
Definition at line 208 of file logger.cpp.
log()
void logger_module::logger::impl::log (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function) inline
Definition at line 65 of file logger.cpp.
References start(), and logger_module::success.
remove_writer()
bool logger_module::logger::impl::remove_writer (const std::string & name) inline
Definition at line 264 of file logger.cpp.
reset_metrics()
result_void logger_module::logger::impl::reset_metrics () inline
Definition at line 251 of file logger.cpp.
References logger_module::make_logger_error(), and logger_module::metrics_not_available.
set_filter()
void logger_module::logger::impl::set_filter (std::unique_ptr< log_filter > filter) inline
Definition at line 284 of file logger.cpp.
set_min_level()
void logger_module::logger::impl::set_min_level (thread_module::log_level level) inline
Definition at line 212 of file logger.cpp.
start()
result_void logger_module::logger::impl::start () inline
Definition at line 191 of file logger.cpp.
Referenced by log().
stop()
result_void logger_module::logger::impl::stop () inline
Definition at line 198 of file logger.cpp.
References flush().
Referenced by ~impl().
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/logger.cpp