Logger System: kcenon::logger::security::secure_key Class Reference
kcenon::logger::security::secure_key Class Reference
RAII wrapper for encryption keys with secure memory management.
#include <secure_key_storage.h>
Public Member Functions
secure_key (size_t size)
Construct with specified size.
secure_key (std::vector< uint8_t > data)
Construct with data.
~secure_key ()
Destructor - securely clears key from memory.
secure_key (const secure_key &)=delete
secure_key & operator= (const secure_key &)=delete
secure_key (secure_key &&other) noexcept
secure_key & operator= (secure_key &&other) noexcept
const std::vector< uint8_t > & data () const
Get const reference to key data.
std::vector< uint8_t > & mutable_data ()
Get mutable reference to key data (use with caution)
size_t size () const
Get key size in bytes.
Private Member Functions
void secure_clear ()
Securely clear key data from memory.
Private Attributes
std::vector< uint8_t > data_
Detailed Description
RAII wrapper for encryption keys with secure memory management.
Features:
Automatic memory cleanup on destruction
Move-only semantics (prevents accidental copies)
Secure random generation with OpenSSL (if available)
Definition at line 40 of file secure_key_storage.h.
Constructor & Destructor Documentation
secure_key() [1/4]
kcenon::logger::security::secure_key::secure_key (size_t size) inline explicit
Construct with specified size.
Parameters
size Key size in bytes (32 for AES-256)
Definition at line 46 of file secure_key_storage.h.
        : data_(size, 0) {
    }
secure_key() [2/4]
kcenon::logger::security::secure_key::secure_key (std::vector< uint8_t > data) inline explicit
Construct with data.
Parameters
data Key data
Definition at line 54 of file secure_key_storage.h.
        : data_(std::move(data)) {
    }
~secure_key()
kcenon::logger::security::secure_key::~secure_key () inline
Destructor - securely clears key from memory.
Definition at line 61 of file secure_key_storage.h.
                  {
        secure_clear();
    }
References secure_clear().
secure_key() [3/4]
kcenon::logger::security::secure_key::secure_key (const secure_key &) delete
secure_key() [4/4]
kcenon::logger::security::secure_key::secure_key (secure_key && other) inline noexcept
Definition at line 70 of file secure_key_storage.h.
        : data_(std::move(other.data_)) {
        // Clear the moved-from object
        other.secure_clear();
    }
Member Function Documentation
data()
const std::vector< uint8_t > & kcenon::logger::security::secure_key::data () const inline
Get const reference to key data.
Definition at line 88 of file secure_key_storage.h.
{
        return data_;
    }
References data_.
Referenced by kcenon::logger::security::audit_logger::calculate_hmac(), kcenon::logger::encrypted_writer::decrypt_entry(), and kcenon::logger::security::secure_key_storage::save_key().
mutable_data()
std::vector< uint8_t > & kcenon::logger::security::secure_key::mutable_data () inline
Get mutable reference to key data (use with caution)
Definition at line 95 of file secure_key_storage.h.
{
        return data_;
    }
References data_.
Referenced by kcenon::logger::security::secure_key_storage::generate_key(), and kcenon::logger::security::secure_key_storage::load_key().
operator=() [1/2]
secure_key & kcenon::logger::security::secure_key::operator= (const secure_key &) delete
operator=() [2/2]
secure_key & kcenon::logger::security::secure_key::operator= (secure_key && other) inline noexcept
Definition at line 76 of file secure_key_storage.h.
{
        if (this != &other) {
            secure_clear();
            data_ = std::move(other.data_);
            other.secure_clear();
        }
        return *this;
    }
References data_, and secure_clear().
secure_clear()
void kcenon::logger::security::secure_key::secure_clear () inline private
Securely clear key data from memory.
Definition at line 110 of file secure_key_storage.h.
{
        if (data_.empty()) {
            return;
        }
#ifdef HAS_OPENSSL
        // Use OpenSSL's secure memory clearing
        OPENSSL_cleanse(data_.data(), data_.size());
#else
        // Fallback: manual zeroing with volatile to prevent optimization
        volatile uint8_t* ptr = data_.data();
        for (size_t i = 0; i < data_.size(); ++i) {
            ptr[i] = 0;
        }
#endif
        data_.clear();
    }
References data_.
Referenced by operator=(), and ~secure_key().
size()
size_t kcenon::logger::security::secure_key::size () const inline
Get key size in bytes.
Definition at line 102 of file secure_key_storage.h.
{
        return data_.size();
    }
References data_.
Referenced by kcenon::logger::security::audit_logger::calculate_hmac(), kcenon::logger::encrypted_writer::encrypted_writer(), kcenon::logger::encrypted_writer::rotate_key(), and kcenon::logger::security::secure_key_storage::save_key().
Member Data Documentation
data_
std::vector<uint8_t> kcenon::logger::security::secure_key::data_ private
Definition at line 128 of file secure_key_storage.h.
Referenced by data(), mutable_data(), operator=(), secure_clear(), and size().
The documentation for this class was generated from the following file:
include/kcenon/logger/security/secure_key_storage.h