Logger System: kcenon::logger::utils::time_utils Class Reference
kcenon::logger::utils::time_utils Class Reference
Time utility functions for timestamp formatting.
#include <time_utils.h>
Static Public Member Functions
static std::string format_timestamp (const std::chrono::system_clock::time_point &tp)
Format timestamp to human-readable format (YYYY-MM-DD HH:MM:SS.mmm)
static std::string format_iso8601 (const std::chrono::system_clock::time_point &tp)
Format timestamp to ISO 8601 / RFC 3339 format with UTC timezone.
static std::string format_compact (const std::chrono::system_clock::time_point &tp)
Format timestamp to compact format (YYYYMMDDHHMMSSmmm)
static std::string format_for_rotation (const std::chrono::system_clock::time_point &tp, bool include_hour=false)
Format timestamp for file rotation (YYYYMMDD or YYYYMMDD_HH)
static std::chrono::system_clock::time_point now ()
Get current system time as time_point.
Detailed Description
Time utility functions for timestamp formatting.
Provides thread-safe timestamp formatting functions in various formats commonly used in logging systems.
Definition at line 27 of file time_utils.h.
Member Function Documentation
format_compact()
static std::string kcenon::logger::utils::time_utils::format_compact (const std::chrono::system_clock::time_point & tp) inline static
Format timestamp to compact format (YYYYMMDDHHMMSSmmm)
Parameters
tp Time point to format
Returns
Compact timestamp string without separators
Output format: "20251103143015123"
Note
Useful for filename generation and sorting.
Thread-safe.
Definition at line 115 of file time_utils.h.
      {
        auto time_t = std::chrono::system_clock::to_time_t(tp);
        std::tm tm_buf{};
#ifdef _WIN32
        localtime_s(&tm_buf, &time_t);
#else
        localtime_r(&time_t, &tm_buf);
#endif
        // Format compact timestamp
        char buffer[32];
        std::strftime(buffer, sizeof(buffer), "%Y%m%d%H%M%S", &tm_buf);
        // Add milliseconds
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
            tp.time_since_epoch()
        ) % 1000;
        std::ostringstream oss;
        oss << buffer
            << std::setfill('0') << std::setw(3) << ms.count();
        return oss.str();
    }
format_for_rotation()
static std::string kcenon::logger::utils::time_utils::format_for_rotation (const std::chrono::system_clock::time_point & tp, bool include_hour = false) inline static
Format timestamp for file rotation (YYYYMMDD or YYYYMMDD_HH)
Parameters
tp Time point to format
include_hour Whether to include hour in the format
Returns
Formatted timestamp suitable for file naming
Output formats:
Without hour: "20251103"
With hour: "20251103_14"
Note
Useful for rotating file writers.
Thread-safe.
Definition at line 156 of file time_utils.h.
      {
        auto time_t = std::chrono::system_clock::to_time_t(tp);
        std::tm tm_buf{};
#ifdef _WIN32
        localtime_s(&tm_buf, &time_t);
#else
        localtime_r(&time_t, &tm_buf);
#endif
        char buffer[32];
        if (include_hour) {
            std::strftime(buffer, sizeof(buffer), "%Y%m%d_%H", &tm_buf);
        } else {
            std::strftime(buffer, sizeof(buffer), "%Y%m%d", &tm_buf);
        }
        return std::string(buffer);
    }
format_iso8601()
static std::string kcenon::logger::utils::time_utils::format_iso8601 (const std::chrono::system_clock::time_point & tp) inline static
Format timestamp to ISO 8601 / RFC 3339 format with UTC timezone.
Parameters
tp Time point to format
Returns
ISO 8601 formatted timestamp string
Output format: "2025-11-03T14:30:15.123Z"
Note
Thread-safe. Always outputs in UTC (Z timezone indicator).
Compatible with JSON parsers and log aggregation systems (ELK, Splunk, etc.)
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/formatters/template_formatter.h.
Definition at line 76 of file time_utils.h.
      {
        auto time_t = std::chrono::system_clock::to_time_t(tp);
        std::tm tm_buf{};
#ifdef _WIN32
        gmtime_s(&tm_buf, &time_t);  // Windows thread-safe version (UTC)
#else
        gmtime_r(&time_t, &tm_buf);  // POSIX thread-safe version (UTC)
#endif
        // Format base timestamp (ISO 8601)
        char buffer[32];
        std::strftime(buffer, sizeof(buffer), "%Y-%m-%dT%H:%M:%S", &tm_buf);
        // Add milliseconds
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
            tp.time_since_epoch()
        ) % 1000;
        std::ostringstream oss;
        oss << buffer << "."
            << std::setfill('0') << std::setw(3) << ms.count()
            << "Z";  // UTC timezone indicator
        return oss.str();
    }
Referenced by kcenon::logger::json_formatter::format(), kcenon::logger::logfmt_formatter::format(), and kcenon::logger::template_formatter::resolve_placeholder().
format_timestamp()
static std::string kcenon::logger::utils::time_utils::format_timestamp (const std::chrono::system_clock::time_point & tp) inline static
Format timestamp to human-readable format (YYYY-MM-DD HH:MM:SS.mmm)
Parameters
tp Time point to format
Returns
Formatted timestamp string with millisecond precision
Output format: "2025-11-03 14:30:15.123"
Note
Thread-safe. Uses platform-specific thread-safe time conversion.
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/formatters/template_formatter.h.
Definition at line 38 of file time_utils.h.
      {
        auto time_t = std::chrono::system_clock::to_time_t(tp);
        std::tm tm_buf{};
#ifdef _WIN32
        localtime_s(&tm_buf, &time_t);  // Windows thread-safe version
#else
        localtime_r(&time_t, &tm_buf);  // POSIX thread-safe version
#endif
        // Format base timestamp
        char buffer[32];
        std::strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M:%S", &tm_buf);
        // Add milliseconds
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
            tp.time_since_epoch()
        ) % 1000;
        std::ostringstream oss;
        oss << buffer << "."
            << std::setfill('0') << std::setw(3) << ms.count();
        return oss.str();
    }
Referenced by kcenon::logger::timestamp_formatter::format(), and kcenon::logger::template_formatter::resolve_placeholder().
now()
static std::chrono::system_clock::time_point kcenon::logger::utils::time_utils::now () inline static
Get current system time as time_point.
Returns
Current time_point
Note
Convenience function for getting current time.
Definition at line 185 of file time_utils.h.
{
        return std::chrono::system_clock::now();
    }
The documentation for this class was generated from the following file:
include/kcenon/logger/utils/time_utils.h