Logger System: logger_adapter Class Reference
logger_adapter Class Reference
Public Member Functions
logger_adapter (std::shared_ptr< logger_core > core)
virtual ~logger_adapter ()=default
void log (const std::string &message)
size_t message_count () const
Protected Attributes
std::shared_ptr< logger_core > core_
Detailed Description
Examples
adapter_pattern_poc.cpp, and di_pattern_example.cpp.
Definition at line 89 of file adapter_pattern_poc.cpp.
Constructor & Destructor Documentation
logger_adapter()
logger_adapter::logger_adapter (std::shared_ptr< logger_core > core) inline explicit
Examples
adapter_pattern_poc.cpp.
Definition at line 91 of file adapter_pattern_poc.cpp.
        : core_(std::move(core)) {}
~logger_adapter()
virtual logger_adapter::~logger_adapter () virtual default
Examples
adapter_pattern_poc.cpp.
Member Function Documentation
log()
void logger_adapter::log (const std::string & message) inline
Examples
adapter_pattern_poc.cpp.
Definition at line 97 of file adapter_pattern_poc.cpp.
{
        core_->log_internal(message);
    }
References core_, and logger_core::log_internal().
Referenced by full_integration_adapter::external_log(), thread_system_adapter::external_log(), standalone_adapter::log_standalone(), common_system_adapter::monitored_log(), and full_integration_adapter::monitored_log().
message_count()
size_t logger_adapter::message_count () const inline
Examples
adapter_pattern_poc.cpp.
Definition at line 101 of file adapter_pattern_poc.cpp.
{
        return core_->message_count();
    }
References core_, and logger_core::message_count().
Referenced by full_integration_adapter::get_metric_count().
Member Data Documentation
core_
std::shared_ptr<logger_core> logger_adapter::core_ protected
Examples
adapter_pattern_poc.cpp.
Definition at line 106 of file adapter_pattern_poc.cpp.
Referenced by log(), and message_count().
The documentation for this class was generated from the following file:
examples/adapter_pattern_poc.cpp