Logger System: full_integration_adapter Class Reference
full_integration_adapter Class Reference
Public Member Functions
void external_log (const std::string &message) override
std::string get_interface_name () const override
void monitored_log (const std::string &message) override
size_t get_metric_count () const override
logger_adapter (std::shared_ptr< logger_core > core)
Public Member Functions inherited from logger_adapter
logger_adapter (std::shared_ptr< logger_core > core)
virtual ~logger_adapter ()=default
void log (const std::string &message)
size_t message_count () const
Public Member Functions inherited from external_system_interface
virtual ~external_system_interface ()=default
Public Member Functions inherited from common_system_interface
virtual ~common_system_interface ()=default
Additional Inherited Members
Protected Attributes inherited from logger_adapter
std::shared_ptr< logger_core > core_
Detailed Description
Examples
adapter_pattern_poc.cpp.
Definition at line 177 of file adapter_pattern_poc.cpp.
Member Function Documentation
external_log()
void full_integration_adapter::external_log (const std::string & message) inline override virtual
Implements external_system_interface.
Examples
adapter_pattern_poc.cpp.
Definition at line 184 of file adapter_pattern_poc.cpp.
{
        std::cout << "[Full Integration - External] ";
        log(message);
    }
References logger_adapter::log().
get_interface_name()
std::string full_integration_adapter::get_interface_name () const inline override virtual
Implements external_system_interface.
Examples
adapter_pattern_poc.cpp.
Definition at line 189 of file adapter_pattern_poc.cpp.
{
        return "full_integration";
    }
get_metric_count()
size_t full_integration_adapter::get_metric_count () const inline override virtual
Implements common_system_interface.
Examples
adapter_pattern_poc.cpp.
Definition at line 198 of file adapter_pattern_poc.cpp.
{
        return message_count();
    }
References logger_adapter::message_count().
logger_adapter()
logger_adapter::logger_adapter (std::shared_ptr< logger_core > core) inline explicit
Definition at line 91 of file adapter_pattern_poc.cpp.
        : core_(std::move(core)) {}
monitored_log()
void full_integration_adapter::monitored_log (const std::string & message) inline override virtual
Implements common_system_interface.
Examples
adapter_pattern_poc.cpp.
Definition at line 193 of file adapter_pattern_poc.cpp.
{
        std::cout << "[Full Integration - Monitored] ";
        log(message);
    }
References logger_adapter::log().
The documentation for this class was generated from the following file:
examples/adapter_pattern_poc.cpp