Logger System: kcenon::logger::structured::basic_structured_logger Class Reference
kcenon::logger::structured::basic_structured_logger Class Reference
#include <structured_logger.h>
Public Member Functions
void set_format (structured_format format)
Set the output format.
void set_output_callback (structured_output_callback callback)
Set a custom output callback.
void set_output_to_stderr (bool use_stderr)
Set whether to output to stderr (default: stdout)
void log_structured (const structured_log_entry &entry) override
Log a structured message.
log_builder start_log (log_level level) override
Start building a structured log entry.
Public Member Functions inherited from kcenon::logger::structured::structured_logger_interface
virtual ~structured_logger_interface ()=default
Static Private Member Functions
static std::string format_logfmt (const structured_log_entry &entry)
Format entry in logfmt style (key=value pairs)
static std::string level_to_string (log_level level)
static std::string format_timestamp_logfmt (std::chrono::system_clock::time_point tp)
static std::string escape_logfmt_value (const std::string &value)
Private Attributes
structured_format format_ = structured_format::json
structured_output_callback output_callback_
bool output_to_stderr_ = false
Detailed Description
Definition at line 158 of file structured_logger.h.
Member Function Documentation
escape_logfmt_value()
static std::string kcenon::logger::structured::basic_structured_logger::escape_logfmt_value (const std::string & value) inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 271 of file structured_logger.h.
{
        // If value contains spaces, quotes, or special chars, quote it
        bool needs_quoting = false;
        for (char c : value) {
            if (c == ' ' || c == '"' || c == '=' || c == '\n' || c == '\t') {
                needs_quoting = true;
                break;
            }
        }
        if (!needs_quoting && !value.empty()) {
            return value;
        }
        // Quote and escape
        std::ostringstream oss;
        oss << '"';
        for (char c : value) {
            switch (c) {
                case '"': oss << "\\\""; break;
                case '\\': oss << "\\\\"; break;
                case '\n': oss << "\\n"; break;
                case '\t': oss << "\\t"; break;
                default: oss << c;
            }
        }
        oss << '"';
        return oss.str();
    }
Referenced by format_logfmt().
format_logfmt()
static std::string kcenon::logger::structured::basic_structured_logger::format_logfmt (const structured_log_entry & entry) inline static private
Format entry in logfmt style (key=value pairs)
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 218 of file structured_logger.h.
{
        std::ostringstream oss;
        // Standard fields first
        oss << "level=" << level_to_string(entry.level);
        oss << " ts=" << format_timestamp_logfmt(entry.timestamp);
        if (!entry.message.empty()) {
            oss << " msg=" << escape_logfmt_value(entry.message);
        }
        // Custom fields
        for (const auto& [key, value] : entry.fields) {
            oss << " " << key << "=";
            std::visit([&oss](const auto& v) {
                using T = std::decay_t<decltype(v)>;
                if constexpr (std::is_same_v<T, std::string>) {
                    oss << escape_logfmt_value(v);
                } else if constexpr (std::is_same_v<T, bool>) {
                    oss << (v ? "true" : "false");
                } else {
                    oss << v;
                }
            }, value);
        }
        return oss.str();
    }
References escape_logfmt_value(), kcenon::logger::structured::structured_log_entry::fields, format_timestamp_logfmt(), kcenon::logger::structured::structured_log_entry::level, level_to_string(), kcenon::logger::structured::structured_log_entry::message, and kcenon::logger::structured::structured_log_entry::timestamp.
Referenced by log_structured().
format_timestamp_logfmt()
static std::string kcenon::logger::structured::basic_structured_logger::format_timestamp_logfmt (std::chrono::system_clock::time_point tp) inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 260 of file structured_logger.h.
{
        auto time_t_val = std::chrono::system_clock::to_time_t(tp);
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
            tp.time_since_epoch()) % 1000;
        std::ostringstream oss;
        oss << std::put_time(std::gmtime(&time_t_val), "%Y-%m-%dT%H:%M:%S");
        oss << "." << std::setfill('0') << std::setw(3) << ms.count() << "Z";
        return oss.str();
    }
Referenced by format_logfmt().
level_to_string()
static std::string kcenon::logger::structured::basic_structured_logger::level_to_string (log_level level) inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 247 of file structured_logger.h.
{
        switch (level) {
            case log_level::trace: return "trace";
            case log_level::debug: return "debug";
            case log_level::info: return "info";
            case log_level::warning: return "warn";
            case log_level::error: return "error";
            case log_level::critical: return "fatal";
            case log_level::off: return "off";
            default: return "unknown";
        }
    }
Referenced by format_logfmt().
log_structured()
void kcenon::logger::structured::basic_structured_logger::log_structured (const structured_log_entry & entry) inline override virtual
Log a structured message.
Implements kcenon::logger::structured::structured_logger_interface.
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 189 of file structured_logger.h.
{
        std::string formatted;
        switch (format_) {
            case structured_format::json:
                formatted = json_formatter::format(entry);
                break;
            case structured_format::logfmt:
                formatted = format_logfmt(entry);
                break;
        }
        // Output the formatted log
        if (output_callback_) {
            output_callback_(entry.level, formatted);
        } else {
            auto& out = output_to_stderr_ ? std::cerr : std::cout;
            out << formatted << std::endl;
        }
    }
References kcenon::logger::structured::json_formatter::format(), format_, format_logfmt(), kcenon::logger::structured::json, kcenon::logger::structured::structured_log_entry::level, kcenon::logger::structured::logfmt, output_callback_, and output_to_stderr_.
set_format()
void kcenon::logger::structured::basic_structured_logger::set_format (structured_format format) inline
Set the output format.
Parameters
format The format to use (json or logfmt)
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 169 of file structured_logger.h.
{
        format_ = format;
    }
References format_.
set_output_callback()
void kcenon::logger::structured::basic_structured_logger::set_output_callback (structured_output_callback callback) inline
Set a custom output callback.
Parameters
callback Function to call with formatted log output
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 177 of file structured_logger.h.
{
        output_callback_ = std::move(callback);
    }
References output_callback_.
set_output_to_stderr()
void kcenon::logger::structured::basic_structured_logger::set_output_to_stderr (bool use_stderr) inline
Set whether to output to stderr (default: stdout)
Parameters
use_stderr If true, output to stderr; otherwise stdout
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 185 of file structured_logger.h.
{
        output_to_stderr_ = use_stderr;
    }
References output_to_stderr_.
start_log()
log_builder kcenon::logger::structured::basic_structured_logger::start_log (log_level level) inline override virtual
Start building a structured log entry.
Implements kcenon::logger::structured::structured_logger_interface.
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 210 of file structured_logger.h.
{
        return log_builder(level, this);
    }
Member Data Documentation
format_
structured_format kcenon::logger::structured::basic_structured_logger::format_ = structured_format::json private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 160 of file structured_logger.h.
Referenced by log_structured(), and set_format().
output_callback_
structured_output_callback kcenon::logger::structured::basic_structured_logger::output_callback_ private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 161 of file structured_logger.h.
Referenced by log_structured(), and set_output_callback().
output_to_stderr_
bool kcenon::logger::structured::basic_structured_logger::output_to_stderr_ = false private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 162 of file structured_logger.h.
Referenced by log_structured(), and set_output_to_stderr().
The documentation for this class was generated from the following file:
include/kcenon/logger/structured/structured_logger.h