Logger System: kcenon::logger::structured::json_formatter Class Reference
kcenon::logger::structured::json_formatter Class Reference
JSON formatter for structured logs.
#include <structured_logger.h>
Static Public Member Functions
static std::string format (const structured_log_entry &entry)
Static Private Member Functions
static std::string level_to_string (log_level level)
static std::string format_timestamp_iso8601 (std::chrono::system_clock::time_point tp)
static std::string escape_json_string (const std::string &s)
static std::string escape_json_key (const std::string &key)
Detailed Description
JSON formatter for structured logs.
Produces valid JSON output with proper escaping and ISO 8601 timestamps.
See also
basic_structured_logger
structured_log_entry
Definition at line 310 of file structured_logger.h.
Member Function Documentation
escape_json_key()
static std::string kcenon::logger::structured::json_formatter::escape_json_key (const std::string & key) inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 392 of file structured_logger.h.
{
        // Keys should be simple identifiers, but escape just in case
        std::string result;
        for (char c : key) {
            if (c == '"' || c == '\\') {
                result += '\\';
            }
            result += c;
        }
        return result;
    }
Referenced by format().
escape_json_string()
static std::string kcenon::logger::structured::json_formatter::escape_json_string (const std::string & s) inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 368 of file structured_logger.h.
{
        std::ostringstream oss;
        oss << '"';
        for (char c : s) {
            switch (c) {
                case '"': oss << "\\\""; break;
                case '\\': oss << "\\\\"; break;
                case '\b': oss << "\\b"; break;
                case '\f': oss << "\\f"; break;
                case '\n': oss << "\\n"; break;
                case '\r': oss << "\\r"; break;
                case '\t': oss << "\\t"; break;
                default:
                    if (static_cast<unsigned char>(c) < 0x20) {
                        oss << "\\u" << std::hex << std::setfill('0') << std::setw(4) << static_cast<int>(c);
                    } else {
                        oss << c;
                    }
            }
        }
        oss << '"';
        return oss.str();
    }
Referenced by format().
format()
static std::string kcenon::logger::structured::json_formatter::format (const structured_log_entry & entry) inline static
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 312 of file structured_logger.h.
{
        std::ostringstream json;
        json << "{";
        json << "\"timestamp\":\"" << format_timestamp_iso8601(entry.timestamp) << "\",";
        json << "\"level\":\"" << level_to_string(entry.level) << "\",";
        json << "\"message\":" << escape_json_string(entry.message);
        // Add custom fields
        for (const auto& [key, value] : entry.fields) {
            json << ",\"" << escape_json_key(key) << "\":";
            std::visit([&json](const auto& v) {
                using T = std::decay_t<decltype(v)>;
                if constexpr (std::is_same_v<T, std::string>) {
                    json << escape_json_string(v);
                } else if constexpr (std::is_same_v<T, bool>) {
                    json << (v ? "true" : "false");
                } else if constexpr (std::is_same_v<T, int>) {
                    json << v;
                } else if constexpr (std::is_same_v<T, double>) {
                    json << std::fixed << std::setprecision(6) << v;
                } else {
                    json << v;
                }
            }, value);
        }
        json << "}";
        return json.str();
    }
References escape_json_key(), escape_json_string(), kcenon::logger::structured::structured_log_entry::fields, format_timestamp_iso8601(), kcenon::logger::structured::json, kcenon::logger::structured::structured_log_entry::level, level_to_string(), kcenon::logger::structured::structured_log_entry::message, and kcenon::logger::structured::structured_log_entry::timestamp.
Referenced by kcenon::logger::structured::basic_structured_logger::log_structured().
format_timestamp_iso8601()
static std::string kcenon::logger::structured::json_formatter::format_timestamp_iso8601 (std::chrono::system_clock::time_point tp) inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 357 of file structured_logger.h.
{
        auto time_t_val = std::chrono::system_clock::to_time_t(tp);
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
            tp.time_since_epoch()) % 1000;
        std::ostringstream oss;
        oss << std::put_time(std::gmtime(&time_t_val), "%Y-%m-%dT%H:%M:%S");
        oss << "." << std::setfill('0') << std::setw(3) << ms.count() << "Z";
        return oss.str();
    }
Referenced by format().
level_to_string()
static std::string kcenon::logger::structured::json_formatter::level_to_string (log_level level) inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/structured/structured_logger.h.
Definition at line 344 of file structured_logger.h.
{
        switch (level) {
            case log_level::trace: return "TRACE";
            case log_level::debug: return "DEBUG";
            case log_level::info: return "INFO";
            case log_level::warning: return "WARN";
            case log_level::error: return "ERROR";
            case log_level::critical: return "FATAL";
            case log_level::off: return "OFF";
            default: return "UNKNOWN";
        }
    }
Referenced by format().
The documentation for this class was generated from the following file:
include/kcenon/logger/structured/structured_logger.h