Logger System: logger_module::health_check_result Class Reference
logger_module::health_check_result Class Reference
Health check result.
#include <monitoring_interface.h>
Public Member Functions
health_check_result (health_status status=health_status::healthy)
void set_status (health_status status)
Set health status.
health_status get_status () const
Get health status.
void add_issue (const std::string &issue)
Add an issue.
const std::vector< std::string > & get_issues () const
Get all issues.
void set_message (const std::string &message)
Set status message.
const std::string & get_message () const
Get status message.
bool is_healthy () const
Check if healthy.
std::chrono::system_clock::time_point get_check_time () const
Get check timestamp.
Detailed Description
Health check result.
Definition at line 130 of file monitoring_interface.h.
Constructor & Destructor Documentation
health_check_result()
logger_module::health_check_result::health_check_result (health_status status = health_status::healthy) inline
Definition at line 138 of file monitoring_interface.h.
Member Function Documentation
add_issue()
void logger_module::health_check_result::add_issue (const std::string & issue) inline
Add an issue.
Parameters
issue Description of the issue
Definition at line 161 of file monitoring_interface.h.
References logger_module::degraded, and logger_module::healthy.
Referenced by logger_module::basic_monitor::check_health(), logger_module::thread_system_monitor_adapter::check_health(), and logger_module::health_check_system::impl::perform_health_check().
get_check_time()
std::chrono::system_clock::time_point logger_module::health_check_result::get_check_time () const inline
Get check timestamp.
Returns
Time when health check was performed
Definition at line 205 of file monitoring_interface.h.
Referenced by logger_module::health_check_utils::format_as_json().
get_issues()
const std::vector< std::string > & logger_module::health_check_result::get_issues () const inline
Get all issues.
Returns
Vector of issue descriptions
Definition at line 173 of file monitoring_interface.h.
Referenced by logger_module::health_check_utils::format_as_json().
get_message()
const std::string & logger_module::health_check_result::get_message () const inline
Get status message.
Returns
Status message
Definition at line 189 of file monitoring_interface.h.
Referenced by logger_module::health_check_utils::format_as_json().
get_status()
health_status logger_module::health_check_result::get_status () const inline
Get health status.
Returns
Current health status
Definition at line 153 of file monitoring_interface.h.
Referenced by logger_module::basic_monitor::check_health(), logger_module::thread_system_monitor_adapter::check_health(), logger_module::health_check_utils::format_as_json(), and logger_module::health_check_system::impl::perform_health_check().
is_healthy()
bool logger_module::health_check_result::is_healthy () const inline
Check if healthy.
Returns
true if status is healthy
Definition at line 197 of file monitoring_interface.h.
References logger_module::healthy.
Referenced by logger_module::basic_monitor::check_health(), and logger_module::thread_system_monitor_adapter::check_health().
set_message()
void logger_module::health_check_result::set_message (const std::string & message) inline
Set status message.
Parameters
message Status message
Definition at line 181 of file monitoring_interface.h.
Referenced by logger_module::basic_monitor::check_health(), logger_module::thread_system_monitor_adapter::check_health(), and logger_module::health_check_system::impl::perform_health_check().
set_status()
void logger_module::health_check_result::set_status (health_status status) inline
Set health status.
Parameters
status The health status
Definition at line 145 of file monitoring_interface.h.
Referenced by logger_module::basic_monitor::check_health(), logger_module::thread_system_monitor_adapter::check_health(), and logger_module::health_check_system::impl::perform_health_check().
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/monitoring/monitoring_interface.h