Logger System: kcenon::common::VoidResult Class Reference
kcenon::common::VoidResult Class Reference
#include <error_codes.h>
Public Member Functions
VoidResult ()=default
VoidResult (error_info info)
bool has_value () const
bool has_error () const
error_info & error ()
const error_info & error () const
Private Attributes
std::optional< error_info > error_
Detailed Description
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h, /home/runner/work/logger_system/logger_system/include/kcenon/logger/core/logger.h, /home/runner/work/logger_system/logger_system/include/kcenon/logger/core/logger_builder.h, /home/runner/work/logger_system/logger_system/include/kcenon/logger/writers/base_writer.h, /home/runner/work/logger_system/logger_system/include/kcenon/logger/writers/composite_writer.h, /home/runner/work/logger_system/logger_system/include/kcenon/logger/writers/critical_writer.h, /home/runner/work/logger_system/logger_system/include/kcenon/logger/writers/encrypted_writer.h, Implementing, custom_writer_example.cpp, di_pattern_example.cpp, and monitoring_integration_example.cpp.
Definition at line 116 of file error_codes.h.
Constructor & Destructor Documentation
VoidResult() [1/2]
kcenon::common::VoidResult::VoidResult () default
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
VoidResult() [2/2]
kcenon::common::VoidResult::VoidResult (error_info info) inline explicit
Definition at line 120 of file error_codes.h.
        : error_(std::move(info)) {}
Member Function Documentation
error() [1/2]
error_info & kcenon::common::VoidResult::error () inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 126 of file error_codes.h.
{
        if (!error_) {
            throw std::logic_error("VoidResult does not contain an error");
        }
        return *error_;
    }
References error_.
Referenced by kcenon::common::get_error().
error() [2/2]
const error_info & kcenon::common::VoidResult::error () const inline
Definition at line 133 of file error_codes.h.
{
        if (!error_) {
            throw std::logic_error("VoidResult does not contain an error");
        }
        return *error_;
    }
References error_.
has_error()
bool kcenon::common::VoidResult::has_error () const inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 124 of file error_codes.h.
{ return error_.has_value(); }
References error_.
Referenced by kcenon::common::is_error(), and kcenon::common::is_ok().
has_value()
bool kcenon::common::VoidResult::has_value () const inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 123 of file error_codes.h.
{ return !error_.has_value(); }
References error_.
Member Data Documentation
error_
std::optional<error_info> kcenon::common::VoidResult::error_ private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 141 of file error_codes.h.
Referenced by error(), error(), has_error(), and has_value().
The documentation for this class was generated from the following file:
include/kcenon/logger/core/error_codes.h