Logger System: logger_module::rotating_file_writer Class Reference
logger_module::rotating_file_writer Class Reference
File writer with rotation support based on size or time.
#include <rotating_file_writer.h>
Public Types
enum class rotation_type { size , daily , hourly , size_and_time }
Type of rotation strategy.
Public Member Functions
rotating_file_writer (const std::string &filename, size_t max_size, size_t max_files=10)
Constructor for size-based rotation.
rotating_file_writer (const std::string &filename, rotation_type type, size_t max_files=10)
Constructor for time-based rotation.
rotating_file_writer (const std::string &filename, rotation_type type, size_t max_size, size_t max_files=10)
Constructor for combined rotation.
~rotating_file_writer () override=default
Destructor.
result_void write (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write with rotation check.
std::string get_name () const override
Get writer name.
void rotate ()
Force rotation.
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
result_void flush () override
Flush file buffer.
bool is_open () const
Check if file is open.
size_t get_file_size () const
Get current file size.
result_void reopen ()
Reopen the file.
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
virtual bool is_healthy () const override
Check if the writer is healthy and operational.
Protected Member Functions
bool should_rotate () const
Check if rotation is needed.
void perform_rotation ()
Perform rotation.
std::string generate_rotated_filename (int index=-1) const
Generate rotated filename.
void cleanup_old_files ()
Clean up old files.
std::vector< std::string > get_backup_files () const
Get list of existing backup files.
bool should_rotate_by_time () const
Check if time-based rotation is needed.
void close ()
Close the current file.
result_void open ()
Open the file.
std::string format_log_entry (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (thread_module::log_level level) const
Convert log level to string representation.
std::string level_to_color (thread_module::log_level level) const
Get ANSI color code for the specified log level.
Protected Attributes
std::string filename_
bool append_mode_
size_t buffer_size_
std::ofstream file_stream_
std::unique_ptr< char[]> buffer_
std::mutex write_mutex_
std::atomic< size_t > bytes_written_ {0}
Detailed Description
File writer with rotation support based on size or time.
Definition at line 21 of file rotating_file_writer.h.
Member Enumeration Documentation
rotation_type
enum class logger_module::rotating_file_writer::rotation_type strong
Type of rotation strategy.
Enumerator
size
daily
hourly
size_and_time
Definition at line 27 of file rotating_file_writer.h.
Constructor & Destructor Documentation
rotating_file_writer() [1/3]
logger_module::rotating_file_writer::rotating_file_writer (const std::string & filename, size_t max_size, size_t max_files = 10)
Constructor for size-based rotation.
Parameters
filename Base filename (will be appended with number/date)
max_size Maximum file size in bytes before rotation
max_files Maximum number of backup files to keep
Definition at line 17 of file rotating_file_writer.cpp.
rotating_file_writer() [2/3]
logger_module::rotating_file_writer::rotating_file_writer (const std::string & filename, rotation_type type, size_t max_files = 10)
Constructor for time-based rotation.
Parameters
filename Base filename (will be appended with date/time)
type Rotation type (daily or hourly)
max_files Maximum number of backup files to keep
Definition at line 36 of file rotating_file_writer.cpp.
rotating_file_writer() [3/3]
logger_module::rotating_file_writer::rotating_file_writer (const std::string & filename, rotation_type type, size_t max_size, size_t max_files = 10)
Constructor for combined rotation.
Parameters
filename Base filename
type Must be size_and_time
max_size Maximum file size
max_files Maximum number of backup files
Definition at line 55 of file rotating_file_writer.cpp.
References size_and_time.
~rotating_file_writer()
logger_module::rotating_file_writer::~rotating_file_writer () override default
Destructor.
Member Function Documentation
cleanup_old_files()
void logger_module::rotating_file_writer::cleanup_old_files () protected
Clean up old files.
Definition at line 187 of file rotating_file_writer.cpp.
References get_backup_files().
Referenced by perform_rotation().
close()
void logger_module::file_writer::close () protected inherited
Close the current file.
Definition at line 74 of file file_writer.cpp.
References logger_module::file_writer::file_stream_.
Referenced by perform_rotation(), logger_module::file_writer::reopen(), and logger_module::file_writer::~file_writer().
flush()
result_void logger_module::file_writer::flush () override virtual inherited
Flush file buffer.
Implements logger_module::base_writer.
Definition at line 56 of file file_writer.cpp.
References logger_module::file_writer::file_stream_, logger_module::flush_timeout, logger_module::make_logger_error(), and logger_module::file_writer::write_mutex_.
format_log_entry()
std::string logger_module::base_writer::format_log_entry (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) protected inherited
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 131 of file console_writer.cpp.
References logger_module::base_writer::level_to_string().
Referenced by logger_module::console_writer::write(), logger_module::encrypted_writer::write(), and logger_module::file_writer::write().
generate_rotated_filename()
std::string logger_module::rotating_file_writer::generate_rotated_filename (int index = -1) const protected
Generate rotated filename.
Definition at line 142 of file rotating_file_writer.cpp.
References daily, logger_module::file_writer::filename_, hourly, size, and size_and_time.
Referenced by perform_rotation().
get_backup_files()
std::vector< std::string > logger_module::rotating_file_writer::get_backup_files () const protected
Get list of existing backup files.
Definition at line 210 of file rotating_file_writer.cpp.
References logger_module::file_writer::filename_.
Referenced by cleanup_old_files().
get_file_size()
size_t logger_module::file_writer::get_file_size () const inline inherited
Get current file size.
Definition at line 67 of file file_writer.h.
References logger_module::file_writer::bytes_written_.
Referenced by should_rotate().
get_name()
std::string logger_module::rotating_file_writer::get_name () const inline override virtual
Get writer name.
Reimplemented from logger_module::file_writer.
Definition at line 84 of file rotating_file_writer.h.
is_healthy()
virtual bool logger_module::base_writer::is_healthy () const inline override virtual inherited
Check if the writer is healthy and operational.
Returns
true if the writer is functioning correctly, false otherwise
Used for health monitoring and automatic failover. A writer might be unhealthy if its destination is unavailable (e.g., disk full, network disconnected).
Note
Default implementation always returns true. Override for writers that can detect failure conditions.
Since
1.0.0
Implements logger_module::log_writer_interface.
Reimplemented in logger_module::async_writer, and logger_module::batch_writer.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 249 of file base_writer.h.
is_open()
bool logger_module::file_writer::is_open () const inline inherited
Check if file is open.
Definition at line 62 of file file_writer.h.
References logger_module::file_writer::file_stream_.
level_to_color()
std::string logger_module::base_writer::level_to_color (thread_module::log_level level) const protected inherited
Get ANSI color code for the specified log level.
Parameters
level Log level to get color for
Returns
ANSI escape sequence for color, or empty string if color is disabled
Returns appropriate ANSI color codes for terminal output:
trace -> Gray/Dim
debug -> Cyan
info -> Green
warning -> Yellow
error -> Red
Note
Returns empty string if use_color() is false.
Warning
Only use for terminals that support ANSI escape codes.
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 170 of file console_writer.cpp.
References logger_module::base_writer::use_color().
Referenced by logger_module::console_writer::write().
level_to_string()
std::string logger_module::base_writer::level_to_string (thread_module::log_level level) const protected inherited
Convert log level to string representation.
Parameters
level Log level to convert
Returns
String representation of the level
Maps log levels to human-readable strings:
trace -> "TRACE"
debug -> "DEBUG"
info -> "INFO"
warning -> "WARNING"
error -> "ERROR"
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 158 of file console_writer.cpp.
Referenced by logger_module::base_writer::format_log_entry().
open()
result_void logger_module::file_writer::open () protected inherited
Open the file.
Definition at line 81 of file file_writer.cpp.
References logger_module::file_writer::append_mode_, logger_module::file_writer::buffer_, logger_module::file_writer::buffer_size_, logger_module::file_writer::bytes_written_, logger_module::file_open_failed, logger_module::file_permission_denied, logger_module::file_writer::file_stream_, logger_module::file_writer::filename_, and logger_module::make_logger_error().
Referenced by logger_module::file_writer::file_writer(), perform_rotation(), and logger_module::file_writer::reopen().
perform_rotation()
void logger_module::rotating_file_writer::perform_rotation () protected
Perform rotation.
Definition at line 115 of file rotating_file_writer.cpp.
References cleanup_old_files(), logger_module::file_writer::close(), logger_module::file_writer::filename_, generate_rotated_filename(), and logger_module::file_writer::open().
Referenced by rotate().
reopen()
result_void logger_module::file_writer::reopen () inherited
Reopen the file.
Definition at line 68 of file file_writer.cpp.
References logger_module::file_writer::close(), logger_module::file_writer::open(), and logger_module::file_writer::write_mutex_.
rotate()
void logger_module::rotating_file_writer::rotate ()
Force rotation.
Definition at line 93 of file rotating_file_writer.cpp.
References perform_rotation(), and logger_module::file_writer::write_mutex_.
Referenced by write().
set_use_color()
virtual void logger_module::base_writer::set_use_color (bool use_color) inline virtual inherited
Set whether to use color output (if supported)
Parameters
use_color true to enable color output, false to disable
Enables or disables ANSI color codes in formatted output. Only affects writers that output to terminals supporting color.
Note
Has no effect on writers that don't support color (e.g., file writers).
Since
1.0.0
Reimplemented in logger_module::async_writer.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 209 of file base_writer.h.
References logger_module::base_writer::use_color().
Referenced by logger_module::console_writer::console_writer().
should_rotate()
bool logger_module::rotating_file_writer::should_rotate () const protected
Check if rotation is needed.
Definition at line 98 of file rotating_file_writer.cpp.
References daily, logger_module::file_writer::get_file_size(), hourly, should_rotate_by_time(), size, and size_and_time.
Referenced by write().
should_rotate_by_time()
bool logger_module::rotating_file_writer::should_rotate_by_time () const protected
Check if time-based rotation is needed.
Definition at line 238 of file rotating_file_writer.cpp.
References daily, hourly, and size_and_time.
Referenced by should_rotate().
use_color()
bool logger_module::base_writer::use_color () const inline inherited
Get current color output setting.
Returns
true if color output is enabled, false otherwise
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 219 of file base_writer.h.
Referenced by logger_module::base_writer::level_to_color(), logger_module::base_writer::set_use_color(), logger_module::async_writer::set_use_color(), and logger_module::console_writer::write().
write() [1/2]
virtual result_void logger_module::base_writer::write (const log_entry & entry) inline override virtual inherited
Write a log entry using the new interface.
Parameters
entry The log entry to write
Returns
result_void Success or error code
This method provides compatibility with the modern log_entry structure. The default implementation converts the entry to the legacy API format for backward compatibility. Derived classes can override this for optimized handling.
Note
This method extracts source location information if present in the entry.
Since
1.0.0
Implements logger_module::log_writer_interface.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 140 of file base_writer.h.
References logger_module::log_entry::level, logger_module::log_entry::location, logger_module::log_entry::message, logger_module::log_entry::timestamp, and logger_module::base_writer::write().
Referenced by logger_module::base_writer::write().
write() [2/2]
result_void logger_module::rotating_file_writer::write (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write with rotation check.
Reimplemented from logger_module::file_writer.
Definition at line 79 of file rotating_file_writer.cpp.
References rotate(), should_rotate(), and logger_module::file_writer::write().
Member Data Documentation
append_mode_
bool logger_module::file_writer::append_mode_ protected inherited
Definition at line 87 of file file_writer.h.
Referenced by logger_module::file_writer::open().
buffer_
std::unique_ptr<char[]> logger_module::file_writer::buffer_ protected inherited
Definition at line 91 of file file_writer.h.
Referenced by logger_module::file_writer::open().
buffer_size_
size_t logger_module::file_writer::buffer_size_ protected inherited
Definition at line 88 of file file_writer.h.
Referenced by logger_module::file_writer::open().
bytes_written_
std::atomic<size_t> logger_module::file_writer::bytes_written_ {0} protected inherited
Definition at line 94 of file file_writer.h.
Referenced by logger_module::file_writer::get_file_size(), logger_module::file_writer::open(), and logger_module::file_writer::write().
file_stream_
std::ofstream logger_module::file_writer::file_stream_ protected inherited
Definition at line 90 of file file_writer.h.
Referenced by logger_module::file_writer::close(), logger_module::file_writer::flush(), logger_module::file_writer::is_open(), logger_module::file_writer::open(), and logger_module::file_writer::write().
filename_
std::string logger_module::file_writer::filename_ protected inherited
Definition at line 86 of file file_writer.h.
Referenced by generate_rotated_filename(), get_backup_files(), logger_module::file_writer::open(), and perform_rotation().
write_mutex_
std::mutex logger_module::file_writer::write_mutex_ mutable protected inherited
Definition at line 92 of file file_writer.h.
Referenced by logger_module::file_writer::flush(), logger_module::file_writer::reopen(), rotate(), and logger_module::file_writer::write().
The documentation for this class was generated from the following files:
/home/runner/work/logger_system/logger_system/sources/logger/writers/rotating_file_writer.h
/home/runner/work/logger_system/logger_system/sources/logger/writers/rotating_file_writer.cpp