Logger System: logger_module::async_writer Class Reference
logger_module::async_writer Class Reference
Asynchronous wrapper for log writers.
#include <async_writer.h>
Public Member Functions
async_writer (std::unique_ptr< base_writer > wrapped_writer, std::size_t queue_size=10000)
Constructor.
~async_writer () override
Destructor.
void start ()
Start the async writer thread.
void stop ()
Stop the async writer thread.
result_void write (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write a log message asynchronously.
result_void flush () override
Flush all pending messages.
bool is_healthy () const override
Check if the writer is healthy.
std::string get_name () const override
Get the name of this writer.
void set_use_color (bool use_color) override
Set whether to use color output.
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
bool use_color () const
Get current color output setting.
Protected Member Functions
std::string format_log_entry (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (thread_module::log_level level) const
Convert log level to string representation.
std::string level_to_color (thread_module::log_level level) const
Get ANSI color code for the specified log level.
Detailed Description
Asynchronous wrapper for log writers.
This class wraps any base_writer implementation and provides asynchronous writing capabilities using a background thread.
Definition at line 35 of file async_writer.h.
Constructor & Destructor Documentation
async_writer()
logger_module::async_writer::async_writer (std::unique_ptr< base_writer > wrapped_writer, std::size_t queue_size = 10000) inline explicit
Constructor.
Parameters
wrapped_writer The writer to wrap with async functionality
queue_size Maximum queue size for pending messages
Definition at line 42 of file async_writer.h.
~async_writer()
logger_module::async_writer::~async_writer () inline override
Destructor.
Definition at line 55 of file async_writer.h.
References stop().
Member Function Documentation
flush()
result_void logger_module::async_writer::flush () inline override virtual
Flush all pending messages.
Returns
result_void indicating success or error
Implements logger_module::base_writer.
Definition at line 137 of file async_writer.h.
format_log_entry()
std::string logger_module::base_writer::format_log_entry (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) protected inherited
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 131 of file console_writer.cpp.
References logger_module::base_writer::level_to_string().
Referenced by logger_module::console_writer::write(), logger_module::encrypted_writer::write(), and logger_module::file_writer::write().
get_name()
std::string logger_module::async_writer::get_name () const inline override virtual
Get the name of this writer.
Returns
Writer name
Implements logger_module::base_writer.
Definition at line 164 of file async_writer.h.
is_healthy()
bool logger_module::async_writer::is_healthy () const inline override virtual
Check if the writer is healthy.
Returns
true if healthy, false otherwise
Reimplemented from logger_module::base_writer.
Definition at line 156 of file async_writer.h.
level_to_color()
std::string logger_module::base_writer::level_to_color (thread_module::log_level level) const protected inherited
Get ANSI color code for the specified log level.
Parameters
level Log level to get color for
Returns
ANSI escape sequence for color, or empty string if color is disabled
Returns appropriate ANSI color codes for terminal output:
trace -> Gray/Dim
debug -> Cyan
info -> Green
warning -> Yellow
error -> Red
Note
Returns empty string if use_color() is false.
Warning
Only use for terminals that support ANSI escape codes.
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 170 of file console_writer.cpp.
References logger_module::base_writer::use_color().
Referenced by logger_module::console_writer::write().
level_to_string()
std::string logger_module::base_writer::level_to_string (thread_module::log_level level) const protected inherited
Convert log level to string representation.
Parameters
level Log level to convert
Returns
String representation of the level
Maps log levels to human-readable strings:
trace -> "TRACE"
debug -> "DEBUG"
info -> "INFO"
warning -> "WARNING"
error -> "ERROR"
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 158 of file console_writer.cpp.
Referenced by logger_module::base_writer::format_log_entry().
set_use_color()
void logger_module::async_writer::set_use_color (bool use_color) inline override virtual
Set whether to use color output.
Parameters
use_color Enable/disable color output
Reimplemented from logger_module::base_writer.
Definition at line 172 of file async_writer.h.
References logger_module::base_writer::use_color().
start()
void logger_module::async_writer::start () inline
Start the async writer thread.
Definition at line 62 of file async_writer.h.
stop()
void logger_module::async_writer::stop () inline
Stop the async writer thread.
Definition at line 75 of file async_writer.h.
Referenced by ~async_writer().
use_color()
bool logger_module::base_writer::use_color () const inline inherited
Get current color output setting.
Returns
true if color output is enabled, false otherwise
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 219 of file base_writer.h.
Referenced by logger_module::base_writer::level_to_color(), logger_module::base_writer::set_use_color(), set_use_color(), and logger_module::console_writer::write().
write() [1/2]
virtual result_void logger_module::base_writer::write (const log_entry & entry) inline override virtual inherited
Write a log entry using the new interface.
Parameters
entry The log entry to write
Returns
result_void Success or error code
This method provides compatibility with the modern log_entry structure. The default implementation converts the entry to the legacy API format for backward compatibility. Derived classes can override this for optimized handling.
Note
This method extracts source location information if present in the entry.
Since
1.0.0
Implements logger_module::log_writer_interface.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 140 of file base_writer.h.
References logger_module::log_entry::level, logger_module::log_entry::location, logger_module::log_entry::message, logger_module::log_entry::timestamp, and logger_module::base_writer::write().
Referenced by logger_module::base_writer::write().
write() [2/2]
result_void logger_module::async_writer::write (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) inline override virtual
Write a log message asynchronously.
Parameters
level Log level
message Log message
file Source file
line Source line
function Function name
timestamp Timestamp
Returns
result_void indicating success or error
Implements logger_module::base_writer.
Definition at line 105 of file async_writer.h.
References logger_module::make_logger_error(), and logger_module::queue_full.
The documentation for this class was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/writers/async_writer.h