Logger System: kcenon::logger::plain_formatter Class Reference
kcenon::logger::plain_formatter Class Reference
Simple plain text formatter.
#include <base_formatter.h>
Public Member Functions
std::string format (const log_entry &entry) const override
Format a log entry into a string.
std::string get_format_type () const override
Public Member Functions inherited from kcenon::logger::base_formatter
virtual ~base_formatter ()=default
Public Member Functions inherited from kcenon::logger::log_formatter_interface
virtual ~log_formatter_interface ()=default
virtual void set_options (const format_options &opts)
Set formatting options.
virtual format_options get_options () const
Get current formatting options.
virtual std::string get_name () const =0
Additional Inherited Members
Protected Member Functions inherited from kcenon::logger::base_formatter
std::string level_to_string (log_level level) const
Convert log level to string.
std::string format_timestamp (const std::chrono::system_clock::time_point &timestamp) const
Format timestamp to ISO8601 string.
std::string get_thread_id () const
Get current thread ID as string.
Protected Attributes inherited from kcenon::logger::log_formatter_interface
format_options options_
Detailed Description
Simple plain text formatter.
Definition at line 87 of file base_formatter.h.
Member Function Documentation
format()
std::string kcenon::logger::plain_formatter::format (const log_entry & entry) const inline override virtual
Format a log entry into a string.
Parameters
entry The log entry to format
Returns
Formatted string representation
Implements kcenon::logger::base_formatter.
Definition at line 89 of file base_formatter.h.
{
        std::ostringstream oss;
        // Format: [TIMESTAMP] [LEVEL] [THREAD] MESSAGE [FILE:LINE:FUNCTION]
        oss << "[" << format_timestamp(entry.timestamp) << "] ";
        oss << "[" << level_to_string(entry.level) << "] ";
        if (entry.thread_id) {
            oss << "[" << std::string_view(*entry.thread_id) << "] ";
        } else {
            oss << "[" << get_thread_id() << "] ";
        }
        oss << std::string_view(entry.message);
        if (entry.location) {
            oss << " [" << std::string_view(entry.location->file)
                << ":" << entry.location->line
                << ":" << std::string_view(entry.location->function) << "]";
        }
        return oss.str();
    }
References kcenon::logger::base_formatter::format_timestamp(), kcenon::logger::base_formatter::get_thread_id(), kcenon::logger::log_entry::level, kcenon::logger::base_formatter::level_to_string(), kcenon::logger::log_entry::location, kcenon::logger::log_entry::message, kcenon::logger::log_entry::thread_id, and kcenon::logger::log_entry::timestamp.
get_format_type()
std::string kcenon::logger::plain_formatter::get_format_type () const inline override
Definition at line 113 of file base_formatter.h.
{
        return "plain";
    }
The documentation for this class was generated from the following file:
include/kcenon/logger/formatters/base_formatter.h