Logger System: kcenon::logger::security::critical_logger_interface Interface Reference
kcenon::logger::security::critical_logger_interface Interface Reference abstract
Interface for loggers that support emergency flushing.
#include <signal_manager.h>
Public Member Functions
virtual ~critical_logger_interface ()=default
virtual int get_emergency_fd () const =0
Get file descriptor for emergency writing.
virtual const char * get_emergency_buffer () const =0
Get emergency buffer pointer.
virtual size_t get_emergency_buffer_size () const =0
Get emergency buffer size.
Detailed Description
Interface for loggers that support emergency flushing.
Definition at line 314 of file signal_manager.h.
Constructor & Destructor Documentation
~critical_logger_interface()
virtual kcenon::logger::security::critical_logger_interface::~critical_logger_interface () virtual default
Member Function Documentation
get_emergency_buffer()
virtual const char * kcenon::logger::security::critical_logger_interface::get_emergency_buffer () const pure virtual
Get emergency buffer pointer.
Returns
Pointer to buffer or nullptr
This method must be signal-safe
Implemented in kcenon::logger::logger.
Referenced by kcenon::logger::security::signal_manager::emergency_flush().
get_emergency_buffer_size()
virtual size_t kcenon::logger::security::critical_logger_interface::get_emergency_buffer_size () const pure virtual
Get emergency buffer size.
Returns
Buffer size in bytes
This method must be signal-safe
Implemented in kcenon::logger::logger.
Referenced by kcenon::logger::security::signal_manager::emergency_flush().
get_emergency_fd()
virtual int kcenon::logger::security::critical_logger_interface::get_emergency_fd () const pure virtual
Get file descriptor for emergency writing.
Returns
File descriptor or -1 if not available
This method must be signal-safe (no allocations, no locks)
Implemented in kcenon::logger::logger.
Referenced by kcenon::logger::security::signal_manager::emergency_flush().
The documentation for this interface was generated from the following file:
include/kcenon/logger/security/signal_manager.h