Logger System: kcenon::logger::log_context_storage Class Reference
kcenon::logger::log_context_storage Class Reference
Thread-local storage for structured logging context fields.
#include <log_context_scope.h>
Static Public Member Functions
static void set (const std::string &key, const std::string &value)
Set a string context field for the current thread.
static void set (const std::string &key, const char *value)
Set a C-string context field for the current thread.
static void set (const std::string &key, int64_t value)
Set an integer context field for the current thread.
static void set (const std::string &key, double value)
Set a double context field for the current thread.
static void set (const std::string &key, bool value)
Set a boolean context field for the current thread.
static void set (const std::string &key, const log_value &value)
Set a log_value context field for the current thread.
static void set_all (const log_fields &fields)
Set multiple context fields at once.
static void remove (const std::string &key)
Remove a context field for the current thread.
static log_fields get ()
Get all context fields for the current thread.
static void clear ()
Clear all context fields for the current thread.
static bool has_context ()
Check if any context fields are set for the current thread.
static std::optional< log_value > get_field (const std::string &key)
Get a specific field value if it exists.
Static Private Member Functions
static log_fields & get_storage ()
static bool & get_has_context ()
Detailed Description
Thread-local storage for structured logging context fields.
Provides thread-safe storage and retrieval of context fields using thread-local storage. This allows automatic context propagation within a thread without affecting other threads.
Thread-local context takes precedence over logger-level context when both are set. Fields are merged with thread-local fields overriding logger-level fields with the same key.
Definition at line 75 of file log_context_scope.h.
Member Function Documentation
clear()
static void kcenon::logger::log_context_storage::clear () inline static
Clear all context fields for the current thread.
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 175 of file log_context_scope.h.
{
        get_storage().clear();
        get_has_context() = false;
    }
References get_has_context(), and get_storage().
get()
static log_fields kcenon::logger::log_context_storage::get () inline static nodiscard
Get all context fields for the current thread.
Returns
Copy of context fields, empty if not set
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 165 of file log_context_scope.h.
{
        if (get_has_context()) {
            return get_storage();
        }
        return {};
    }
References get_has_context(), and get_storage().
get_field()
static std::optional< log_value > kcenon::logger::log_context_storage::get_field (const std::string & key) inline static nodiscard
Get a specific field value if it exists.
Parameters
key Field name
Returns
Optional field value
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 193 of file log_context_scope.h.
{
        if (!get_has_context()) {
            return std::nullopt;
        }
        auto& storage = get_storage();
        auto it = storage.find(key);
        if (it != storage.end()) {
            return it->second;
        }
        return std::nullopt;
    }
References get_has_context(), and get_storage().
Referenced by kcenon::logger::scoped_context::scoped_context(), kcenon::logger::scoped_context::scoped_context(), kcenon::logger::scoped_context::scoped_context(), and kcenon::logger::scoped_context::scoped_context().
get_has_context()
static bool & kcenon::logger::log_context_storage::get_has_context () inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 211 of file log_context_scope.h.
{
        thread_local bool has_ctx = false;
        return has_ctx;
    }
Referenced by clear(), get(), get_field(), has_context(), remove(), set(), set(), set(), set(), set(), set(), and set_all().
get_storage()
static log_fields & kcenon::logger::log_context_storage::get_storage () inline static private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 206 of file log_context_scope.h.
{
        thread_local log_fields storage;
        return storage;
    }
Referenced by clear(), get(), get_field(), remove(), set(), set(), set(), set(), set(), set(), and set_all().
has_context()
static bool kcenon::logger::log_context_storage::has_context () inline static nodiscard
Check if any context fields are set for the current thread.
Returns
true if context is set
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 184 of file log_context_scope.h.
{
        return get_has_context();
    }
References get_has_context().
remove()
static void kcenon::logger::log_context_storage::remove (const std::string & key) inline static
Remove a context field for the current thread.
Parameters
key Field name to remove
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 154 of file log_context_scope.h.
{
        get_storage().erase(key);
        if (get_storage().empty()) {
            get_has_context() = false;
        }
    }
References get_has_context(), and get_storage().
Referenced by kcenon::logger::scoped_context::~scoped_context().
set() [1/6]
static void kcenon::logger::log_context_storage::set (const std::string & key, bool value) inline static
Set a boolean context field for the current thread.
Parameters
key Field name
value Field value
Definition at line 122 of file log_context_scope.h.
{
        get_storage()[key] = value;
        get_has_context() = true;
    }
References get_has_context(), and get_storage().
set() [2/6]
static void kcenon::logger::log_context_storage::set (const std::string & key, const char * value) inline static
Set a C-string context field for the current thread.
Parameters
key Field name
value Field value (will be converted to std::string)
Definition at line 92 of file log_context_scope.h.
{
        get_storage()[key] = std::string(value);
        get_has_context() = true;
    }
References get_has_context(), and get_storage().
set() [3/6]
static void kcenon::logger::log_context_storage::set (const std::string & key, const log_value & value) inline static
Set a log_value context field for the current thread.
Parameters
key Field name
value Field value
Definition at line 132 of file log_context_scope.h.
{
        get_storage()[key] = value;
        get_has_context() = true;
    }
References get_has_context(), and get_storage().
set() [4/6]
static void kcenon::logger::log_context_storage::set (const std::string & key, const std::string & value) inline static
Set a string context field for the current thread.
Parameters
key Field name
value Field value
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 82 of file log_context_scope.h.
{
        get_storage()[key] = value;
        get_has_context() = true;
    }
References get_has_context(), and get_storage().
Referenced by kcenon::logger::log_context_scope::log_context_scope(), kcenon::logger::scoped_context::scoped_context(), kcenon::logger::scoped_context::scoped_context(), kcenon::logger::scoped_context::scoped_context(), kcenon::logger::scoped_context::scoped_context(), and kcenon::logger::scoped_context::~scoped_context().
set() [5/6]
static void kcenon::logger::log_context_storage::set (const std::string & key, double value) inline static
Set a double context field for the current thread.
Parameters
key Field name
value Field value
Definition at line 112 of file log_context_scope.h.
{
        get_storage()[key] = value;
        get_has_context() = true;
    }
References get_has_context(), and get_storage().
set() [6/6]
static void kcenon::logger::log_context_storage::set (const std::string & key, int64_t value) inline static
Set an integer context field for the current thread.
Parameters
key Field name
value Field value
Definition at line 102 of file log_context_scope.h.
{
        get_storage()[key] = value;
        get_has_context() = true;
    }
References get_has_context(), and get_storage().
set_all()
static void kcenon::logger::log_context_storage::set_all (const log_fields & fields) inline static
Set multiple context fields at once.
Parameters
fields Fields to set
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/log_context_scope.h.
Definition at line 141 of file log_context_scope.h.
{
        for (const auto& [key, value] : fields) {
            get_storage()[key] = value;
        }
        if (!fields.empty()) {
            get_has_context() = true;
        }
    }
References get_has_context(), and get_storage().
The documentation for this class was generated from the following file:
include/kcenon/logger/core/log_context_scope.h