Logger System: kcenon::logger::deployment_strategy Class Reference
kcenon::logger::deployment_strategy Class Reference
Configuration strategy based on deployment environment.
#include <deployment_strategy.h>
Public Member Functions
deployment_strategy (deployment_env env)
Constructor with deployment environment.
std::string get_name () const override
Get the strategy name.
void apply (logger_config &config) const override
Apply this strategy to a logger configuration.
int priority () const override
Get the strategy priority.
Public Member Functions inherited from kcenon::logger::config_strategy_interface
virtual ~config_strategy_interface ()=default
virtual bool is_applicable () const
Check if this strategy is applicable in the current context.
Static Private Member Functions
static void apply_development (logger_config &config)
static void apply_staging (logger_config &config)
static void apply_production (logger_config &config)
static void apply_testing (logger_config &config)
static std::string env_to_string (deployment_env env)
Private Attributes
deployment_env env_
Detailed Description
Configuration strategy based on deployment environment.
Applies environment-appropriate settings for the logger. Each environment type is optimized for its specific use case.
Since
2.0.0
Definition at line 45 of file deployment_strategy.h.
Constructor & Destructor Documentation
deployment_strategy()
kcenon::logger::deployment_strategy::deployment_strategy (deployment_env env) inline explicit
Constructor with deployment environment.
Parameters
env The deployment environment to configure for
Definition at line 51 of file deployment_strategy.h.
        : env_(env) {}
Member Function Documentation
apply()
void kcenon::logger::deployment_strategy::apply (logger_config & config) const inline override virtual
Apply this strategy to a logger configuration.
Parameters
config The configuration to modify
Modifies the provided configuration according to the strategy's rules. Changes are applied in-place.
Implements kcenon::logger::config_strategy_interface.
Definition at line 58 of file deployment_strategy.h.
{
        switch (env_) {
        case deployment_env::development:
            apply_development(config);
            break;
        case deployment_env::staging:
            apply_staging(config);
            break;
        case deployment_env::production:
            apply_production(config);
            break;
        case deployment_env::testing:
            apply_testing(config);
            break;
        }
    }
References apply_development(), apply_production(), apply_staging(), apply_testing(), kcenon::logger::development, env_, kcenon::logger::production, kcenon::logger::staging, and kcenon::logger::testing.
apply_development()
static void kcenon::logger::deployment_strategy::apply_development (logger_config & config) inline static private
Definition at line 82 of file deployment_strategy.h.
{
        config.async = false;
        config.min_level = log_level::trace;
        config.enable_metrics = true;
        config.enable_crash_handler = true;
        config.enable_color_output = true;
        config.enable_source_location = true;
        config.enable_structured_logging = false;
        config.batch_size = 1;
        config.flush_interval = std::chrono::milliseconds(0);
    }
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::enable_color_output, kcenon::logger::logger_config::enable_crash_handler, kcenon::logger::logger_config::enable_metrics, kcenon::logger::logger_config::enable_source_location, kcenon::logger::logger_config::enable_structured_logging, kcenon::logger::logger_config::flush_interval, and kcenon::logger::logger_config::min_level.
Referenced by apply().
apply_production()
static void kcenon::logger::deployment_strategy::apply_production (logger_config & config) inline static private
Definition at line 109 of file deployment_strategy.h.
{
        config.async = true;
        config.min_level = log_level::warn;
        config.enable_metrics = true;
        config.enable_crash_handler = true;
        config.enable_color_output = false;
        config.enable_source_location = false;
        config.enable_structured_logging = true;
        config.buffer_size = 32768;
        config.batch_size = 200;
        config.flush_interval = std::chrono::milliseconds(2000);
        config.max_file_size = 100 * 1024 * 1024;  // 100MB
        config.max_file_count = 10;
        config.enable_compression = true;
        config.enable_batch_writing = true;
        config.queue_overflow_policy = logger_config::overflow_policy::drop_oldest;
    }
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::buffer_size, kcenon::logger::logger_config::enable_batch_writing, kcenon::logger::logger_config::enable_color_output, kcenon::logger::logger_config::enable_compression, kcenon::logger::logger_config::enable_crash_handler, kcenon::logger::logger_config::enable_metrics, kcenon::logger::logger_config::enable_source_location, kcenon::logger::logger_config::enable_structured_logging, kcenon::logger::logger_config::flush_interval, kcenon::logger::logger_config::max_file_count, kcenon::logger::logger_config::max_file_size, kcenon::logger::logger_config::min_level, and kcenon::logger::logger_config::queue_overflow_policy.
Referenced by apply().
apply_staging()
static void kcenon::logger::deployment_strategy::apply_staging (logger_config & config) inline static private
Definition at line 94 of file deployment_strategy.h.
{
        config.async = true;
        config.min_level = log_level::info;
        config.enable_metrics = true;
        config.enable_crash_handler = true;
        config.enable_color_output = false;
        config.enable_structured_logging = true;
        config.buffer_size = 16384;
        config.batch_size = 100;
        config.flush_interval = std::chrono::milliseconds(1000);
        config.max_file_size = 50 * 1024 * 1024;  // 50MB
        config.max_file_count = 5;
        config.enable_batch_writing = true;
    }
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::buffer_size, kcenon::logger::logger_config::enable_batch_writing, kcenon::logger::logger_config::enable_color_output, kcenon::logger::logger_config::enable_crash_handler, kcenon::logger::logger_config::enable_metrics, kcenon::logger::logger_config::enable_structured_logging, kcenon::logger::logger_config::flush_interval, kcenon::logger::logger_config::max_file_count, kcenon::logger::logger_config::max_file_size, and kcenon::logger::logger_config::min_level.
Referenced by apply().
apply_testing()
static void kcenon::logger::deployment_strategy::apply_testing (logger_config & config) inline static private
Definition at line 127 of file deployment_strategy.h.
{
        config.async = false;
        config.min_level = log_level::trace;
        config.enable_metrics = false;
        config.enable_crash_handler = false;
        config.enable_color_output = false;
        config.enable_source_location = true;
        config.batch_size = 1;
        config.flush_interval = std::chrono::milliseconds(0);
    }
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::enable_color_output, kcenon::logger::logger_config::enable_crash_handler, kcenon::logger::logger_config::enable_metrics, kcenon::logger::logger_config::enable_source_location, kcenon::logger::logger_config::flush_interval, and kcenon::logger::logger_config::min_level.
Referenced by apply().
env_to_string()
static std::string kcenon::logger::deployment_strategy::env_to_string (deployment_env env) inline static private
Definition at line 138 of file deployment_strategy.h.
{
        switch (env) {
        case deployment_env::development: return "development";
        case deployment_env::staging: return "staging";
        case deployment_env::production: return "production";
        case deployment_env::testing: return "testing";
        default: return "unknown";
        }
    }
References kcenon::logger::development, kcenon::logger::production, kcenon::logger::staging, and kcenon::logger::testing.
Referenced by get_name().
get_name()
std::string kcenon::logger::deployment_strategy::get_name () const inline override virtual
Get the strategy name.
Returns
Human-readable strategy name
Implements kcenon::logger::config_strategy_interface.
Definition at line 54 of file deployment_strategy.h.
{
        return "deployment:" + env_to_string(env_);
    }
References env_, and env_to_string().
priority()
int kcenon::logger::deployment_strategy::priority () const inline override virtual
Get the strategy priority.
Returns
Priority value (higher = applied first)
When multiple strategies are applied, they are sorted by priority (descending) before application.
Reimplemented from kcenon::logger::config_strategy_interface.
Definition at line 75 of file deployment_strategy.h.
{
        return 75;  // Higher than performance, lower than environment
    }
Member Data Documentation
env_
deployment_env kcenon::logger::deployment_strategy::env_ private
Definition at line 80 of file deployment_strategy.h.
Referenced by apply(), and get_name().
The documentation for this class was generated from the following file:
include/kcenon/logger/core/strategies/deployment_strategy.h