Logger System: kcenon::logger::network_send_jthread_worker Class Reference
kcenon::logger::network_send_jthread_worker Class Reference
Worker thread for sending buffered logs with jthread compatibility.
Public Types
using send_callback = std::function<void()>
Public Member Functions
network_send_jthread_worker (send_callback callback)
~network_send_jthread_worker ()
void start ()
void stop ()
void notify_work ()
Private Attributes
send_callback callback_
compat_jthread thread_
std::atomic< bool > running_ {false}
std::atomic< bool > has_work_ {false}
Detailed Description
Worker thread for sending buffered logs with jthread compatibility.
Uses std::jthread with std::stop_token for cooperative cancellation where available, falls back to std::thread with manual stop mechanism.
Definition at line 52 of file network_writer.cpp.
Member Typedef Documentation
send_callback
using kcenon::logger::network_send_jthread_worker::send_callback = std::function<void()>
Definition at line 54 of file network_writer.cpp.
Constructor & Destructor Documentation
network_send_jthread_worker()
kcenon::logger::network_send_jthread_worker::network_send_jthread_worker (send_callback callback) inline explicit
Definition at line 56 of file network_writer.cpp.
        : callback_(std::move(callback))
    {}
~network_send_jthread_worker()
kcenon::logger::network_send_jthread_worker::~network_send_jthread_worker () inline
Definition at line 60 of file network_writer.cpp.
{
        stop();
    }
References stop().
Member Function Documentation
notify_work()
void kcenon::logger::network_send_jthread_worker::notify_work () inline
Definition at line 105 of file network_writer.cpp.
                       {
        has_work_.store(true, std::memory_order_release);
    }
References has_work_.
start()
void kcenon::logger::network_send_jthread_worker::start () inline
Definition at line 64 of file network_writer.cpp.
                 {
        if (running_.exchange(true, std::memory_order_acq_rel)) {
            return;  // Already started
        }
#if LOGGER_HAS_JTHREAD
        auto callback = callback_;
        thread_ = compat_jthread([callback](std::stop_token stop_token) {
            while (!stop_token.stop_requested()) {
                if (callback) {
                    callback();
                }
                std::this_thread::sleep_for(std::chrono::milliseconds(10));
            }
        });
#else
        // Create worker thread with manual stop source
        // Note: We use the stop_source created by compat_jthread to ensure
        // request_stop() correctly signals the worker loop
        auto callback = callback_;
        thread_ = compat_jthread([callback](simple_stop_source& stop) {
            while (!stop.stop_requested()) {
                if (callback) {
                    callback();
                }
                std::this_thread::sleep_for(std::chrono::milliseconds(10));
            }
        });
#endif
    }
References callback_, running_, stop(), and thread_.
stop()
void kcenon::logger::network_send_jthread_worker::stop () inline
Definition at line 95 of file network_writer.cpp.
                {
        if (!running_.exchange(false, std::memory_order_acq_rel)) {
            return;  // Already stopped
        }
        // Request stop and join thread
        thread_.request_stop();
        thread_.join();
    }
References kcenon::logger::async::compat_jthread::join(), kcenon::logger::async::compat_jthread::request_stop(), running_, and thread_.
Referenced by start(), and ~network_send_jthread_worker().
Member Data Documentation
callback_
send_callback kcenon::logger::network_send_jthread_worker::callback_ private
Definition at line 110 of file network_writer.cpp.
Referenced by start().
has_work_
std::atomic<bool> kcenon::logger::network_send_jthread_worker::has_work_ {false} private
Definition at line 113 of file network_writer.cpp.
{false};
Referenced by notify_work().
running_
std::atomic<bool> kcenon::logger::network_send_jthread_worker::running_ {false} private
Definition at line 112 of file network_writer.cpp.
{false};
Referenced by start(), and stop().
thread_
compat_jthread kcenon::logger::network_send_jthread_worker::thread_ private
Definition at line 111 of file network_writer.cpp.
Referenced by start(), and stop().
The documentation for this class was generated from the following file:
src/impl/writers/network_writer.cpp