Logger System: kcenon::logger::otlp::otel_context_scope Class Reference
kcenon::logger::otlp::otel_context_scope Class Reference
RAII guard for OpenTelemetry context.
#include <otel_context.h>
Public Member Functions
otel_context_scope (const otel_context &ctx)
Construct and set context.
~otel_context_scope ()
Destructor - restores previous context.
otel_context_scope (const otel_context_scope &)=delete
otel_context_scope & operator= (const otel_context_scope &)=delete
otel_context_scope (otel_context_scope &&)=delete
otel_context_scope & operator= (otel_context_scope &&)=delete
Private Attributes
std::optional< otel_context > previous_context_
bool had_previous_
Detailed Description
RAII guard for OpenTelemetry context.
Automatically sets context on construction and clears it on destruction. Useful for request processing.
Definition at line 286 of file otel_context.h.
Constructor & Destructor Documentation
otel_context_scope() [1/3]
kcenon::logger::otlp::otel_context_scope::otel_context_scope (const otel_context & ctx) inline explicit
Construct and set context.
Parameters
ctx Context to set for this scope
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
Definition at line 293 of file otel_context.h.
        : previous_context_(otel_context_storage::get()),
          had_previous_(otel_context_storage::has_context()) {
        otel_context_storage::set(ctx);
    }
References kcenon::logger::otlp::otel_context_storage::set().
~otel_context_scope()
kcenon::logger::otlp::otel_context_scope::~otel_context_scope () inline
Destructor - restores previous context.
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
Definition at line 302 of file otel_context.h.
{
        if (had_previous_) {
            otel_context_storage::set(*previous_context_);
        } else {
            otel_context_storage::clear();
        }
    }
References kcenon::logger::otlp::otel_context_storage::clear(), had_previous_, previous_context_, and kcenon::logger::otlp::otel_context_storage::set().
otel_context_scope() [2/3]
kcenon::logger::otlp::otel_context_scope::otel_context_scope (const otel_context_scope &) delete
otel_context_scope() [3/3]
kcenon::logger::otlp::otel_context_scope::otel_context_scope (otel_context_scope &&) delete
Member Function Documentation
operator=() [1/2]
otel_context_scope & kcenon::logger::otlp::otel_context_scope::operator= (const otel_context_scope &) delete
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
operator=() [2/2]
otel_context_scope & kcenon::logger::otlp::otel_context_scope::operator= (otel_context_scope &&) delete
Member Data Documentation
had_previous_
bool kcenon::logger::otlp::otel_context_scope::had_previous_ private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
Definition at line 318 of file otel_context.h.
Referenced by ~otel_context_scope().
previous_context_
std::optional<otel_context> kcenon::logger::otlp::otel_context_scope::previous_context_ private
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/otlp/otel_context.h.
Definition at line 317 of file otel_context.h.
Referenced by ~otel_context_scope().
The documentation for this class was generated from the following file:
include/kcenon/logger/otlp/otel_context.h