Logger System: kcenon::logger::base_formatter Class Reference
kcenon::logger::base_formatter Class Reference abstract
Base implementation for log formatters.
#include <base_formatter.h>
Public Member Functions
virtual ~base_formatter ()=default
virtual std::string format (const log_entry &entry) const override=0
Format a log entry into a string.
Public Member Functions inherited from kcenon::logger::log_formatter_interface
virtual ~log_formatter_interface ()=default
virtual void set_options (const format_options &opts)
Set formatting options.
virtual format_options get_options () const
Get current formatting options.
virtual std::string get_name () const =0
Protected Member Functions
std::string level_to_string (log_level level) const
Convert log level to string.
std::string format_timestamp (const std::chrono::system_clock::time_point &timestamp) const
Format timestamp to ISO8601 string.
std::string get_thread_id () const
Get current thread ID as string.
Additional Inherited Members
Protected Attributes inherited from kcenon::logger::log_formatter_interface
format_options options_
Detailed Description
Base implementation for log formatters.
Provides common formatting functionality for derived formatters.
Definition at line 31 of file base_formatter.h.
Constructor & Destructor Documentation
~base_formatter()
virtual kcenon::logger::base_formatter::~base_formatter () virtual default
Member Function Documentation
format()
virtual std::string kcenon::logger::base_formatter::format (const log_entry & entry) const override pure virtual
Format a log entry into a string.
Parameters
entry The log entry to format
Returns
Formatted string representation
Implements kcenon::logger::log_formatter_interface.
Implemented in kcenon::logger::compact_formatter, kcenon::logger::json_formatter, kcenon::logger::json_formatter, and kcenon::logger::plain_formatter.
format_timestamp()
std::string kcenon::logger::base_formatter::format_timestamp (const std::chrono::system_clock::time_point & timestamp) const inline protected
Format timestamp to ISO8601 string.
Parameters
timestamp Time point to format
Returns
ISO8601 formatted string
Definition at line 65 of file base_formatter.h.
{
        auto time_t = std::chrono::system_clock::to_time_t(timestamp);
        std::ostringstream oss;
        oss << std::put_time(std::gmtime(&time_t), "%Y-%m-%dT%H:%M:%SZ");
        return oss.str();
    }
Referenced by kcenon::logger::json_formatter::format(), and kcenon::logger::plain_formatter::format().
get_thread_id()
std::string kcenon::logger::base_formatter::get_thread_id () const inline protected
Get current thread ID as string.
Returns
Thread ID string
Definition at line 76 of file base_formatter.h.
{
        std::ostringstream oss;
        oss << std::this_thread::get_id();
        return oss.str();
    }
Referenced by kcenon::logger::json_formatter::format(), and kcenon::logger::plain_formatter::format().
level_to_string()
std::string kcenon::logger::base_formatter::level_to_string (log_level level) const inline protected
Convert log level to string.
Parameters
level Log level
Returns
String representation
Definition at line 48 of file base_formatter.h.
{
        switch (level) {
            case log_level::critical:  return "CRITICAL";
            case log_level::error:  return "ERROR";
            case log_level::warning:   return "WARNING";
            case log_level::info:   return "INFO";
            case log_level::debug:  return "DEBUG";
            case log_level::trace:  return "TRACE";
            default: return "UNKNOWN";
        }
    }
Referenced by kcenon::logger::compact_formatter::format(), kcenon::logger::json_formatter::format(), and kcenon::logger::plain_formatter::format().
The documentation for this class was generated from the following file:
include/kcenon/logger/formatters/base_formatter.h