Logger System: kcenon::logger::queued_writer_base< Container > Class Template Reference
kcenon::logger::queued_writer_base< Container > Class Template Reference
Abstract base class for queue-based log writers.
#include <queued_writer_base.h>
Public Member Functions
queued_writer_base (std::unique_ptr< log_writer_interface > wrapped_writer, std::size_t max_queue_size, std::string_view decorator_name)
Constructor for queued writer base.
~queued_writer_base () override=default
Virtual destructor.
bool is_healthy () const override
Check if the writer is healthy.
std::size_t get_queue_size () const
Get the current queue size.
std::size_t get_max_queue_size () const
Get maximum queue size.
Public Member Functions inherited from kcenon::logger::decorator_writer_base
decorator_writer_base (std::unique_ptr< log_writer_interface > wrapped, std::string_view decorator_name)
Construct a decorator writer base.
~decorator_writer_base () override=default
Virtual destructor for proper cleanup.
decorator_writer_base (const decorator_writer_base &)=delete
decorator_writer_base & operator= (const decorator_writer_base &)=delete
decorator_writer_base (decorator_writer_base &&) noexcept=default
decorator_writer_base & operator= (decorator_writer_base &&) noexcept=default
common::VoidResult write (const log_entry &entry) override=0
Write a log entry (must be implemented by derived classes)
common::VoidResult flush () override
Flush the wrapped writer.
std::string get_name () const override
Get the name of this writer.
const log_writer_interface * get_wrapped_writer () const noexcept
Get the wrapped writer (const version)
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
virtual common::VoidResult close ()
Close the writer and release resources.
virtual auto is_open () const -> bool
Check if writer is open and ready.
Protected Member Functions
common::VoidResult try_enqueue (const log_entry &entry)
Try to enqueue an entry with overflow protection.
virtual common::VoidResult handle_overflow (const log_entry &)
Handle queue overflow condition.
virtual void on_entry_enqueued ()
Called after an entry is successfully enqueued.
Protected Member Functions inherited from kcenon::logger::decorator_writer_base
log_writer_interface & wrapped () noexcept
Access the wrapped writer (non-const)
const log_writer_interface & wrapped () const noexcept
Access the wrapped writer (const)
const std::string & decorator_name () const noexcept
Get the decorator name.
Static Protected Member Functions
template<typename T >
static std::size_t get_container_size (const std::queue< T > &container)
Get container size (specialization for std::queue)
template<typename T >
static std::size_t get_container_size (const std::vector< T > &container)
Get container size (specialization for std::vector)
template<typename T >
static void enqueue_entry (std::queue< T > &container, const log_entry &entry)
Enqueue entry (specialization for std::queue)
template<typename T >
static void enqueue_entry (std::vector< T > &container, const log_entry &entry)
Enqueue entry (specialization for std::vector)
Protected Attributes
std::size_t max_queue_size_
std::mutex queue_mutex_
Container queue_
std::atomic< bool > shutting_down_
Additional Inherited Members
Static Public Attributes inherited from kcenon::logger::decorator_writer_tag
static constexpr writer_category category = writer_category::decorator
Static Public Attributes inherited from kcenon::logger::async_writer_tag
static constexpr writer_category category = writer_category::asynchronous
Detailed Description
template<typename Container>
class kcenon::logger::queued_writer_base< Container >
Abstract base class for queue-based log writers.
This template provides common functionality for writers that accumulate log entries in a queue before processing. Derived classes must implement the queue processing strategy (immediate async vs batched).
Template Parameter:
Container: The container type to use for storing entries (e.g., std::queue, std::vector)
Category: Asynchronous (non-blocking), Decorator (wraps another writer)
Definition at line 61 of file queued_writer_base.h.
Constructor & Destructor Documentation
queued_writer_base()
template<typename Container > kcenon::logger::queued_writer_base< Container >::queued_writer_base (std::unique_ptr< log_writer_interface > wrapped_writer, std::size_t max_queue_size, std::string_view decorator_name) inline explicit
Constructor for queued writer base.
Parameters
wrapped_writer The underlying writer to delegate writes to
max_queue_size Maximum number of entries in the queue
decorator_name Name of the decorator (e.g., "async", "batch")
Exceptions
std::invalid_argument if wrapped_writer is null
Definition at line 70 of file queued_writer_base.h.
        : decorator_writer_base(std::move(wrapped_writer), decorator_name)
        , max_queue_size_(max_queue_size)
        , shutting_down_(false) {
    }
~queued_writer_base()
template<typename Container > kcenon::logger::queued_writer_base< Container >::~queued_writer_base () override default
Virtual destructor.
Member Function Documentation
enqueue_entry() [1/2]
template<typename Container > template<typename T > static void kcenon::logger::queued_writer_base< Container >::enqueue_entry (std::queue< T > & container, const log_entry & entry) inline static protected
Enqueue entry (specialization for std::queue)
Definition at line 162 of file queued_writer_base.h.
{
        container.push(copy_log_entry(entry));
    }
References kcenon::logger::copy_log_entry().
Referenced by kcenon::logger::queued_writer_base< Container >::try_enqueue().
enqueue_entry() [2/2]
template<typename Container > template<typename T > static void kcenon::logger::queued_writer_base< Container >::enqueue_entry (std::vector< T > & container, const log_entry & entry) inline static protected
Enqueue entry (specialization for std::vector)
Definition at line 170 of file queued_writer_base.h.
{
        container.push_back(copy_log_entry(entry));
    }
References kcenon::logger::copy_log_entry().
get_container_size() [1/2]
template<typename Container > template<typename T > static std::size_t kcenon::logger::queued_writer_base< Container >::get_container_size (const std::queue< T > & container) inline static protected
Get container size (specialization for std::queue)
Definition at line 146 of file queued_writer_base.h.
{
        return container.size();
    }
Referenced by kcenon::logger::queued_writer_base< Container >::get_queue_size(), and kcenon::logger::queued_writer_base< Container >::try_enqueue().
get_container_size() [2/2]
template<typename Container > template<typename T > static std::size_t kcenon::logger::queued_writer_base< Container >::get_container_size (const std::vector< T > & container) inline static protected
Get container size (specialization for std::vector)
Definition at line 154 of file queued_writer_base.h.
{
        return container.size();
    }
get_max_queue_size()
template<typename Container > std::size_t kcenon::logger::queued_writer_base< Container >::get_max_queue_size () const inline
Get maximum queue size.
Returns
Maximum allowed queue size
Definition at line 104 of file queued_writer_base.h.
{
        return max_queue_size_;
    }
References kcenon::logger::queued_writer_base< Container >::max_queue_size_.
get_queue_size()
template<typename Container > std::size_t kcenon::logger::queued_writer_base< Container >::get_queue_size () const inline
Get the current queue size.
Returns
Number of entries currently in the queue
Definition at line 95 of file queued_writer_base.h.
{
        std::lock_guard<std::mutex> lock(queue_mutex_);
        return get_container_size(queue_);
    }
References kcenon::logger::queued_writer_base< Container >::get_container_size(), kcenon::logger::queued_writer_base< Container >::queue_, and kcenon::logger::queued_writer_base< Container >::queue_mutex_.
handle_overflow()
template<typename Container > virtual common::VoidResult kcenon::logger::queued_writer_base< Container >::handle_overflow (const log_entry &) inline protected virtual
Handle queue overflow condition.
Parameters
entry The entry that couldn't be enqueued
Returns
Error result indicating queue full
Note
Derived classes can override to implement custom overflow policies
Reimplemented in kcenon::logger::async_writer.
Definition at line 132 of file queued_writer_base.h.
{
        return make_logger_void_result(logger_error_code::queue_full, "Queue is full");
    }
References kcenon::logger::make_logger_void_result(), and kcenon::logger::queue_full.
Referenced by kcenon::logger::queued_writer_base< Container >::try_enqueue().
is_healthy()
template<typename Container > bool kcenon::logger::queued_writer_base< Container >::is_healthy () const inline override virtual
Check if the writer is healthy.
Returns
true if healthy, false otherwise
Reimplemented from kcenon::logger::decorator_writer_base.
Definition at line 87 of file queued_writer_base.h.
{
        return !shutting_down_ && wrapped().is_healthy();
    }
References kcenon::logger::log_writer_interface::is_healthy(), kcenon::logger::queued_writer_base< Container >::shutting_down_, and kcenon::logger::decorator_writer_base::wrapped().
on_entry_enqueued()
template<typename Container > virtual void kcenon::logger::queued_writer_base< Container >::on_entry_enqueued () inline protected virtual
Called after an entry is successfully enqueued.
Note
Derived classes can override to implement notifications (e.g., condition variable)
Reimplemented in kcenon::logger::async_writer.
Definition at line 140 of file queued_writer_base.h.
{}
Referenced by kcenon::logger::queued_writer_base< Container >::try_enqueue().
try_enqueue()
template<typename Container > common::VoidResult kcenon::logger::queued_writer_base< Container >::try_enqueue (const log_entry & entry) inline protected
Try to enqueue an entry with overflow protection.
Parameters
entry The log entry to enqueue
Returns
common::VoidResult indicating success or queue_full error
Definition at line 114 of file queued_writer_base.h.
{
        std::lock_guard<std::mutex> lock(queue_mutex_);
        if (get_container_size(queue_) >= max_queue_size_) {
            return handle_overflow(entry);
        }
        enqueue_entry(queue_, entry);
        on_entry_enqueued();
        return common::ok();
    }
References kcenon::logger::queued_writer_base< Container >::enqueue_entry(), kcenon::logger::queued_writer_base< Container >::get_container_size(), kcenon::logger::queued_writer_base< Container >::handle_overflow(), kcenon::logger::queued_writer_base< Container >::max_queue_size_, kcenon::common::ok(), kcenon::logger::queued_writer_base< Container >::on_entry_enqueued(), kcenon::logger::queued_writer_base< Container >::queue_, and kcenon::logger::queued_writer_base< Container >::queue_mutex_.
Member Data Documentation
max_queue_size_
template<typename Container > std::size_t kcenon::logger::queued_writer_base< Container >::max_queue_size_ protected
Definition at line 174 of file queued_writer_base.h.
Referenced by kcenon::logger::queued_writer_base< Container >::get_max_queue_size(), and kcenon::logger::queued_writer_base< Container >::try_enqueue().
queue_
template<typename Container > Container kcenon::logger::queued_writer_base< Container >::queue_ protected
Definition at line 177 of file queued_writer_base.h.
Referenced by kcenon::logger::queued_writer_base< Container >::get_queue_size(), and kcenon::logger::queued_writer_base< Container >::try_enqueue().
queue_mutex_
template<typename Container > std::mutex kcenon::logger::queued_writer_base< Container >::queue_mutex_ mutable protected
Definition at line 176 of file queued_writer_base.h.
Referenced by kcenon::logger::queued_writer_base< Container >::get_queue_size(), and kcenon::logger::queued_writer_base< Container >::try_enqueue().
shutting_down_
template<typename Container > std::atomic<bool> kcenon::logger::queued_writer_base< Container >::shutting_down_ protected
Definition at line 179 of file queued_writer_base.h.
Referenced by kcenon::logger::queued_writer_base< Container >::is_healthy().
The documentation for this class was generated from the following file:
include/kcenon/logger/writers/queued_writer_base.h