Logger System: kcenon::logger::log_context_scope Class Reference
kcenon::logger::log_context_scope Class Reference
RAII guard for structured logging context.
#include <log_context_scope.h>
Public Member Functions
log_context_scope (const log_fields &fields)
Construct scope with initial fields.
log_context_scope (logger &log, const log_fields &fields)
Construct scope with a logger reference (for logger-level context)
~log_context_scope ()
Destructor - restores previous context.
log_context_scope (const log_context_scope &)=delete
log_context_scope & operator= (const log_context_scope &)=delete
log_context_scope (log_context_scope &&)=delete
log_context_scope & operator= (log_context_scope &&)=delete
Private Member Functions
void remove_logger_context (const std::string &key)
Private Attributes
log_fields previous_context_
bool had_previous_
std::vector< std::string > added_keys_
logger * logger_ = nullptr
Detailed Description
RAII guard for structured logging context.
Automatically sets context fields on construction and restores the previous context on destruction. Supports nested scopes where inner scopes can add or override fields from outer scopes.
Examples
structured_logging_example.cpp.
Definition at line 251 of file log_context_scope.h.
Constructor & Destructor Documentation
log_context_scope() [1/4]
kcenon::logger::log_context_scope::log_context_scope (const log_fields & fields) inline explicit
Construct scope with initial fields.
Parameters
fields Context fields to set for this scope
Saves the current thread-local context and sets the new fields. Fields are merged with existing context (new fields override existing ones with the same key).
Definition at line 261 of file log_context_scope.h.
        : previous_context_(log_context_storage::get()),
          had_previous_(log_context_storage::has_context()) {
        for (const auto& [key, value] : fields) {
            // Track which keys we're adding (to remove them on destruction)
            if (previous_context_.find(key) == previous_context_.end()) {
                added_keys_.push_back(key);
            }
            log_context_storage::set(key, value);
        }
    }
log_context_scope() [2/4]
kcenon::logger::log_context_scope::log_context_scope (logger & log, const log_fields & fields)
Construct scope with a logger reference (for logger-level context)
Parameters
log Logger to use for context
fields Context fields to set for this scope
Sets context on both the logger (for non-thread-local use) and thread-local storage.
Definition at line 10 of file log_context_scope.cpp.
    : previous_context_(log_context_storage::get()),
      had_previous_(log_context_storage::has_context()),
      logger_(&log) {
    for (const auto& [key, value] : fields) {
        // Track which keys we're adding
        if (previous_context_.find(key) == previous_context_.end()) {
            added_keys_.push_back(key);
        }
        log_context_storage::set(key, value);
        // Also set on logger for non-thread-local context
        std::visit([&log, &key](const auto& v) {
            log.context().set(key, v);
        }, value);
    }
}
References added_keys_, kcenon::logger::logger::context(), previous_context_, kcenon::logger::log_context_storage::set(), and kcenon::logger::unified_log_context::set().
~log_context_scope()
kcenon::logger::log_context_scope::~log_context_scope () inline
Destructor - restores previous context.
Removes fields that were added by this scope and restores fields that were overridden.
Definition at line 289 of file log_context_scope.h.
{
        // Remove keys that were added by this scope
        for (const auto& key : added_keys_) {
            log_context_storage::remove(key);
        }
        // Restore overridden values from previous context
        if (had_previous_) {
            for (const auto& [key, value] : previous_context_) {
                // Only restore if the key was overridden (not newly added)
                if (std::find(added_keys_.begin(), added_keys_.end(), key) == added_keys_.end()) {
                    log_context_storage::set(key, value);
                }
            }
        }
        // Clear logger context if we set it
        if (logger_ != nullptr) {
            for (const auto& key : added_keys_) {
                remove_logger_context(key);
            }
        }
    }
log_context_scope() [3/4]
kcenon::logger::log_context_scope::log_context_scope (const log_context_scope &) delete
log_context_scope() [4/4]
kcenon::logger::log_context_scope::log_context_scope (log_context_scope &&) delete
Member Function Documentation
operator=() [1/2]
log_context_scope & kcenon::logger::log_context_scope::operator= (const log_context_scope &) delete
operator=() [2/2]
log_context_scope & kcenon::logger::log_context_scope::operator= (log_context_scope &&) delete
remove_logger_context()
void kcenon::logger::log_context_scope::remove_logger_context (const std::string & key) private
Definition at line 28 of file log_context_scope.cpp.
{
    if (logger_ != nullptr) {
        logger_->context().remove(key);
    }
}
References kcenon::logger::logger::context(), logger_, and kcenon::logger::unified_log_context::remove().
Member Data Documentation
added_keys_
std::vector<std::string> kcenon::logger::log_context_scope::added_keys_ private
Definition at line 324 of file log_context_scope.h.
Referenced by log_context_scope().
had_previous_
bool kcenon::logger::log_context_scope::had_previous_ private
Definition at line 323 of file log_context_scope.h.
logger_
logger* kcenon::logger::log_context_scope::logger_ = nullptr private
Definition at line 325 of file log_context_scope.h.
Referenced by remove_logger_context().
previous_context_
log_fields kcenon::logger::log_context_scope::previous_context_ private
Definition at line 322 of file log_context_scope.h.
Referenced by log_context_scope().
The documentation for this class was generated from the following files:
include/kcenon/logger/core/log_context_scope.h
src/core/log_context_scope.cpp