Logger System: kcenon::logger::analysis::log_analyzer Class Reference
kcenon::logger::analysis::log_analyzer Class Reference export
module kcenon.logger
Log analyzer for processing and analyzing log data.
#include <log_analyzer.h>
Public Member Functions
void add_entry (const analyzed_log_entry &entry)
Add a log entry for analysis.
void add_entries (const std::vector< analyzed_log_entry > &entries)
Add multiple log entries.
void clear ()
Clear all entries.
const analysis_stats & get_stats ()
Get analysis statistics.
std::vector< analyzed_log_entry > filter_by_level (log_level level) const
Filter entries by log level.
std::vector< analyzed_log_entry > filter_by_time_range (const std::chrono::system_clock::time_point &start, const std::chrono::system_clock::time_point &end) const
Filter entries by time range.
std::vector< analyzed_log_entry > search_messages (const std::string &search_text) const
Find entries containing specific text.
double get_error_rate (const std::chrono::minutes &window=std::chrono::minutes(60)) const
Get error rate for a time window.
std::string generate_summary_report ()
Generate summary report.
void add_entry (const analyzed_log_entry &entry)
Add a log entry for analysis.
void add_entries (const std::vector< analyzed_log_entry > &entries)
Add multiple log entries.
void clear ()
Clear all entries.
const analysis_stats & get_stats ()
Get analysis statistics.
std::vector< analyzed_log_entry > filter_by_level (common::interfaces::log_level level) const
Filter entries by log level.
std::vector< analyzed_log_entry > filter_by_time_range (const std::chrono::system_clock::time_point &start, const std::chrono::system_clock::time_point &end) const
Filter entries by time range.
std::vector< analyzed_log_entry > search_messages (const std::string &search_text) const
Find entries containing specific text.
double get_error_rate (const std::chrono::minutes &window=std::chrono::minutes(60)) const
Get error rate for a time window.
std::string generate_summary_report ()
Generate summary report.
size_t size () const
Get the total number of entries.
bool empty () const
Check if the analyzer has no entries.
Private Member Functions
void update_stats ()
std::string level_to_string (log_level level) const
void update_stats ()
std::string level_to_string (common::interfaces::log_level level) const
Private Attributes
std::vector< analyzed_log_entry > entries_
analysis_stats cached_stats_
bool stats_dirty_ = true
Detailed Description
Log analyzer for processing and analyzing log data.
Provides functionality to:
Add and store log entries
Filter entries by various criteria
Compute statistics and rates
Generate summary reports
Definition at line 75 of file analysis.cppm.
Member Function Documentation
add_entries() [1/2]
void kcenon::logger::analysis::log_analyzer::add_entries (const std::vector< analyzed_log_entry > & entries) inline
Add multiple log entries.
Definition at line 69 of file log_analyzer.h.
{
        entries_.insert(entries_.end(), entries.begin(), entries.end());
        stats_dirty_ = true;
    }
References entries_, and stats_dirty_.
add_entries() [2/2]
void kcenon::logger::analysis::log_analyzer::add_entries (const std::vector< analyzed_log_entry > & entries) inline export
Add multiple log entries.
Parameters
entries Vector of entries to add
Definition at line 95 of file analysis.cppm.
{
        entries_.insert(entries_.end(), entries.begin(), entries.end());
        stats_dirty_ = true;
    }
References entries_, and stats_dirty_.
add_entry() [1/2]
void kcenon::logger::analysis::log_analyzer::add_entry (const analyzed_log_entry & entry) inline
Add a log entry for analysis.
Definition at line 61 of file log_analyzer.h.
{
        entries_.push_back(entry);
        stats_dirty_ = true;
    }
References entries_, and stats_dirty_.
add_entry() [2/2]
void kcenon::logger::analysis::log_analyzer::add_entry (const analyzed_log_entry & entry) inline export
Add a log entry for analysis.
Parameters
entry The entry to add
Definition at line 86 of file analysis.cppm.
{
        entries_.push_back(entry);
        stats_dirty_ = true;
    }
References entries_, and stats_dirty_.
clear() [1/2]
void kcenon::logger::analysis::log_analyzer::clear () inline
Clear all entries.
Definition at line 77 of file log_analyzer.h.
                 {
        entries_.clear();
        cached_stats_ = analysis_stats{};
        stats_dirty_ = true;
    }
References cached_stats_, entries_, and stats_dirty_.
clear() [2/2]
void kcenon::logger::analysis::log_analyzer::clear () inline export
Clear all entries.
Definition at line 103 of file analysis.cppm.
                 {
        entries_.clear();
        cached_stats_ = analysis_stats{};
        stats_dirty_ = true;
    }
References cached_stats_, entries_, and stats_dirty_.
empty()
bool kcenon::logger::analysis::log_analyzer::empty () const inline export
Check if the analyzer has no entries.
Returns
true if empty
Definition at line 232 of file analysis.cppm.
                       {
        return entries_.empty();
    }
References entries_.
filter_by_level() [1/2]
std::vector< analyzed_log_entry > kcenon::logger::analysis::log_analyzer::filter_by_level (common::interfaces::log_level level) const inline export
Filter entries by log level.
Parameters
level The level to filter for
Returns
Vector of matching entries
Definition at line 126 of file analysis.cppm.
{
        std::vector<analyzed_log_entry> filtered;
        for (const auto& entry : entries_) {
            if (entry.level == level) {
                filtered.push_back(entry);
            }
        }
        return filtered;
    }
References entries_.
filter_by_level() [2/2]
std::vector< analyzed_log_entry > kcenon::logger::analysis::log_analyzer::filter_by_level (log_level level) const inline
Filter entries by log level.
Definition at line 97 of file log_analyzer.h.
{
        std::vector<analyzed_log_entry> filtered;
        for (const auto& entry : entries_) {
            if (entry.level == level) {
                filtered.push_back(entry);
            }
        }
        return filtered;
    }
References entries_.
filter_by_time_range() [1/2]
std::vector< analyzed_log_entry > kcenon::logger::analysis::log_analyzer::filter_by_time_range (const std::chrono::system_clock::time_point & start, const std::chrono::system_clock::time_point & end) const inline
Filter entries by time range.
Definition at line 110 of file log_analyzer.h.
{
        std::vector<analyzed_log_entry> filtered;
        for (const auto& entry : entries_) {
            if (entry.timestamp >= start && entry.timestamp <= end) {
                filtered.push_back(entry);
            }
        }
        return filtered;
    }
References entries_.
filter_by_time_range() [2/2]
std::vector< analyzed_log_entry > kcenon::logger::analysis::log_analyzer::filter_by_time_range (const std::chrono::system_clock::time_point & start, const std::chrono::system_clock::time_point & end) const inline export
Filter entries by time range.
Parameters
start Start of time range
end End of time range
Returns
Vector of entries within the time range
Definition at line 142 of file analysis.cppm.
{
        std::vector<analyzed_log_entry> filtered;
        for (const auto& entry : entries_) {
            if (entry.timestamp >= start && entry.timestamp <= end) {
                filtered.push_back(entry);
            }
        }
        return filtered;
    }
References entries_.
generate_summary_report() [1/2]
std::string kcenon::logger::analysis::log_analyzer::generate_summary_report () inline
Generate summary report.
Definition at line 163 of file log_analyzer.h.
{
        const auto& stats = get_stats();
        std::string report = "=== Log Analysis Summary ===\n";
        report += "Total Entries: " + std::to_string(stats.total_entries) + "\n";
        report += "Level Distribution:\n";
        for (const auto& [level, count] : stats.level_counts) {
            report += "  " + level_to_string(level) + ": " + std::to_string(count) + "\n";
        }
        if (stats.total_entries > 0) {
            auto duration = std::chrono::duration_cast<std::chrono::minutes>(
                stats.latest_timestamp - stats.earliest_timestamp);
            report += "Time Range: " + std::to_string(duration.count()) + " minutes\n";
        }
        return report;
    }
References get_stats(), and level_to_string().
generate_summary_report() [2/2]
std::string kcenon::logger::analysis::log_analyzer::generate_summary_report () inline export
Generate summary report.
Returns
Formatted summary string
Definition at line 200 of file analysis.cppm.
{
        const auto& stats = get_stats();
        std::string report = "=== Log Analysis Summary ===\n";
        report += "Total Entries: " + std::to_string(stats.total_entries) + "\n";
        report += "Level Distribution:\n";
        for (const auto& [level, count] : stats.level_counts) {
            report += "  " + level_to_string(level) + ": " + std::to_string(count) + "\n";
        }
        if (stats.total_entries > 0) {
            auto duration = std::chrono::duration_cast<std::chrono::minutes>(
                stats.latest_timestamp - stats.earliest_timestamp);
            report += "Time Range: " + std::to_string(duration.count()) + " minutes\n";
        }
        return report;
    }
References get_stats(), and level_to_string().
get_error_rate() [1/2]
double kcenon::logger::analysis::log_analyzer::get_error_rate (const std::chrono::minutes & window = std::chrono::minutes(60)) const inline
Get error rate for a time window.
Definition at line 139 of file log_analyzer.h.
{
        auto now = std::chrono::system_clock::now();
        auto start_time = now - window;
        size_t total_in_window = 0;
        size_t errors_in_window = 0;
        for (const auto& entry : entries_) {
            if (entry.timestamp >= start_time) {
                total_in_window++;
                if (entry.level == log_level::error ||
                    entry.level == log_level::fatal) {
                    errors_in_window++;
                }
            }
        }
        return total_in_window > 0 ?
            static_cast<double>(errors_in_window) / total_in_window : 0.0;
    }
References entries_.
get_error_rate() [2/2]
double kcenon::logger::analysis::log_analyzer::get_error_rate (const std::chrono::minutes & window = std::chrono::minutes(60)) const inline export
Get error rate for a time window.
Parameters
window Time window to analyze (default: 60 minutes)
Returns
Error rate as a decimal (0.0 to 1.0)
Definition at line 175 of file analysis.cppm.
{
        auto now = std::chrono::system_clock::now();
        auto start_time = now - window;
        size_t total_in_window = 0;
        size_t errors_in_window = 0;
        for (const auto& entry : entries_) {
            if (entry.timestamp >= start_time) {
                total_in_window++;
                if (entry.level == common::interfaces::log_level::error ||
                    entry.level == common::interfaces::log_level::critical) {
                    errors_in_window++;
                }
            }
        }
        return total_in_window > 0 ?
            static_cast<double>(errors_in_window) / static_cast<double>(total_in_window) : 0.0;
    }
References entries_.
get_stats() [1/2]
const analysis_stats & kcenon::logger::analysis::log_analyzer::get_stats () inline
Get analysis statistics.
Definition at line 86 of file log_analyzer.h.
{
        if (stats_dirty_) {
            update_stats();
            stats_dirty_ = false;
        }
        return cached_stats_;
    }
References cached_stats_, stats_dirty_, and update_stats().
Referenced by generate_summary_report().
get_stats() [2/2]
const analysis_stats & kcenon::logger::analysis::log_analyzer::get_stats () inline export
Get analysis statistics.
Returns
Reference to computed statistics
Definition at line 113 of file analysis.cppm.
{
        if (stats_dirty_) {
            update_stats();
            stats_dirty_ = false;
        }
        return cached_stats_;
    }
References cached_stats_, stats_dirty_, and update_stats().
level_to_string() [1/2]
std::string kcenon::logger::analysis::log_analyzer::level_to_string (common::interfaces::log_level level) const inline export private
Definition at line 262 of file analysis.cppm.
{
        // Use underlying integer to avoid duplicate case value errors
        // (warn and warning both = 3, fatal and critical both = 5)
        const int level_value = static_cast<int>(level);
        switch (level_value) {
            case 0: return "TRACE";
            case 1: return "DEBUG";
            case 2: return "INFO";
            case 3: return "WARN";
            case 4: return "ERROR";
            case 5: return "FATAL";
            case 6: return "OFF";
            default: return "UNKNOWN";
        }
    }
level_to_string() [2/2]
std::string kcenon::logger::analysis::log_analyzer::level_to_string (log_level level) const inline private
Definition at line 209 of file log_analyzer.h.
{
        switch (level) {
            case log_level::trace: return "TRACE";
            case log_level::debug: return "DEBUG";
            case log_level::info: return "INFO";
            case log_level::warn: return "WARN";
            case log_level::error: return "ERROR";
            case log_level::fatal: return "FATAL";
            case log_level::off: return "OFF";
            default: return "UNKNOWN";
        }
    }
Referenced by generate_summary_report().
search_messages() [1/2]
std::vector< analyzed_log_entry > kcenon::logger::analysis::log_analyzer::search_messages (const std::string & search_text) const inline
Find entries containing specific text.
Definition at line 126 of file log_analyzer.h.
{
        std::vector<analyzed_log_entry> results;
        for (const auto& entry : entries_) {
            if (entry.message.find(search_text) != std::string::npos) {
                results.push_back(entry);
            }
        }
        return results;
    }
References entries_.
search_messages() [2/2]
std::vector< analyzed_log_entry > kcenon::logger::analysis::log_analyzer::search_messages (const std::string & search_text) const inline export
Find entries containing specific text.
Parameters
search_text Text to search for
Returns
Vector of matching entries
Definition at line 160 of file analysis.cppm.
{
        std::vector<analyzed_log_entry> results;
        for (const auto& entry : entries_) {
            if (entry.message.find(search_text) != std::string::npos) {
                results.push_back(entry);
            }
        }
        return results;
    }
References entries_.
size()
size_t kcenon::logger::analysis::log_analyzer::size () const inline export
Get the total number of entries.
Returns
Number of stored entries
Definition at line 224 of file analysis.cppm.
{
        return entries_.size();
    }
References entries_.
update_stats() [1/2]
void kcenon::logger::analysis::log_analyzer::update_stats () inline private
Definition at line 184 of file log_analyzer.h.
{
        cached_stats_ = analysis_stats{};
        cached_stats_.total_entries = entries_.size();
        if (entries_.empty()) {
            return;
        }
        // Initialize timestamps
        cached_stats_.earliest_timestamp = entries_[0].timestamp;
        cached_stats_.latest_timestamp = entries_[0].timestamp;
        // Count levels and update timestamps
        for (const auto& entry : entries_) {
            cached_stats_.level_counts[entry.level]++;
            if (entry.timestamp < cached_stats_.earliest_timestamp) {
                cached_stats_.earliest_timestamp = entry.timestamp;
            }
            if (entry.timestamp > cached_stats_.latest_timestamp) {
                cached_stats_.latest_timestamp = entry.timestamp;
            }
        }
    }
References cached_stats_, kcenon::logger::analysis::analysis_stats::earliest_timestamp, entries_, kcenon::logger::analysis::analysis_stats::latest_timestamp, kcenon::logger::analysis::analysis_stats::level_counts, and kcenon::logger::analysis::analysis_stats::total_entries.
Referenced by get_stats().
update_stats() [2/2]
void kcenon::logger::analysis::log_analyzer::update_stats () inline export private
Definition at line 237 of file analysis.cppm.
{
        cached_stats_ = analysis_stats{};
        cached_stats_.total_entries = entries_.size();
        if (entries_.empty()) {
            return;
        }
        // Initialize timestamps
        cached_stats_.earliest_timestamp = entries_[0].timestamp;
        cached_stats_.latest_timestamp = entries_[0].timestamp;
        // Count levels and update timestamps
        for (const auto& entry : entries_) {
            cached_stats_.level_counts[entry.level]++;
            if (entry.timestamp < cached_stats_.earliest_timestamp) {
                cached_stats_.earliest_timestamp = entry.timestamp;
            }
            if (entry.timestamp > cached_stats_.latest_timestamp) {
                cached_stats_.latest_timestamp = entry.timestamp;
            }
        }
    }
References cached_stats_, kcenon::logger::analysis::analysis_stats::earliest_timestamp, entries_, kcenon::logger::analysis::analysis_stats::latest_timestamp, kcenon::logger::analysis::analysis_stats::level_counts, and kcenon::logger::analysis::analysis_stats::total_entries.
Member Data Documentation
cached_stats_
analysis_stats kcenon::logger::analysis::log_analyzer::cached_stats_ export private
Definition at line 54 of file log_analyzer.h.
Referenced by clear(), get_stats(), and update_stats().
entries_
std::vector< analyzed_log_entry > kcenon::logger::analysis::log_analyzer::entries_ export private
Definition at line 53 of file log_analyzer.h.
Referenced by add_entries(), add_entry(), clear(), empty(), filter_by_level(), filter_by_level(), filter_by_time_range(), get_error_rate(), search_messages(), size(), and update_stats().
stats_dirty_
bool kcenon::logger::analysis::log_analyzer::stats_dirty_ = true export private
Definition at line 55 of file log_analyzer.h.
Referenced by add_entries(), add_entry(), clear(), and get_stats().
The documentation for this class was generated from the following files:
include/kcenon/logger/analysis/log_analyzer.h
src/modules/analysis.cppm