Logger System: logger_module::network_writer Class Reference
logger_module::network_writer Class Reference
Sends logs over network (TCP/UDP)
#include <network_writer.h>
Classes
struct connection_stats
Get connection statistics.
Public Types
enum class protocol_type { tcp , udp }
Public Member Functions
network_writer (const std::string &host, uint16_t port, protocol_type protocol=protocol_type::tcp, size_t buffer_size=8192, std::chrono::seconds reconnect_interval=std::chrono::seconds(5))
Constructor.
~network_writer () override
Destructor.
result_void write (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write log entry.
result_void flush () override
Flush pending logs.
std::string get_name () const override
Get writer name.
bool is_connected () const
Check if connected.
connection_stats get_stats () const
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
virtual bool is_healthy () const override
Check if the writer is healthy and operational.
Protected Member Functions
std::string format_log_entry (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (thread_module::log_level level) const
Convert log level to string representation.
std::string level_to_color (thread_module::log_level level) const
Get ANSI color code for the specified log level.
Detailed Description
Sends logs over network (TCP/UDP)
Definition at line 25 of file network_writer.h.
Member Enumeration Documentation
protocol_type
enum class logger_module::network_writer::protocol_type strong
Enumerator
tcp
udp
Definition at line 27 of file network_writer.h.
Constructor & Destructor Documentation
network_writer()
logger_module::network_writer::network_writer (const std::string & host, uint16_t port, protocol_type protocol = protocol_type::tcp, size_t buffer_size = 8192, std::chrono::seconds reconnect_interval = std::chrono::seconds(5))
Constructor.
Parameters
host Remote host address
port Remote port
protocol Network protocol (TCP/UDP)
buffer_size Internal buffer size
reconnect_interval Reconnection interval in seconds
Definition at line 33 of file network_writer.cpp.
References tcp.
~network_writer()
logger_module::network_writer::~network_writer () override
Destructor.
Definition at line 67 of file network_writer.cpp.
Member Function Documentation
flush()
result_void logger_module::network_writer::flush () override virtual
Flush pending logs.
Implements logger_module::base_writer.
Definition at line 111 of file network_writer.cpp.
References logger_module::flush_timeout, and logger_module::make_logger_error().
format_log_entry()
std::string logger_module::base_writer::format_log_entry (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) protected inherited
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 131 of file console_writer.cpp.
References logger_module::base_writer::level_to_string().
Referenced by logger_module::console_writer::write(), logger_module::encrypted_writer::write(), and logger_module::file_writer::write().
get_name()
std::string logger_module::network_writer::get_name () const inline override virtual
Get writer name.
Implements logger_module::base_writer.
Definition at line 69 of file network_writer.h.
get_stats()
network_writer::connection_stats logger_module::network_writer::get_stats () const
Definition at line 135 of file network_writer.cpp.
is_connected()
bool logger_module::network_writer::is_connected () const inline
Check if connected.
Definition at line 74 of file network_writer.h.
is_healthy()
virtual bool logger_module::base_writer::is_healthy () const inline override virtual inherited
Check if the writer is healthy and operational.
Returns
true if the writer is functioning correctly, false otherwise
Used for health monitoring and automatic failover. A writer might be unhealthy if its destination is unavailable (e.g., disk full, network disconnected).
Note
Default implementation always returns true. Override for writers that can detect failure conditions.
Since
1.0.0
Implements logger_module::log_writer_interface.
Reimplemented in logger_module::async_writer, and logger_module::batch_writer.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 249 of file base_writer.h.
level_to_color()
std::string logger_module::base_writer::level_to_color (thread_module::log_level level) const protected inherited
Get ANSI color code for the specified log level.
Parameters
level Log level to get color for
Returns
ANSI escape sequence for color, or empty string if color is disabled
Returns appropriate ANSI color codes for terminal output:
trace -> Gray/Dim
debug -> Cyan
info -> Green
warning -> Yellow
error -> Red
Note
Returns empty string if use_color() is false.
Warning
Only use for terminals that support ANSI escape codes.
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 170 of file console_writer.cpp.
References logger_module::base_writer::use_color().
Referenced by logger_module::console_writer::write().
level_to_string()
std::string logger_module::base_writer::level_to_string (thread_module::log_level level) const protected inherited
Convert log level to string representation.
Parameters
level Log level to convert
Returns
String representation of the level
Maps log levels to human-readable strings:
trace -> "TRACE"
debug -> "DEBUG"
info -> "INFO"
warning -> "WARNING"
error -> "ERROR"
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 158 of file console_writer.cpp.
Referenced by logger_module::base_writer::format_log_entry().
set_use_color()
virtual void logger_module::base_writer::set_use_color (bool use_color) inline virtual inherited
Set whether to use color output (if supported)
Parameters
use_color true to enable color output, false to disable
Enables or disables ANSI color codes in formatted output. Only affects writers that output to terminals supporting color.
Note
Has no effect on writers that don't support color (e.g., file writers).
Since
1.0.0
Reimplemented in logger_module::async_writer.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 209 of file base_writer.h.
References logger_module::base_writer::use_color().
Referenced by logger_module::console_writer::console_writer().
use_color()
bool logger_module::base_writer::use_color () const inline inherited
Get current color output setting.
Returns
true if color output is enabled, false otherwise
Since
1.0.0
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 219 of file base_writer.h.
Referenced by logger_module::base_writer::level_to_color(), logger_module::base_writer::set_use_color(), logger_module::async_writer::set_use_color(), and logger_module::console_writer::write().
write() [1/2]
virtual result_void logger_module::base_writer::write (const log_entry & entry) inline override virtual inherited
Write a log entry using the new interface.
Parameters
entry The log entry to write
Returns
result_void Success or error code
This method provides compatibility with the modern log_entry structure. The default implementation converts the entry to the legacy API format for backward compatibility. Derived classes can override this for optimized handling.
Note
This method extracts source location information if present in the entry.
Since
1.0.0
Implements logger_module::log_writer_interface.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/writers/base_writer.h.
Definition at line 140 of file base_writer.h.
References logger_module::log_entry::level, logger_module::log_entry::location, logger_module::log_entry::message, logger_module::log_entry::timestamp, and logger_module::base_writer::write().
Referenced by logger_module::base_writer::write().
write() [2/2]
result_void logger_module::network_writer::write (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write log entry.
Implements logger_module::base_writer.
Definition at line 87 of file network_writer.cpp.
References logger_module::network_writer::connection_stats::send_failures.
The documentation for this class was generated from the following files:
/home/runner/work/logger_system/logger_system/sources/logger/writers/network_writer.h
/home/runner/work/logger_system/logger_system/sources/logger/writers/network_writer.cpp