Logger System: examples/custom_writer_example.cpp File Reference
custom_writer_example.cpp File Reference
Example demonstrating how to create custom writers using thread_safe_writer.
#include <kcenon/logger/core/logger_builder.h>
#include <kcenon/logger/writers/thread_safe_writer.h>
#include <kcenon/logger/writers/console_writer.h>
#include <kcenon/logger/formatters/json_formatter.h>
#include <kcenon/logger/interfaces/log_entry.h>
#include <kcenon/common/interfaces/logger_interface.h>
#include <iostream>
#include <vector>
#include <map>
Classes
class memory_writer
A custom writer that stores log entries in memory.
class counted_console_writer
A console writer that counts messages per log level.
Functions
int main ()
Detailed Description
Example demonstrating how to create custom writers using thread_safe_writer.
Definition in file custom_writer_example.cpp.
Function Documentation
main()
int main ()
Definition at line 216 of file custom_writer_example.cpp.
           {
    std::cout << "=== Custom Writer Example (thread_safe_writer) ===" << std::endl;
    std::cout << std::endl;
    // Example 1: Memory Writer
    std::cout << "--- Example 1: Memory Writer ---" << std::endl;
    {
        auto result = logger_builder()
            .with_min_level(kcenon::common::interfaces::log_level::info)
            .add_writer("memory", std::make_unique<memory_writer>())
            .build();
        if (!result.has_value()) {
            std::cerr << "Failed to create logger" << std::endl;
            return 1;
        }
        auto logger = std::move(result.value());
        // Log some messages
        logger->log(ci::log_level::info, std::string("First message"));
        logger->log(ci::log_level::warning, std::string("Second message"));
        logger->log(ci::log_level::error, std::string("Third message"));
        std::cout << "Logged 3 messages to memory writer" << std::endl;
    }
    std::cout << std::endl;
    // Example 2: Counted Console Writer
    std::cout << "--- Example 2: Counted Console Writer ---" << std::endl;
    {
        auto counted_writer = std::make_unique<counted_console_writer>();
        auto* counted_ptr = counted_writer.get();  // Keep reference for stats
        auto result = logger_builder()
            .with_min_level(kcenon::common::interfaces::log_level::debug)
            .add_writer("counted", std::move(counted_writer))
            .build();
        if (!result.has_value()) {
            std::cerr << "Failed to create logger" << std::endl;
            return 1;
        }
        auto logger = std::move(result.value());
        // Log messages at different levels
        logger->log(ci::log_level::debug, std::string("Debug message 1"));
        logger->log(ci::log_level::debug, std::string("Debug message 2"));
        logger->log(ci::log_level::info, std::string("Info message"));
        logger->log(ci::log_level::warning, std::string("Warning message"));
        logger->log(ci::log_level::error, std::string("Error message"));
        // Print statistics
        counted_ptr->print_stats();
    }
    std::cout << std::endl;
    std::cout << "=== Custom Writer Example Complete ===" << std::endl;
    return 0;
}
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::result< T >::value(), and kcenon::logger::logger_builder::with_min_level().