Logger System: logger_module::v1_compat Namespace Reference
logger_module::v1_compat Namespace Reference
Classes
struct logger_config_v1
Legacy logger configuration structure.
Functions
std::string format_string (const char *fmt,...)
Format string with variable arguments (C-style)
logger * create_logger ()
Legacy logger creation function.
logger * create_logger (const std::string &name)
Legacy logger creation with name.
logger * create_file_logger (const std::string &filename)
Legacy file logger creation.
void add_writer (logger *log, base_writer *writer)
Legacy writer addition with raw pointer.
void add_console_writer (logger *log)
Legacy console writer addition.
void add_file_writer (logger *log, const std::string &filename)
Legacy file writer addition.
void set_level (logger *log, log_level level)
Legacy level setting.
void set_async (logger *log, bool async)
Legacy async mode setting.
void set_pattern (logger *log, const std::string &pattern)
Legacy pattern setting.
logger * get_global_logger ()
Legacy global logger instance.
void init_logging (const logger_config_v1 &config={})
Legacy initialization function.
void shutdown_logging ()
Legacy shutdown function.
Function Documentation
add_console_writer()
void logger_module::v1_compat::add_console_writer (logger * log) inline
Legacy console writer addition.
Deprecated:
Use logger_builder with with_console_writer()
Definition at line 175 of file logger_v1_compat.h.
References logger_module::logger::add_writer().
add_file_writer()
void logger_module::v1_compat::add_file_writer (logger * log, const std::string & filename) inline
Legacy file writer addition.
Deprecated:
Use logger_builder with with_file_writer()
Definition at line 188 of file logger_v1_compat.h.
References logger_module::logger::add_writer().
add_writer()
void logger_module::v1_compat::add_writer (logger * log, base_writer * writer) inline
Legacy writer addition with raw pointer.
Deprecated:
Use add_writer with std::unique_ptr
Definition at line 162 of file logger_v1_compat.h.
References logger_module::logger::add_writer().
create_file_logger()
logger * logger_module::v1_compat::create_file_logger (const std::string & filename) inline
Legacy file logger creation.
Deprecated:
Use logger_builder with with_file_writer()
Definition at line 146 of file logger_v1_compat.h.
References logger_module::logger_builder::add_writer(), and logger_module::logger_builder::build().
create_logger() [1/2]
logger * logger_module::v1_compat::create_logger () inline
Legacy logger creation function.
Deprecated:
Use logger_builder instead
Definition at line 114 of file logger_v1_compat.h.
References logger_module::logger_builder::add_writer(), and logger_module::logger_builder::build().
create_logger() [2/2]
logger * logger_module::v1_compat::create_logger (const std::string & name) inline
Legacy logger creation with name.
Deprecated:
Use logger_builder with with_name()
Definition at line 130 of file logger_v1_compat.h.
References logger_module::logger_builder::add_writer(), and logger_module::logger_builder::build().
format_string()
std::string logger_module::v1_compat::format_string (const char * fmt, ...) inline
Format string with variable arguments (C-style)
Deprecated:
Use structured logging with fields instead
Definition at line 37 of file logger_v1_compat.h.
get_global_logger()
logger * logger_module::v1_compat::get_global_logger () inline
Legacy global logger instance.
Deprecated:
Use dependency injection instead of global state
Definition at line 264 of file logger_v1_compat.h.
References logger_module::logger_builder::add_writer(), and logger_module::logger_builder::build().
init_logging()
void logger_module::v1_compat::init_logging (const logger_config_v1 & config = {}) inline
Legacy initialization function.
Deprecated:
Use logger_builder
Definition at line 282 of file logger_v1_compat.h.
set_async()
void logger_module::v1_compat::set_async (logger * log, bool async) inline
Legacy async mode setting.
Deprecated:
Use logger_builder with with_async_mode()
Definition at line 212 of file logger_v1_compat.h.
set_level()
void logger_module::v1_compat::set_level (logger * log, log_level level) inline
Legacy level setting.
Deprecated:
Loggers are immutable in v2. Recreate with logger_builder.
Definition at line 201 of file logger_v1_compat.h.
set_pattern()
void logger_module::v1_compat::set_pattern (logger * log, const std::string & pattern) inline
Legacy pattern setting.
Deprecated:
Use logger_builder with with_pattern()
Definition at line 223 of file logger_v1_compat.h.
shutdown_logging()
void logger_module::v1_compat::shutdown_logging () inline
Legacy shutdown function.
Deprecated:
Loggers clean up automatically via RAII
Definition at line 292 of file logger_v1_compat.h.