Logger System: kcenon::logger::adapters Namespace Reference
kcenon::logger::adapters Namespace Reference
Classes
class common_logger_factory
Factory for creating common_system compatible loggers.
class common_system_logger_adapter
Adapter to expose kcenon::logger as common::interfaces::ILogger.
class logger_adapter
Adapter to expose logger as common::interfaces::ILogger.
class logger_from_common_adapter
Adapter to use common::interfaces::ILogger in logger_system.
Typedefs
using log_level = common::interfaces::log_level
Functions
inline ::common::interfaces::log_level to_common_level (log_level level)
Convert log levels between logger_system and common_system.
log_level from_common_level (::common::interfaces::log_level level)
Typedef Documentation
log_level
using kcenon::logger::adapters::log_level = common::interfaces::log_level
Definition at line 26 of file logger_adapter.h.
Function Documentation
from_common_level()
log_level kcenon::logger::adapters::from_common_level (::common::interfaces::log_level level) inline
Definition at line 56 of file common_logger_adapter.h.
{
    switch (level) {
        case ::common::interfaces::log_level::trace:
            return log_level::trace;
        case ::common::interfaces::log_level::debug:
            return log_level::debug;
        case ::common::interfaces::log_level::info:
            return log_level::info;
        case ::common::interfaces::log_level::warning:
            return log_level::warning;
        case ::common::interfaces::log_level::error:
            return log_level::error;
        case ::common::interfaces::log_level::critical:
            return log_level::critical;
        case ::common::interfaces::log_level::off:
            return log_level::off;
        default:
            return log_level::info;
    }
}
Referenced by kcenon::logger::adapters::logger_from_common_adapter::get_level(), kcenon::logger::adapters::logger_adapter::log(), kcenon::logger::adapters::logger_adapter::log_entry(), kcenon::logger::adapters::logger_adapter::log_with_location(), and kcenon::logger::adapters::logger_adapter::set_level().
to_common_level()
inline ::common::interfaces::log_level kcenon::logger::adapters::to_common_level (log_level level)
Convert log levels between logger_system and common_system.
Definition at line 35 of file common_logger_adapter.h.
{
    switch (level) {
        case log_level::trace:
            return ::common::interfaces::log_level::trace;
        case log_level::debug:
            return ::common::interfaces::log_level::debug;
        case log_level::info:
            return ::common::interfaces::log_level::info;
        case log_level::warning:
            return ::common::interfaces::log_level::warning;
        case log_level::error:
            return ::common::interfaces::log_level::error;
        case log_level::critical:
            return ::common::interfaces::log_level::critical;
        case log_level::off:
            return ::common::interfaces::log_level::off;
        default:
            return ::common::interfaces::log_level::info;
    }
}
Referenced by kcenon::logger::adapters::logger_adapter::get_level(), kcenon::logger::adapters::logger_from_common_adapter::log(), kcenon::logger::adapters::logger_from_common_adapter::log_with_location(), and kcenon::logger::adapters::logger_from_common_adapter::set_level().