Logger System: kcenon::common Namespace Reference
kcenon::common Namespace Reference
Namespaces
namespace error_codes
Classes
struct error_info
class Result
class VoidResult
Functions
error_info make_error_info (int code_value, std::string message_value, std::string category_value)
template<typename T >
Result< T > ok (T value)
VoidResult ok ()
template<typename T >
Result< T > error (error_info info)
VoidResult error (error_info info)
template<typename T >
bool is_ok (const Result< T > &result)
template<typename T >
bool is_error (const Result< T > &result)
bool is_ok (const VoidResult &result)
bool is_error (const VoidResult &result)
template<typename T >
T & get_value (Result< T > &result)
template<typename T >
const T & get_value (const Result< T > &result)
template<typename T >
error_info & get_error (Result< T > &result)
template<typename T >
const error_info & get_error (const Result< T > &result)
const error_info & get_error (const VoidResult &result)
Function Documentation
error() [1/2]
template<typename T > Result< T > kcenon::common::error (error_info info)
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 154 of file error_codes.h.
{
    return Result<T>(std::move(info));
}
error() [2/2]
VoidResult kcenon::common::error (error_info info) inline
Definition at line 158 of file error_codes.h.
{
    return VoidResult(std::move(info));
}
get_error() [1/3]
template<typename T > const error_info & kcenon::common::get_error (const Result< T > & result)
Definition at line 196 of file error_codes.h.
{
    return result.error();
}
References kcenon::common::Result< T >::error().
get_error() [2/3]
const error_info & kcenon::common::get_error (const VoidResult & result) inline
Definition at line 200 of file error_codes.h.
{
    return result.error();
}
References kcenon::common::VoidResult::error().
get_error() [3/3]
template<typename T > error_info & kcenon::common::get_error (Result< T > & result)
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h, and monitoring_integration_example.cpp.
Definition at line 191 of file error_codes.h.
{
    return result.error();
}
References kcenon::common::Result< T >::error().
Referenced by aggregating_monitor::check_health().
get_value() [1/2]
template<typename T > const T & kcenon::common::get_value (const Result< T > & result)
Definition at line 186 of file error_codes.h.
{
    return result.value();
}
References kcenon::common::Result< T >::value().
get_value() [2/2]
template<typename T > T & kcenon::common::get_value (Result< T > & result)
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h, di_pattern_example.cpp, and monitoring_integration_example.cpp.
Definition at line 181 of file error_codes.h.
{
    return result.value();
}
References kcenon::common::Result< T >::value().
Referenced by aggregating_monitor::check_health(), example_1_basic_integration(), example_2_multiple_loggers(), example_3_imonitorable_interface(), example_4_monitoring_system_simulation(), aggregating_monitor::get_metrics(), and use_logger_via_interface().
is_error() [1/2]
template<typename T > bool kcenon::common::is_error (const Result< T > & result)
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 168 of file error_codes.h.
{
    return result.has_error();
}
References kcenon::common::Result< T >::has_error().
is_error() [2/2]
bool kcenon::common::is_error (const VoidResult & result) inline
Definition at line 176 of file error_codes.h.
{
    return result.has_error();
}
References kcenon::common::VoidResult::has_error().
is_ok() [1/2]
template<typename T > bool kcenon::common::is_ok (const Result< T > & result)
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h, di_pattern_example.cpp, and monitoring_integration_example.cpp.
Definition at line 163 of file error_codes.h.
{
    return result.has_value();
}
References kcenon::common::Result< T >::has_value().
Referenced by aggregating_monitor::check_health(), example_1_basic_integration(), example_2_multiple_loggers(), example_3_imonitorable_interface(), example_4_monitoring_system_simulation(), aggregating_monitor::get_metrics(), and use_logger_via_interface().
is_ok() [2/2]
bool kcenon::common::is_ok (const VoidResult & result) inline
Definition at line 172 of file error_codes.h.
{
    return !result.has_error();
}
References kcenon::common::VoidResult::has_error().
make_error_info()
error_info kcenon::common::make_error_info (int code_value, std::string message_value, std::string category_value) inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h.
Definition at line 65 of file error_codes.h.
{
    return error_info{code_value, std::move(message_value), std::move(category_value)};
}
ok() [1/2]
VoidResult kcenon::common::ok () inline
Examples
/home/runner/work/logger_system/logger_system/include/kcenon/logger/core/error_codes.h, Implementing, custom_writer_example.cpp, di_pattern_example.cpp, and monitoring_integration_example.cpp.
Definition at line 149 of file error_codes.h.
                       {
    return VoidResult{};
}
Referenced by kcenon::logger::logger::add_writer(), kcenon::logger::logger::add_writer(), kcenon::logger::encrypted_writer::auto_rotate_key_if_needed(), kcenon::logger::utils::check_condition(), kcenon::logger::utils::check_file_exists(), kcenon::logger::utils::check_stream_state(), kcenon::logger::rotating_file_writer::cleanup_old_files(), kcenon::logger::logger::clear_writers(), kcenon::logger::file_writer::close(), kcenon::logger::logger::enable_metrics_collection(), kcenon::logger::encrypted_writer::encrypt_data(), kcenon::logger::utils::ensure_directory_exists(), kcenon::logger::async::high_performance_async_writer::flush(), kcenon::logger::batch_writer::flush(), kcenon::logger::console_sink::flush(), kcenon::logger::console_writer::flush(), kcenon::logger::file_sink::flush(), kcenon::logger::file_writer::flush(), kcenon::logger::logger::flush(), kcenon::logger::network_writer::flush(), kcenon::logger::otlp_writer::flush(), kcenon::logger::batch_writer::flush_batch_unsafe(), counted_console_writer::flush_impl(), memory_writer::flush_impl(), kcenon::logger::encrypted_writer::generate_iv(), kcenon::logger::rotating_file_writer::get_backup_files(), kcenon::logger::logger::log(), kcenon::logger::logger::log(), kcenon::logger::logger::log(), kcenon::logger::make_logger_void_success(), kcenon::logger::result< T >::ok_value(), kcenon::logger::file_writer::open_internal(), kcenon::logger::rotating_file_writer::perform_rotation(), aggregating_monitor::record_metric(), example_monitor::record_metric(), example_monitor::record_metric(), aggregating_monitor::reset(), example_monitor::reset(), kcenon::logger::basic_monitor::reset_metrics(), kcenon::logger::thread_system_monitor_adapter::reset_metrics(), kcenon::logger::encrypted_writer::rotate_key(), kcenon::logger::security::secure_key_storage::save_key(), kcenon::logger::basic_monitor::set_enabled(), kcenon::logger::thread_system_monitor_adapter::set_enabled(), kcenon::logger::utils::file_utils::set_file_permissions(), kcenon::logger::logger::set_level(), kcenon::logger::logger::start(), kcenon::logger::logger::stop(), kcenon::logger::queued_writer_base< Container >::try_enqueue(), kcenon::logger::logger_config::validate(), kcenon::logger::security::path_validator::validate(), kcenon::logger::security::secure_key_storage::validate_key_path(), kcenon::logger::utils::file_utils::validate_log_path(), kcenon::logger::async::high_performance_async_writer::write(), kcenon::logger::batch_writer::write(), kcenon::logger::buffered_writer::write(), kcenon::logger::filtered_writer::write(), kcenon::logger::network_writer::write(), kcenon::logger::otlp_writer::write(), kcenon::logger::rotating_file_writer::write(), counted_console_writer::write_entry_impl(), memory_writer::write_entry_impl(), kcenon::logger::console_sink::write_raw(), and kcenon::logger::file_sink::write_raw().
ok() [2/2]
template<typename T > Result< T > kcenon::common::ok (T value)
Definition at line 145 of file error_codes.h.
                      {
    return Result<T>(std::move(value));
}