Logger System: logger_module Namespace Reference
logger_module Namespace Reference
Namespaces
namespace v1_compat
Classes
class access_control_filter
Filter that controls access based on log level and source.
class adaptive_backpressure
Adaptive backpressure system.
class async_writer
Asynchronous wrapper for log writers.
class base_formatter
Base implementation for log formatters.
class base_writer
Abstract base class for all log output writers.
class basic_monitor
Basic monitoring implementation.
class batch_writer
Batch writer that accumulates log entries and writes them in batches.
class block_policy
Block until space is available.
struct buffer_health_info
Buffer health information.
class compact_formatter
Compact formatter for minimal output.
class composite_filter
Combine multiple filters with AND/OR logic.
class composite_strategy
Combines multiple strategies in sequence.
class config_strategy_factory
Factory for creating configuration strategies.
interface config_strategy_interface
Abstract interface for configuration strategies.
class console_writer
Console writer that outputs logs to stdout/stderr.
class custom_overflow_policy
class di_container_factory
Factory for creating DI containers.
class di_container_interface
Abstract interface for dependency injection container.
class drop_newest_policy
Drop newest messages when queue is full.
class drop_oldest_policy
Drop oldest messages when queue is full.
class encrypted_writer
Writer that encrypts log data before passing to another writer.
class environment_strategy
Strategy for applying environment-based configuration.
class file_writer
Basic file writer for logging to files.
class function_filter
Filter logs by custom function.
class grow_policy
Dynamically grow the queue.
struct health_check_criteria
Health check criteria for different components.
class health_check_result
Health check result.
class health_check_system
Comprehensive health check system for logger components.
class health_check_utils
Health check utilities.
class json_formatter
JSON formatter for structured logging.
class level_filter
Filter logs by minimum level.
class lightweight_container
Simple dependency injection container.
class lightweight_di_container
Lightweight implementation of DI container.
class log_aggregator
Aggregates logs from multiple sources.
class log_analyzer
Real-time log analysis and statistics.
class log_collector
Asynchronous log collector for high-performance logging.
struct log_entry
Represents a single log entry with all associated metadata.
class log_filter
Base class for log filtering.
interface log_filter_interface
Interface for log filters.
interface log_formatter_interface
Interface for log formatters.
struct log_route
Represents a routing rule.
class log_router
Routes log messages to specific writers based on filters.
class log_sanitizer
Sanitizes sensitive information from log messages.
class log_server
Server that receives logs from network writers.
interface log_sink_interface
Interface for log sinks.
interface log_writer_interface
Interface for log writers.
class logger
Main logger implementation that implements thread_system's logger_interface.
class logger_builder
Builder pattern for logger construction with validation.
struct logger_config
Configuration structure for logger with validation.
class logger_metrics_collector
Collects and manages logger performance metrics.
struct metric_value
Single metric value with metadata.
class monitoring_data
Collection of metrics.
class monitoring_factory
Factory for creating monitoring implementations.
class monitoring_interface
Abstract monitoring interface.
class network_writer
Sends logs over network (TCP/UDP)
class overflow_policy_base
Base class for overflow policies.
class overflow_policy_factory
Factory for creating overflow policies.
class overflow_queue
Queue with overflow policy support.
struct overflow_stats
Statistics for overflow handling.
struct performance_metrics
Comprehensive performance metrics for the logger.
class performance_tuning_strategy
Strategy for automatic performance tuning based on system resources.
class plain_formatter
Simple plain text formatter.
struct queue_health_info
Queue health information.
class regex_filter
Filter logs by regex pattern.
class rotating_file_writer
File writer with rotation support based on size or time.
class router_builder
Fluent builder for creating routing rules.
class sanitizing_filter
Log filter that sanitizes messages before logging.
class scoped_health_registration
RAII helper for automatic health check registration.
class small_string
Small String Optimization (SSO) implementation.
struct source_location
Source code location information for debugging.
struct standard_fields
Standard field names for structured logging.
class structured_log_entry
Builder pattern for structured log entries.
class structured_logger
Logger with structured logging support.
class template_strategy
Strategy for applying predefined configuration templates.
class thread_system_di_adapter
Adapter to use thread_system's service container.
class thread_system_monitor_adapter
Adapter to use thread_system's monitoring capabilities.
struct writer_health_info
Writer health information.
struct writer_metrics
Performance metrics for a specific log writer.
Typedefs
using log_level = thread_module::log_level
using small_string_64 = small_string< 64 >
using small_string_128 = small_string< 128 >
using small_string_256 = small_string< 256 >
using small_string_512 = small_string< 512 >
using error_code = logger_error_code
Enumerations
enum class logger_error_code {
success = 0 , unknown_error = 1 , not_implemented = 2 , invalid_argument = 3 ,
writer_not_found = 1000 , writer_initialization_failed = 1001 , writer_already_exists = 1002 , writer_not_healthy = 1003 ,
file_open_failed = 1100 , file_write_failed = 1101 , file_rotation_failed = 1102 , file_permission_denied = 1103 ,
network_connection_failed = 1200 , network_send_failed = 1201 , network_timeout = 1202 , buffer_overflow = 1300 ,
queue_full = 1301 , queue_stopped = 1302 , invalid_configuration = 1400 , configuration_missing = 1401 ,
configuration_conflict = 1402 , metrics_collection_failed = 1500 , metrics_not_available = 1501 , flush_timeout = 1600 ,
processing_failed = 1601 , filter_error = 1602 , formatter_error = 1603 , encryption_failed = 1700 ,
decryption_failed = 1701 , authentication_failed = 1702 , sanitization_failed = 1703 , di_not_available = 1800 ,
component_not_found = 1801 , registration_failed = 1802 , creation_failed = 1803 , operation_failed = 1804
}
Error codes specific to the logger system.
enum class overflow_policy_type {
drop_oldest , drop_newest , block , grow ,
custom
}
Overflow policy types.
enum class health_status { healthy , degraded , unhealthy , unknown }
Health status levels.
enum class metric_type { counter , gauge , histogram , summary }
Metric types for categorization.
Functions
lightweight_container & get_container ()
Get the global lightweight container instance.
std::string logger_error_to_string (logger_error_code code)
Convert logger_error_code to string representation.
error make_logger_error (logger_error_code code, const std::string &message="")
Create a logger error from error code.
result_void make_error (logger_error_code code, const std::string &message="")
Helper function to create an error result.
template<typename T >
result< T > make_error (logger_error_code code, const std::string &message="")
Helper function to create an error result with value.
std::string health_status_to_string (health_status status)
Convert health status to string.
std::string metric_type_to_string (metric_type type)
Convert metric type to string.
std::unique_ptr< batch_writer > make_batch_writer (std::unique_ptr< base_writer > writer, size_t batch_size=100, std::chrono::milliseconds flush_interval=std::chrono::milliseconds{1000})
Factory function to create a batch writer.
Variables
static logger_crash_safety * g_instance = nullptr
static std::mutex g_instance_mutex
Typedef Documentation
error_code
using logger_module::error_code = typedef logger_error_code
Examples
/home/runner/work/logger_system/logger_system/sources/logger/config/logger_builder.h.
Definition at line 225 of file error_codes.h.
log_level
using logger_module::log_level = typedef thread_module::log_level
Definition at line 28 of file logger_v1_compat.h.
small_string_128
using logger_module::small_string_128 = typedef small_string<128>
Examples
/home/runner/work/logger_system/logger_system/sources/logger/interfaces/log_entry.h.
Definition at line 441 of file small_string.h.
small_string_256
using logger_module::small_string_256 = typedef small_string<256>
Examples
/home/runner/work/logger_system/logger_system/sources/logger/interfaces/log_entry.h.
Definition at line 442 of file small_string.h.
small_string_512
using logger_module::small_string_512 = typedef small_string<512>
Definition at line 443 of file small_string.h.
small_string_64
using logger_module::small_string_64 = typedef small_string<64>
Definition at line 440 of file small_string.h.
Enumeration Type Documentation
health_status
enum class logger_module::health_status strong
Health status levels.
Enumerator
healthy
Everything is working normally.
degraded
Some issues but still operational.
unhealthy
Major issues, may not be operational.
unknown
Status cannot be determined.
Definition at line 30 of file monitoring_interface.h.
logger_error_code
enum class logger_module::logger_error_code strong
Error codes specific to the logger system.
These error codes extend the thread_module error codes with logger-specific error conditions.
Enumerator
success
unknown_error
not_implemented
invalid_argument
writer_not_found
writer_initialization_failed
writer_already_exists
writer_not_healthy
file_open_failed
file_write_failed
file_rotation_failed
file_permission_denied
network_connection_failed
network_send_failed
network_timeout
buffer_overflow
queue_full
queue_stopped
invalid_configuration
configuration_missing
configuration_conflict
metrics_collection_failed
metrics_not_available
flush_timeout
processing_failed
filter_error
formatter_error
encryption_failed
decryption_failed
authentication_failed
sanitization_failed
di_not_available
component_not_found
registration_failed
creation_failed
operation_failed
Examples
/home/runner/work/logger_system/logger_system/sources/logger/config/logger_builder.h.
Definition at line 57 of file error_codes.h.
metric_type
enum class logger_module::metric_type strong
Metric types for categorization.
Enumerator
counter
Monotonically increasing value.
gauge
Value that can go up or down.
histogram
Distribution of values.
summary
Statistical summary.
Examples
/home/runner/work/logger_system/logger_system/sources/logger/logger.h.
Definition at line 40 of file monitoring_interface.h.
overflow_policy_type
enum class logger_module::overflow_policy_type strong
Overflow policy types.
Enumerator
drop_oldest
Drop oldest messages when queue is full.
drop_newest
Drop newest messages when queue is full.
block
Block until space is available.
grow
Dynamically grow the queue.
custom
Custom policy implementation.
Definition at line 61 of file overflow_policy.h.
Function Documentation
get_container()
lightweight_container & logger_module::get_container () inline
Get the global lightweight container instance.
Returns
Reference to the global container
Definition at line 111 of file lightweight_container.h.
health_status_to_string()
std::string logger_module::health_status_to_string (health_status status) inline
Convert health status to string.
Parameters
status The health status
Returns
String representation
Definition at line 287 of file monitoring_interface.h.
References degraded, healthy, unhealthy, and unknown.
logger_error_to_string()
std::string logger_module::logger_error_to_string (logger_error_code code) inline
Convert logger_error_code to string representation.
Parameters
code The error code to convert
Returns
Human-readable error description
Definition at line 120 of file error_codes.h.
References authentication_failed, buffer_overflow, component_not_found, configuration_conflict, configuration_missing, creation_failed, decryption_failed, di_not_available, encryption_failed, file_open_failed, file_permission_denied, file_rotation_failed, file_write_failed, filter_error, flush_timeout, formatter_error, invalid_argument, invalid_configuration, metrics_collection_failed, metrics_not_available, network_connection_failed, network_send_failed, network_timeout, not_implemented, operation_failed, processing_failed, queue_full, queue_stopped, registration_failed, sanitization_failed, success, unknown_error, writer_already_exists, writer_initialization_failed, writer_not_found, and writer_not_healthy.
Referenced by make_logger_error().
make_batch_writer()
std::unique_ptr< batch_writer > logger_module::make_batch_writer (std::unique_ptr< base_writer > writer, size_t batch_size = 100, std::chrono::milliseconds flush_interval = std::chrono::milliseconds{1000})
Factory function to create a batch writer.
Parameters
writer The underlying writer to wrap
batch_size Maximum batch size
flush_interval Auto-flush interval in milliseconds
Returns
Unique pointer to the batch writer
Definition at line 186 of file batch_writer.cpp.
References logger_module::batch_writer::config::flush_interval, and logger_module::batch_writer::config::max_batch_size.
make_error() [1/2]
result_void logger_module::make_error (logger_error_code code, const std::string & message = "") inline
Helper function to create an error result.
Parameters
code Logger error code
message Error message
Returns
result_void with error
Definition at line 252 of file error_codes.h.
References make_logger_error().
make_error() [2/2]
template<typename T > result< T > logger_module::make_error (logger_error_code code, const std::string & message = "") inline
Helper function to create an error result with value.
Template Parameters
T Result value type
Parameters
code Logger error code
message Error message
Returns
result<T> with error
Definition at line 264 of file error_codes.h.
References make_logger_error().
make_logger_error()
error logger_module::make_logger_error (logger_error_code code, const std::string & message = "") inline
Create a logger error from error code.
Parameters
code Logger error code
message Optional detailed message
Returns
thread_module::error object
Definition at line 233 of file error_codes.h.
References logger_system::error, and logger_error_to_string().
Referenced by logger_module::logger::impl::add_writer(), logger_module::performance_tuning_strategy::can_apply(), logger_module::composite_strategy::can_apply(), logger_module::console_writer::flush(), logger_module::file_writer::flush(), logger_module::network_writer::flush(), make_error(), logger_module::file_writer::open(), logger_module::lightweight_di_container< T >::register_factory(), logger_module::lightweight_di_container< T >::register_singleton(), logger_module::logger::impl::reset_metrics(), logger_module::logger_config::validate(), logger_module::async_writer::write(), logger_module::batch_writer::write(), logger_module::console_writer::write(), logger_module::encrypted_writer::write(), and logger_module::file_writer::write().
metric_type_to_string()
std::string logger_module::metric_type_to_string (metric_type type) inline
Convert metric type to string.
Parameters
type The metric type
Returns
String representation
Definition at line 307 of file monitoring_interface.h.
References counter, gauge, histogram, and summary.
Variable Documentation
g_instance
logger_crash_safety* logger_module::g_instance = nullptr static
Definition at line 41 of file crash_safety.cpp.
g_instance_mutex
std::mutex logger_module::g_instance_mutex static
Definition at line 42 of file crash_safety.cpp.