Logger System: logger_module::v1_compat::logger_config_v1 Struct Reference
logger_module::v1_compat::logger_config_v1 Struct Reference
Legacy logger configuration structure.
#include <logger_v1_compat.h>
Public Member Functions
std::shared_ptr< logger > create () const
Apply configuration to create logger.
Public Attributes
log_level level = log_level::info
bool async = false
size_t buffer_size = 8192
std::string pattern = "[%time%] [%level%] %message%"
bool colored = true
Detailed Description
Legacy logger configuration structure.
Deprecated:
Use logger_builder for configuration
Definition at line 233 of file logger_v1_compat.h.
Member Function Documentation
create()
std::shared_ptr< logger > logger_module::v1_compat::logger_config_v1::create () const inline
Apply configuration to create logger.
Deprecated:
Use logger_builder directly
Definition at line 245 of file logger_v1_compat.h.
References logger_module::logger_builder::add_writer(), logger_module::logger_builder::build(), logger_module::logger_builder::with_async(), logger_module::logger_builder::with_buffer_size(), and logger_module::logger_builder::with_min_level().
Member Data Documentation
async
bool logger_module::v1_compat::logger_config_v1::async = false
Definition at line 235 of file logger_v1_compat.h.
buffer_size
size_t logger_module::v1_compat::logger_config_v1::buffer_size = 8192
Definition at line 236 of file logger_v1_compat.h.
colored
bool logger_module::v1_compat::logger_config_v1::colored = true
Definition at line 238 of file logger_v1_compat.h.
level
log_level logger_module::v1_compat::logger_config_v1::level = log_level::info
Definition at line 234 of file logger_v1_compat.h.
pattern
std::string logger_module::v1_compat::logger_config_v1::pattern = "[%time%] [%level%] %message%"
Definition at line 237 of file logger_v1_compat.h.
The documentation for this struct was generated from the following file:
/home/runner/work/logger_system/logger_system/sources/logger/compatibility/logger_v1_compat.h