var searchData=
[
  ['factory_20methods_0',['Static Factory Methods',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md133',1,'']]],
  ['failures_1',['Recent Test Failures',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md87',1,'']]],
  ['failures_20last_207_20days_2',['Build Failures (Last 7 Days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md92',1,'']]],
  ['faq_3',['FAQ',['../index.html#autotoc_md62',1,'']]],
  ['feature_20additions_4',['Feature Additions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md468',1,'']]],
  ['feature_20flags_5',['CMake Feature Flags',['../index.html#autotoc_md38',1,'']]],
  ['feature_20migration_202_203_20days_6',['Phase 3: Feature Migration (2-3 days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md387',1,'']]],
  ['features_7',['features',['../index.html#autotoc_md26',1,'Advanced Features'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md179',1,'Advanced Features'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md444',1,'Advanced Features'],['../index.html#autotoc_md24',1,'Core Features'],['../index.html#autotoc_md23',1,'Features'],['../index.html#autotoc_md53',1,'Security Features']]],
  ['features_20strong_8',['📈 &lt;strong&gt;Enterprise-Ready Features&lt;/strong&gt;',['../index.html#autotoc_md16',1,'']]],
  ['fetchcontent_20recommended_9',['Using CMake FetchContent (Recommended)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md340',1,'']]],
  ['file_20writer_10',['file writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md108',1,'1. File Writer'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md109',1,'2. Rotating File Writer']]],
  ['file_20writers_11',['File Writers',['../index.html#autotoc_md50',1,'']]],
  ['files_12',['files',['../index.html#autotoc_md35',1,'Configuration Files'],['../index.html#autotoc_md33',1,'Core Module Files'],['../index.html#autotoc_md34',1,'Writer Files']]],
  ['files_20and_20their_20purpose_20strong_13',['📖 &lt;strong&gt;Key Files and Their Purpose&lt;/strong&gt;',['../index.html#autotoc_md32',1,'']]],
  ['filter_20interface_14',['Filter Interface',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md441',1,'']]],
  ['filtering_15',['3. Level Filtering',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md412',1,'']]],
  ['filtering_20and_20routing_16',['Advanced Filtering and Routing',['../index.html#autotoc_md49',1,'']]],
  ['filtering_20by_20level_17',['Filtering by Level',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md348',1,'']]],
  ['filtering_20writer_18',['1. Filtering Writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md113',1,'']]],
  ['filters_19',['filters',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md464',1,'Custom Filters'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md164',1,'Filters']]],
  ['fixed_20',['Fixed',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md248',1,'']]],
  ['flags_21',['CMake Feature Flags',['../index.html#autotoc_md38',1,'']]],
  ['flow_20interface_20contracts_22',['🔄 Dependency Flow &amp; Interface Contracts',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md207',1,'']]],
  ['flush_20tt_23',['&lt;tt&gt;flush&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md127',1,'']]],
  ['for_20contributors_24',['For Contributors',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md472',1,'']]],
  ['for_20existing_20users_202025_2009_2010_25',['[2.9.0] - Phase 5 P2 Migration Guide for Existing Users (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md237',1,'']]],
  ['for_20library_20users_26',['For Library Users',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md471',1,'']]],
  ['for_20other_20libraries_27',['Wrapper for Other Libraries',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md383',1,'']]],
  ['for_20testing_28',['1. Mock Logger for Testing',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md324',1,'']]],
  ['format_29',['3. Commit Message Format',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md284',1,'']]],
  ['formatter_20interface_30',['Formatter Interface',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md442',1,'']]],
  ['formatters_31',['formatters',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md465',1,'Custom Formatters'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md168',1,'Formatters'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md395',1,'Issue 5: Custom Formatters']]],
  ['formatting_32',['formatting',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md420',1,'2. Excessive String Formatting'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md287',1,'Code Formatting']]],
  ['foundation_33',['1. thread_system (Foundation)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md188',1,'']]],
  ['foundation_20complete_34',['Phase 1 - Foundation (Complete)',['../index.html#autotoc_md4',1,'']]],
  ['foundation_20complete_202025_2009_2009_35',['[2.1.0] - Phase 1 Foundation Complete (2025-09-09)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md271',1,'']]],
  ['foundation_20strong_36',['🏗️ &lt;strong&gt;Modern C++ Foundation&lt;/strong&gt;',['../index.html#autotoc_md28',1,'']]],
  ['from_20boost_20log_37',['From Boost.Log',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md378',1,'']]],
  ['from_20google_20glog_38',['From Google glog',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md379',1,'']]],
  ['from_20ini_20xml_20configuration_39',['From INI/XML Configuration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md373',1,'']]],
  ['from_20log4cpp_40',['From log4cpp',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md380',1,'']]],
  ['from_20other_20libraries_41',['Migration from Other Libraries',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md375',1,'']]],
  ['from_20source_42',['Building from Source',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md341',1,'']]],
  ['from_20spdlog_43',['From spdlog',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md376',1,'']]],
  ['from_20v1_200_44',['Migration from v1.0',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md184',1,'']]],
  ['from_20v1_20x_20to_20v2_20x_45',['From v1.x to v2.x',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md363',1,'']]],
  ['functions_46',['Helper Functions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md159',1,'']]],
  ['further_20reading_47',['Further Reading',['../index.html#autotoc_md63',1,'']]],
  ['future_20enhancements_48',['Future Enhancements',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md466',1,'']]],
  ['future_20roadmap_49',['🔮 Future Roadmap',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md231',1,'']]]
];
