var searchData=
[
  ['factory_20methods_0',['Static Factory Methods',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md101',1,'']]],
  ['failures_1',['Recent Test Failures',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md55',1,'']]],
  ['failures_20last_207_20days_2',['Build Failures (Last 7 Days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md60',1,'']]],
  ['faq_3',['FAQ',['../index.html#autotoc_md39',1,'']]],
  ['feature_20additions_4',['Feature Additions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md436',1,'']]],
  ['feature_20flags_5',['CMake Feature Flags',['../index.html#autotoc_md15',1,'']]],
  ['feature_20migration_202_203_20days_6',['Phase 3: Feature Migration (2-3 days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md355',1,'']]],
  ['features_7',['features',['../index.html#autotoc_md13',1,'Advanced Features'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md147',1,'Advanced Features'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md412',1,'Advanced Features'],['../index.html#autotoc_md11',1,'Core Features'],['../index.html#autotoc_md10',1,'Features'],['../index.html#autotoc_md30',1,'Security Features']]],
  ['fetchcontent_20recommended_8',['Using CMake FetchContent (Recommended)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md308',1,'']]],
  ['file_20writer_9',['file writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md76',1,'1. File Writer'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md77',1,'2. Rotating File Writer']]],
  ['file_20writers_10',['File Writers',['../index.html#autotoc_md27',1,'']]],
  ['filter_20interface_11',['Filter Interface',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md409',1,'']]],
  ['filtering_12',['3. Level Filtering',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md380',1,'']]],
  ['filtering_20and_20routing_13',['Advanced Filtering and Routing',['../index.html#autotoc_md26',1,'']]],
  ['filtering_20by_20level_14',['Filtering by Level',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md316',1,'']]],
  ['filtering_20writer_15',['1. Filtering Writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md81',1,'']]],
  ['filters_16',['filters',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md432',1,'Custom Filters'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md132',1,'Filters']]],
  ['fixed_17',['Fixed',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md216',1,'']]],
  ['flags_18',['CMake Feature Flags',['../index.html#autotoc_md15',1,'']]],
  ['flow_20interface_20contracts_19',['🔄 Dependency Flow &amp; Interface Contracts',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md175',1,'']]],
  ['flush_20tt_20',['&lt;tt&gt;flush&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md95',1,'']]],
  ['for_20contributors_21',['For Contributors',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md440',1,'']]],
  ['for_20existing_20users_202025_2009_2010_22',['[2.9.0] - Phase 5 P2 Migration Guide for Existing Users (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md205',1,'']]],
  ['for_20library_20users_23',['For Library Users',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md439',1,'']]],
  ['for_20other_20libraries_24',['Wrapper for Other Libraries',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md351',1,'']]],
  ['for_20testing_25',['1. Mock Logger for Testing',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md292',1,'']]],
  ['format_26',['3. Commit Message Format',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md252',1,'']]],
  ['formatter_20interface_27',['Formatter Interface',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md410',1,'']]],
  ['formatters_28',['formatters',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md433',1,'Custom Formatters'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md136',1,'Formatters'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md363',1,'Issue 5: Custom Formatters']]],
  ['formatting_29',['formatting',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md388',1,'2. Excessive String Formatting'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md255',1,'Code Formatting']]],
  ['foundation_30',['1. thread_system (Foundation)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md156',1,'']]],
  ['foundation_20complete_31',['Phase 1 - Foundation (Complete)',['../index.html#autotoc_md4',1,'']]],
  ['foundation_20complete_202025_2009_2009_32',['[2.1.0] - Phase 1 Foundation Complete (2025-09-09)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md239',1,'']]],
  ['from_20boost_20log_33',['From Boost.Log',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md346',1,'']]],
  ['from_20google_20glog_34',['From Google glog',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md347',1,'']]],
  ['from_20ini_20xml_20configuration_35',['From INI/XML Configuration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md341',1,'']]],
  ['from_20log4cpp_36',['From log4cpp',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md348',1,'']]],
  ['from_20other_20libraries_37',['Migration from Other Libraries',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md343',1,'']]],
  ['from_20source_38',['Building from Source',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md309',1,'']]],
  ['from_20spdlog_39',['From spdlog',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md344',1,'']]],
  ['from_20v1_200_40',['Migration from v1.0',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md152',1,'']]],
  ['from_20v1_20x_20to_20v2_20x_41',['From v1.x to v2.x',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md331',1,'']]],
  ['functions_42',['Helper Functions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md127',1,'']]],
  ['further_20reading_43',['Further Reading',['../index.html#autotoc_md40',1,'']]],
  ['future_20enhancements_44',['Future Enhancements',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md434',1,'']]],
  ['future_20roadmap_45',['🔮 Future Roadmap',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md199',1,'']]]
];
