var searchData=
[
  ['ecosystem_20architecture_0',['Threading Ecosystem Architecture',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html',1,'']]],
  ['ecosystem_20expansion_1',['Phase 3: Ecosystem Expansion',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md238',1,'']]],
  ['ecosystem_20integration_2',['🔗 Ecosystem Integration',['../index.html#autotoc_md7',1,'']]],
  ['ecosystem_20overview_3',['🏗️ Ecosystem Overview',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md190',1,'']]],
  ['edge_20case_20testing_4',['Issue ARC-005: DI Edge Case Testing',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2ARCHITECTURE__ISSUES.html#autotoc_md254',1,'']]],
  ['enable_5fmetrics_5fcollection_20tt_5',['&lt;tt&gt;enable_metrics_collection&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md130',1,'']]],
  ['enabled_6',['Coverage (if enabled)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md668',1,'']]],
  ['enabled_20sanitizers_7',['Enabled Sanitizers',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SANITIZER__BASELINE.html#autotoc_md754',1,'']]],
  ['encryption_8',['Log Encryption',['../index.html#autotoc_md52',1,'']]],
  ['engineers_9',['Performance Engineers',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md743',1,'']]],
  ['enhanced_10',['enhanced',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md335',1,'Enhanced'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md339',1,'Enhanced']]],
  ['enhanced_20architecture_20new_20in_20phase_201_11',['Enhanced Architecture (New in Phase 1)',['../index.html#autotoc_md23',1,'']]],
  ['enhancement_12',['Phase 2: Enhancement',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md237',1,'']]],
  ['enhancements_13',['enhancements',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md589',1,'Future Enhancements'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md351',1,'Test Coverage Enhancements']]],
  ['enterprise_20ready_20features_20strong_14',['📈 &lt;strong&gt;Enterprise-Ready Features&lt;/strong&gt;',['../index.html#autotoc_md14',1,'']]],
  ['entry_20structure_15',['5. Log Entry Structure',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md566',1,'']]],
  ['environment_16',['environment',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2BASELINE.html#autotoc_md283',1,'Measurement Environment'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md527',1,'Test Environment']]],
  ['environment_20based_20configuration_17',['environment based configuration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md187',1,'Environment-based Configuration'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md497',1,'Environment-based Configuration']]],
  ['environment_20setup_18',['1. Development Environment Setup',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md227',1,'']]],
  ['environment_20specific_20configuration_19',['Environment-Specific Configuration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md430',1,'']]],
  ['error_20codes_20',['Error Codes',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md162',1,'']]],
  ['error_20handling_21',['error handling',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md438',1,'Error Handling'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md178',1,'Error Handling'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md161',1,'Error Handling']]],
  ['error_20handling_20migration_22',['1. Error Handling Migration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md487',1,'']]],
  ['error_20handling_20with_20result_20pattern_23',['error handling with result pattern',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md569',1,'2. Error Handling with Result Pattern'],['../index.html#autotoc_md43',1,'Error Handling with Result Pattern']]],
  ['error_20recovery_24',['Error Recovery',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md440',1,'']]],
  ['errors_25',['Issue: Circular Dependency Errors',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md629',1,'']]],
  ['established_26',['Documentation Established',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md658',1,'']]],
  ['evaluation_27',['2. Lazy Evaluation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md435',1,'']]],
  ['evolution_3a_20monolithic_20→_20modular_28',['🔄 Evolution: Monolithic → Modular',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md222',1,'']]],
  ['example_29',['Unit Test Example',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md621',1,'']]],
  ['example_201_3a_20basic_20monitor_20injection_30',['Example 1: Basic Monitor Injection',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md604',1,'']]],
  ['example_202_3a_20runtime_20monitor_20injection_31',['Example 2: Runtime Monitor Injection',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md605',1,'']]],
  ['example_203_3a_20optional_20monitoring_32',['Example 3: Optional Monitoring',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md606',1,'']]],
  ['example_204_3a_20using_20imonitorable_20interface_33',['Example 4: Using IMonitorable Interface',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md607',1,'']]],
  ['examples_34',['examples',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md637',1,'Examples'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2ARCHITECTURE__ISSUES.html#autotoc_md259',1,'Issue ARC-008: Missing Integration Examples'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md603',1,'Migration Examples'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md111',1,'Simple Examples'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md176',1,'Usage Examples']]],
  ['examples_20p2_20low_35',['Priority 1: Add Resource Guard Examples (P2 - Low)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md714',1,'']]],
  ['excellence_20strong_36',['🚀 &lt;strong&gt;Performance Excellence&lt;/strong&gt;',['../index.html#autotoc_md10',1,'']]],
  ['exception_20safety_37',['exception safety',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md686',1,'5. Exception Safety'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md515',1,'Issue 2: Exception Safety']]],
  ['excessive_20string_20formatting_38',['2. Excessive String Formatting',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md543',1,'']]],
  ['execution_39',['Test Execution',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md652',1,'']]],
  ['execution_20stats_20last_2030_20days_40',['Workflow Execution Stats (Last 30 Days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md101',1,'']]],
  ['execution_20summary_41',['Test Execution Summary',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md90',1,'']]],
  ['executive_20summary_42',['executive summary',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md676',1,'Executive Summary'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SANITIZER__BASELINE.html#autotoc_md751',1,'Executive Summary'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2BASELINE.html#autotoc_md281',1,'Executive Summary'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CURRENT__STATE.html#autotoc_md397',1,'Executive Summary']]],
  ['exemptions_43',['Exemptions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SANITIZER__BASELINE.html#autotoc_md770',1,'']]],
  ['existing_20users_44',['Existing Users',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md741',1,'']]],
  ['existing_20users_202025_2009_2010_45',['[2.9.0] - Phase 5 P2 Migration Guide for Existing Users (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md332',1,'']]],
  ['expansion_46',['Phase 3: Ecosystem Expansion',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md238',1,'']]],
  ['extension_20points_47',['Extension Points',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md585',1,'']]],
  ['extensions_48',['Platform Extensions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md592',1,'']]],
  ['external_20dependencies_49',['External Dependencies',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md99',1,'']]],
  ['external_20profiling_50',['External Profiling',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md547',1,'']]],
  ['external_20resources_51',['📖 External Resources',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md746',1,'']]]
];
