var searchData=
[
  ['a_20package_0',['Using as a Package',['../index.html#autotoc_md37',1,'']]],
  ['a4_20complete_1',['Added - Phase 3 Task A4 Complete',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md266',1,'']]],
  ['access_20control_2',['access control',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md343',1,'2. Access Control'],['../index.html#autotoc_md54',1,'Access Control']]],
  ['accomplishments_3',['Phase 0 Accomplishments',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md555',1,'']]],
  ['acknowledgments_4',['Acknowledgments',['../index.html#autotoc_md73',1,'']]],
  ['add_5ffilter_20tt_5',['&lt;tt&gt;add_filter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md148',1,'']]],
  ['add_5fwriter_20tt_6',['add_writer tt',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md123',1,'&lt;tt&gt;add_writer&lt;/tt&gt;'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md147',1,'&lt;tt&gt;add_writer&lt;/tt&gt;']]],
  ['added_7',['added',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md275',1,'Added'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md271',1,'Added']]],
  ['added_20all_20phase_202_20tasks_20complete_8',['Added - All Phase 2 Tasks Complete',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md269',1,'']]],
  ['added_20phase_203_20task_20a4_20complete_9',['Added - Phase 3 Task A4 Complete',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md266',1,'']]],
  ['added_20phase_204_20tasks_20o1_20o3_20o4_20complete_10',['Added - Phase 4 Tasks O1, O3 &amp; O4 Complete',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md260',1,'']]],
  ['added_20phase_205_20task_20p1_20partial_20implementation_11',['Added - Phase 5 Task P1 Partial Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md254',1,'']]],
  ['added_20phase_205_20task_20p2_20complete_20implementation_12',['Added - Phase 5 Task P2 Complete Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md237',1,'']]],
  ['added_20phase_205_20task_20p3_20complete_20implementation_13',['Added - Phase 5 Task P3 Complete Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md241',1,'']]],
  ['added_20phase_205_20task_20p4_20complete_20implementation_14',['Added - Phase 5 Task P4 Complete Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md245',1,'']]],
  ['added_20phase_205_20task_20p5_20complete_20implementation_15',['Added - Phase 5 Task P5 Complete Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md249',1,'']]],
  ['additions_16',['Feature Additions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md490',1,'']]],
  ['advanced_20capabilities_17',['🔧 Advanced Capabilities',['../index.html#autotoc_md4',1,'']]],
  ['advanced_20features_18',['advanced features',['../index.html#autotoc_md24',1,'Advanced Features'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md466',1,'Advanced Features'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md178',1,'Advanced Features']]],
  ['advanced_20filtering_20and_20routing_19',['Advanced Filtering and Routing',['../index.html#autotoc_md47',1,'']]],
  ['advanced_20patterns_20',['Advanced Patterns',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md111',1,'']]],
  ['advanced_20topics_20tt_20docs_20advanced_20tt_21',['Advanced Topics (&lt;tt&gt;docs/advanced/&lt;/tt&gt;)',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md574',1,'']]],
  ['advanced_20tt_22',['Advanced Topics (&lt;tt&gt;docs/advanced/&lt;/tt&gt;)',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md574',1,'']]],
  ['advantages_20benefits_23',['Core Advantages &amp; Benefits',['../index.html#autotoc_md9',1,'']]],
  ['after_3a_20modular_20architecture_24',['After: Modular Architecture',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md219',1,'']]],
  ['aggregating_20multiple_20loggers_25',['Pattern 2: Aggregating Multiple Loggers',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md510',1,'']]],
  ['aggregation_26',['Pattern 3: Health Check Aggregation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md511',1,'']]],
  ['all_20phase_202_20tasks_20complete_27',['Added - All Phase 2 Tasks Complete',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md269',1,'']]],
  ['allocations_28',['1. Minimize Allocations',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md333',1,'']]],
  ['analysis_29',['analysis',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md88',1,'📈 Build Time Analysis'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2STATIC__ANALYSIS__BASELINE.html#autotoc_md603',1,'How to Run Analysis'],['../index.html#autotoc_md50',1,'Real-time Analysis'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md566',1,'Static Analysis'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md82',1,'Static Analysis']]],
  ['analysis_20baseline_30',['Static Analysis Baseline',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md554',1,'']]],
  ['analysis_20baseline_20logger_5fsystem_31',['Static Analysis Baseline - logger_system',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2STATIC__ANALYSIS__BASELINE.html',1,'']]],
  ['analysis_20configuration_32',['Static Analysis Configuration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md546',1,'']]],
  ['and_20monitoring_33',['Profiling and Monitoring',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md444',1,'']]],
  ['and_20resources_34',['Support and Resources',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md419',1,'']]],
  ['and_20routing_35',['Advanced Filtering and Routing',['../index.html#autotoc_md47',1,'']]],
  ['and_20solutions_36',['Common Issues and Solutions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md412',1,'']]],
  ['and_20their_20purpose_20strong_37',['📖 &lt;strong&gt;Key Files and Their Purpose&lt;/strong&gt;',['../index.html#autotoc_md30',1,'']]],
  ['anti_20patterns_38',['Performance Anti-patterns',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md440',1,'']]],
  ['api_39',['api',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md532',1,'Builder API'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md393',1,'Configuration API'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md391',1,'Core Logger API'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md534',1,'IMonitorable API'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md533',1,'Runtime API'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md392',1,'Writer API']]],
  ['api_20changes_40',['API Changes',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md390',1,'']]],
  ['api_20documentation_41',['api documentation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md242',1,'API Documentation'],['../index.html#autotoc_md64',1,'API Documentation']]],
  ['api_20documentation_202025_2009_2010_42',['[2.8.0] - Phase 5 P3 Complete API Documentation (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md240',1,'']]],
  ['api_20legacy_20support_43',['Traditional API (Legacy Support)',['../index.html#autotoc_md42',1,'']]],
  ['api_20migration_44',['4. Logging API Migration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md389',1,'']]],
  ['api_20overview_45',['Quick API Overview',['../index.html#autotoc_md66',1,'']]],
  ['api_20reference_46',['api reference',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md531',1,'API Reference'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html',1,'API Reference'],['../index.html#autotoc_md65',1,'Core API Reference']]],
  ['api_20wrapper_47',['Legacy API Wrapper',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md404',1,'']]],
  ['api_5freference_2emd_48',['API_REFERENCE.md',['../API__REFERENCE_8md.html',1,'']]],
  ['apis_49',['1. Use Interface Types in APIs',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md514',1,'']]],
  ['applications_20strong_50',['🎯 &lt;strong&gt;Ideal Applications&lt;/strong&gt;',['../index.html#autotoc_md16',1,'']]],
  ['architecture_51',['architecture',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md219',1,'After: Modular Architecture'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md218',1,'Before: Monolithic Architecture'],['../index.html#autotoc_md44',1,'Interface Architecture'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html',1,'Logger System Architecture'],['../index.html#autotoc_md25',1,'Technology Stack &amp; Architecture'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html',1,'Threading Ecosystem Architecture']]],
  ['architecture_20diagram_52',['Architecture Diagram',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md454',1,'']]],
  ['architecture_20highlights_53',['🏗️ Architecture Highlights',['../index.html#autotoc_md5',1,'']]],
  ['architecture_20new_20in_20phase_201_54',['Enhanced Architecture (New in Phase 1)',['../index.html#autotoc_md23',1,'']]],
  ['architecture_2emd_55',['architecture.md',['../architecture_8md.html',1,'']]],
  ['as_20a_20package_56',['Using as a Package',['../index.html#autotoc_md37',1,'']]],
  ['as_20installed_20package_57',['Using as Installed Package',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md364',1,'']]],
  ['async_20logging_20pattern_58',['4. Async Logging Pattern',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md336',1,'']]],
  ['async_20writer_20wrapper_59',['2. Async Writer Wrapper',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md113',1,'']]],
  ['asynchronous_20logging_60',['Synchronous vs Asynchronous Logging',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md372',1,'']]],
  ['asynchronous_20mode_61',['asynchronous mode',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md424',1,'Asynchronous Mode'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md473',1,'Asynchronous Mode']]],
  ['asynchronous_20pipeline_62',['1. Asynchronous Pipeline',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md467',1,'']]],
  ['at_20phase_200_20completion_63',['Known Issues at Phase 0 Completion',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md559',1,'']]],
  ['at_20runtime_64',['4. Check Capabilities at Runtime',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md517',1,'']]],
  ['average_20build_20times_65',['Average Build Times',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md89',1,'']]]
];
