var searchData=
[
  ['last_2030_20days_0',['Workflow Execution Stats (Last 30 Days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md101',1,'']]],
  ['last_207_20days_1',['Build Failures (Last 7 Days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md96',1,'']]],
  ['latest_20benchmark_20results_2',['Latest Benchmark Results',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md84',1,'']]],
  ['latest_20benchmarks_3',['Core Performance Metrics (Latest Benchmarks)',['../index.html#autotoc_md18',1,'']]],
  ['lazy_20evaluation_4',['2. Lazy Evaluation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md383',1,'']]],
  ['leaks_5',['1. Memory Leaks',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md403',1,'']]],
  ['leaks_20with_20raw_20pointers_6',['Issue 1: Memory Leaks with Raw Pointers',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md462',1,'']]],
  ['legacy_20api_20wrapper_7',['Legacy API Wrapper',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md453',1,'']]],
  ['legacy_20support_8',['Traditional API (Legacy Support)',['../index.html#autotoc_md42',1,'']]],
  ['level_9',['Filtering by Level',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md419',1,'']]],
  ['level_20filtering_10',['3. Level Filtering',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md483',1,'']]],
  ['levels_11',['Log Levels',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md418',1,'']]],
  ['libraries_12',['libraries',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md446',1,'Migration from Other Libraries'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md454',1,'Wrapper for Other Libraries']]],
  ['library_20users_13',['For Library Users',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md542',1,'']]],
  ['license_14',['License',['../index.html#autotoc_md77',1,'']]],
  ['lifetime_15',['Object Lifetime',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md526',1,'']]],
  ['limitations_16',['Important Limitations',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html#autotoc_md637',1,'']]],
  ['links_17',['🔗 Quick Links',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md105',1,'']]],
  ['linux_18',['Linux',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md498',1,'']]],
  ['local_20development_19',['2. Build Order (Local Development)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md228',1,'']]],
  ['location_20',['Logging with Source Location',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md416',1,'']]],
  ['lock_20free_20queue_20implementation_21',['Issue ARC-004: Lock-Free Queue Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2ARCHITECTURE__ISSUES.html#autotoc_md251',1,'']]],
  ['log_22',['From Boost.Log',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md449',1,'']]],
  ['log_20encryption_23',['Log Encryption',['../index.html#autotoc_md52',1,'']]],
  ['log_20entry_20structure_24',['5. Log Entry Structure',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md514',1,'']]],
  ['log_20injection_20prevention_25',['3. Log Injection Prevention',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md393',1,'']]],
  ['log_20levels_26',['Log Levels',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md418',1,'']]],
  ['log_20rotation_20strategy_27',['2. Log Rotation Strategy',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md400',1,'']]],
  ['log_20tt_28',['&lt;tt&gt;log&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md127',1,'']]],
  ['log4cpp_29',['From log4cpp',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md451',1,'']]],
  ['logger_20api_30',['Core Logger API',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md440',1,'']]],
  ['logger_20configuration_20with_20validation_31',['Logger Configuration with Validation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md507',1,'']]],
  ['logger_20for_20testing_32',['1. Mock Logger for Testing',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md395',1,'']]],
  ['logger_20interface_20implementation_33',['1. Logger Interface Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md505',1,'']]],
  ['logger_20system_34',['logger system',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html',1,'Contributing to Logger System'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html',1,'Getting Started with Logger System'],['../index.html',1,'Logger System']]],
  ['logger_20system_20architecture_35',['Logger System Architecture',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html',1,'']]],
  ['logger_20system_20best_20practices_20guide_36',['Logger System Best Practices Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html',1,'']]],
  ['logger_20system_20ci_20cd_20dashboard_37',['Logger System CI/CD Dashboard',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html',1,'']]],
  ['logger_20system_20migration_20guide_38',['Logger System Migration Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html',1,'']]],
  ['logger_20system_20performance_20guide_39',['Logger System Performance Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html',1,'']]],
  ['logger_20system_20project_40',['Logger System Project',['../index.html#autotoc_md0',1,'']]],
  ['logger_5fmodule_3a_3acompact_5fformatter_20tt_41',['&lt;tt&gt;logger_module::compact_formatter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md175',1,'']]],
  ['logger_5fmodule_3a_3aconsole_5fwriter_20tt_42',['&lt;tt&gt;logger_module::console_writer&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md165',1,'']]],
  ['logger_5fmodule_3a_3afile_5fwriter_20tt_43',['&lt;tt&gt;logger_module::file_writer&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md166',1,'']]],
  ['logger_5fmodule_3a_3afunction_5ffilter_20tt_44',['&lt;tt&gt;logger_module::function_filter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md171',1,'']]],
  ['logger_5fmodule_3a_3ajson_5fformatter_20tt_45',['&lt;tt&gt;logger_module::json_formatter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md174',1,'']]],
  ['logger_5fmodule_3a_3alevel_5ffilter_20tt_46',['&lt;tt&gt;logger_module::level_filter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md169',1,'']]],
  ['logger_5fmodule_3a_3alog_5fentry_20tt_47',['&lt;tt&gt;logger_module::log_entry&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md160',1,'']]],
  ['logger_5fmodule_3a_3alog_5ffilter_5finterface_20tt_48',['&lt;tt&gt;logger_module::log_filter_interface&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md158',1,'']]],
  ['logger_5fmodule_3a_3alog_5fformatter_5finterface_20tt_49',['&lt;tt&gt;logger_module::log_formatter_interface&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md159',1,'']]],
  ['logger_5fmodule_3a_3alog_5fwriter_5finterface_20tt_50',['&lt;tt&gt;logger_module::log_writer_interface&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md157',1,'']]],
  ['logger_5fmodule_3a_3alogger_20tt_51',['&lt;tt&gt;logger_module::logger&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md124',1,'']]],
  ['logger_5fmodule_3a_3alogger_5fbuilder_20tt_52',['&lt;tt&gt;logger_module::logger_builder&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md144',1,'']]],
  ['logger_5fmodule_3a_3alogger_5fconfig_20tt_53',['&lt;tt&gt;logger_module::logger_config&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md133',1,'']]],
  ['logger_5fmodule_3a_3aplain_5fformatter_20tt_54',['&lt;tt&gt;logger_module::plain_formatter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md173',1,'']]],
  ['logger_5fmodule_3a_3aregex_5ffilter_20tt_55',['&lt;tt&gt;logger_module::regex_filter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md170',1,'']]],
  ['logger_5fmodule_3a_3arotating_5ffile_5fwriter_20tt_56',['&lt;tt&gt;logger_module::rotating_file_writer&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md167',1,'']]],
  ['logger_5fsystem_57',['logger_system',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md232',1,'logger_system'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html',1,'Phase 0 Baseline - logger_system'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2STATIC__ANALYSIS__BASELINE.html',1,'Static Analysis Baseline - logger_system']]],
  ['logger_5fsystem_20logging_58',['2. logger_system (Logging)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md197',1,'']]],
  ['logger_5fsystem_5farchitecture_2emd_59',['LOGGER_SYSTEM_ARCHITECTURE.md',['../LOGGER__SYSTEM__ARCHITECTURE_8md.html',1,'']]],
  ['loggers_60',['Pattern 2: Aggregating Multiple Loggers',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md559',1,'']]],
  ['logging_61',['logging',['../index.html#autotoc_md3',1,'🎯 High-Performance Logging'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md197',1,'2. logger_system (Logging)'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md185',1,'Contextual Logging'],['../index.html#autotoc_md49',1,'Distributed Logging'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md415',1,'Simple Console Logging'],['../index.html#autotoc_md46',1,'Structured Logging'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md184',1,'Structured Logging'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md421',1,'Synchronous vs Asynchronous Logging']]],
  ['logging_20api_20migration_62',['4. Logging API Migration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md438',1,'']]],
  ['logging_20in_20tight_20loops_63',['3. Logging in Tight Loops',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md492',1,'']]],
  ['logging_20pattern_64',['4. Async Logging Pattern',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md385',1,'']]],
  ['logging_20with_20source_20location_65',['Logging with Source Location',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md416',1,'']]],
  ['loops_66',['3. Logging in Tight Loops',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md492',1,'']]],
  ['low_20priority_20p2_67',['Low Priority (P2)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CURRENT__STATE.html#autotoc_md367',1,'']]],
  ['low_5flatency_20tt_68',['&lt;tt&gt;low_latency&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md142',1,'']]]
];
