var searchData=
[
  ['예상_20결과물_0',['📈 예상 결과물',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2performance_2CI__CD__PERFORMANCE__PROPOSAL.html#autotoc_md1322',1,'']]],
  ['예상_20소요_3a_201시간_1',['예상 소요: 1시간',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2performance_2CI__CD__PERFORMANCE__PROPOSAL.html#autotoc_md1330',1,'Phase 3: README 자동 업데이트 (예상 소요: 1시간)'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2performance_2CI__CD__PERFORMANCE__PROPOSAL.html#autotoc_md1333',1,'Phase 6: 문서화 (예상 소요: 1시간)']]],
  ['예상_20소요_3a_201_205시간_2',['예상 소요: 1 5시간',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2performance_2CI__CD__PERFORMANCE__PROPOSAL.html#autotoc_md1329',1,'Phase 2: 배지 및 차트 (예상 소요: 1.5시간)'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2performance_2CI__CD__PERFORMANCE__PROPOSAL.html#autotoc_md1332',1,'Phase 5: 테스트 및 검증 (예상 소요: 1.5시간)']]],
  ['예상_20소요_3a_202시간_3',['예상 소요: 2시간',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2performance_2CI__CD__PERFORMANCE__PROPOSAL.html#autotoc_md1328',1,'Phase 1: 인프라 구축 (예상 소요: 2시간)'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2performance_2CI__CD__PERFORMANCE__PROPOSAL.html#autotoc_md1331',1,'Phase 4: CI/CD 통합 (예상 소요: 2시간)']]],
  ['예시_4',['예시',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2performance_2CI__CD__PERFORMANCE__PROPOSAL.html#autotoc_md1343',1,'관련 프로젝트 예시'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2FEATURES__KO.html#autotoc_md957',1,'구성 예시'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2FEATURES__KO.html#autotoc_md925',1,'사용 예시'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2performance_2CI__CD__PERFORMANCE__PROPOSAL.html#autotoc_md1320',1,'🔄 CI/CD 워크플로우 전체 예시']]],
  ['예외_20안전성_5',['예외 안전성',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PRODUCTION__QUALITY__KO.html#autotoc_md1451',1,'']]]
];
