var searchData=
[
  ['ubuntu_20clang_20build_0',['2. Ubuntu Clang Build',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CURRENT__STATE.html#autotoc_md506',1,'']]],
  ['ubuntu_20gcc_20build_1',['1. Ubuntu GCC Build',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CURRENT__STATE.html#autotoc_md505',1,'']]],
  ['undefinedbehaviorsanitizer_2',['UndefinedBehaviorSanitizer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SANITIZER__BASELINE.html#autotoc_md910',1,'']]],
  ['undefinedbehaviorsanitizer_20warnings_3',['UndefinedBehaviorSanitizer Warnings',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SANITIZER__BASELINE.html#autotoc_md905',1,'']]],
  ['unit_20test_20example_4',['Unit Test Example',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md719',1,'']]],
  ['unit_20tests_5',['unit tests',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md386',1,'Unit Tests'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__3__PREPARATION.html#autotoc_md862',1,'Unit Tests']]],
  ['update_6',['📊 Dashboard Update',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md107',1,'']]],
  ['update_20this_20document_7',['Update This Document',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2BASELINE.html#autotoc_md318',1,'']]],
  ['updates_8',['updates',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md391',1,'Documentation Updates'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__3__PREPARATION.html#autotoc_md848',1,'Test Updates']]],
  ['usage_9',['usage',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md564',1,'Basic Usage'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md178',1,'Basic Usage'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md628',1,'Memory Usage'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md103',1,'Resource Usage'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md794',1,'std::unique_ptr Usage']]],
  ['usage_20example_3a_10',['usage example:',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md410',1,'Usage Example:'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md407',1,'Usage Example:']]],
  ['usage_20examples_11',['Usage Examples',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md177',1,'']]],
  ['usage_20scenarios_12',['📊 3 Usage Scenarios',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOGGING__QUICK__START.html#autotoc_md472',1,'']]],
  ['usage_3a_13',['WAL Usage:',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md418',1,'']]],
  ['use_20cases_14',['Real-World Impact &amp; Use Cases',['../index.html#autotoc_md15',1,'']]],
  ['use_20hybrid_20writer_15',['Strategy 3: Use Hybrid Writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md433',1,'']]],
  ['use_20interface_20types_20in_20apis_16',['1. Use Interface Types in APIs',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md713',1,'']]],
  ['use_20monitor_20providers_17',['3. Use Monitor Providers',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md715',1,'']]],
  ['use_20wal_18',['Q2: When should I use WAL?',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md454',1,'']]],
  ['use_5ftemplate_20tt_19',['&lt;tt&gt;use_template&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md148',1,'']]],
  ['users_20',['users',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md887',1,'Existing Users'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md692',1,'For Library Users'],['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md886',1,'New Users']]],
  ['users_202025_2009_2010_21',['[2.9.0] - Phase 5 P2 Migration Guide for Existing Users (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md333',1,'']]],
  ['using_20as_20a_20package_22',['Using as a Package',['../index.html#autotoc_md37',1,'']]],
  ['using_20as_20installed_20package_23',['Using as Installed Package',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md563',1,'']]],
  ['using_20cmake_20fetchcontent_20recommended_24',['Using CMake FetchContent (Recommended)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md561',1,'']]],
  ['using_20imonitorable_20interface_25',['Example 4: Using IMonitorable Interface',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md705',1,'']]],
  ['using_20service_20container_26',['Using Service Container',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md576',1,'']]]
];
