var searchData=
[
  ['raw_20pointers_0',['Issue 1: Memory Leaks with Raw Pointers',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md392',1,'']]],
  ['reading_1',['Further Reading',['../index.html#autotoc_md63',1,'']]],
  ['readme_2emd_2',['readme.md',['../README_8md.html',1,'(Global Namespace)'],['../docs_2README_8md.html',1,'(Global Namespace)']]],
  ['ready_20features_20strong_3',['📈 &lt;strong&gt;Enterprise-Ready Features&lt;/strong&gt;',['../index.html#autotoc_md16',1,'']]],
  ['real_20time_20analysis_4',['Real-time Analysis',['../index.html#autotoc_md52',1,'']]],
  ['real_20world_20impact_20use_20cases_5',['Real-World Impact &amp; Use Cases',['../index.html#autotoc_md17',1,'']]],
  ['receiving_20metrics_6',['Issue: Monitor Not Receiving Metrics',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md506',1,'']]],
  ['recent_20changes_7',['Recent Changes',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md530',1,'']]],
  ['recent_20improvements_8',['🚀 Recent Improvements',['../index.html#autotoc_md2',1,'']]],
  ['recent_20issues_9',['🚨 Recent Issues',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md92',1,'']]],
  ['recent_20releases_10',['Recent Releases',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md101',1,'']]],
  ['recent_20test_20failures_11',['Recent Test Failures',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md88',1,'']]],
  ['recommendations_12',['Recommendations',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md503',1,'']]],
  ['recommendations_20production_13',['Recommendations (Production)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html#autotoc_md538',1,'']]],
  ['recommended_14',['recommended',['../index.html#autotoc_md42',1,'Quick Start with Builder Pattern (Recommended)'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md341',1,'Using CMake FetchContent (Recommended)']]],
  ['reconfiguration_15',['Dynamic Reconfiguration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md310',1,'']]],
  ['recovery_16',['Error Recovery',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md318',1,'']]],
  ['refactoring_202025_2007_2026_17',['[2.0.0] - Major Refactoring (2025-07-26)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md274',1,'']]],
  ['reference_18',['reference',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md510',1,'API Reference'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html',1,'API Reference'],['../index.html#autotoc_md67',1,'Core API Reference']]],
  ['regressions_19',['Performance Regressions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md94',1,'']]],
  ['related_20projects_20',['Related Projects',['../index.html#autotoc_md7',1,'']]],
  ['release_202025_2007_2001_21',['[1.0.0] - Initial Release (2025-07-01)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md276',1,'']]],
  ['release_20history_22',['📅 Release History',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md100',1,'']]],
  ['releases_23',['Recent Releases',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md101',1,'']]],
  ['reliability_20strong_24',['🛡️ &lt;strong&gt;Production-Grade Reliability&lt;/strong&gt;',['../index.html#autotoc_md13',1,'']]],
  ['request_20process_25',['Pull Request Process',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md298',1,'']]],
  ['requirements_26',['requirements',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md211',1,'Build Order Requirements'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md339',1,'Requirements']]],
  ['resource_20usage_27',['Resource Usage',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md99',1,'']]],
  ['resources_28',['resources',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md531',1,'📖 External Resources'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md398',1,'Support and Resources']]],
  ['responsibilities_29',['📋 Project Roles &amp; Responsibilities',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md188',1,'']]],
  ['responsibilities_3a_30',['responsibilities:',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md200',1,'Responsibilities:'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md190',1,'Responsibilities:'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md195',1,'Responsibilities:'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md205',1,'Responsibilities:']]],
  ['responsibility_31',['1. Single Responsibility',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md304',1,'']]],
  ['result_20pattern_32',['result pattern',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md447',1,'2. Error Handling with Result Pattern'],['../index.html#autotoc_md45',1,'Error Handling with Result Pattern']]],
  ['results_33',['results',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md89',1,'🔥 Sanitizer Results'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md86',1,'🧪 Test Results'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md81',1,'Latest Benchmark Results']]],
  ['review_20process_34',['Review Process',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md299',1,'']]],
  ['right_20mode_35',['1. Choose the Right Mode',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md410',1,'']]],
  ['roadmap_36',['roadmap',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md232',1,'🔮 Future Roadmap'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html#autotoc_md540',1,'Roadmap']]],
  ['roles_20responsibilities_37',['📋 Project Roles &amp; Responsibilities',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md188',1,'']]],
  ['rotating_20file_20writer_38',['2. Rotating File Writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md110',1,'']]],
  ['rotation_20strategy_39',['2. Log Rotation Strategy',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md330',1,'']]],
  ['routing_40',['Advanced Filtering and Routing',['../index.html#autotoc_md49',1,'']]],
  ['running_20tests_41',['Running Tests',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md292',1,'']]],
  ['runtime_42',['4. Check Capabilities at Runtime',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md496',1,'']]],
  ['runtime_20api_43',['Runtime API',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md512',1,'']]],
  ['runtime_20monitor_20injection_44',['Example 2: Runtime Monitor Injection',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md483',1,'']]]
];
