var searchData=
[
  ['ecosystem_20architecture_0',['Threading Ecosystem Architecture',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html',1,'']]],
  ['ecosystem_20expansion_1',['Phase 3: Ecosystem Expansion',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md233',1,'']]],
  ['ecosystem_20integration_2',['🔗 Ecosystem Integration',['../index.html#autotoc_md7',1,'']]],
  ['ecosystem_20overview_3',['🏗️ Ecosystem Overview',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md185',1,'']]],
  ['enable_5fmetrics_5fcollection_20tt_4',['&lt;tt&gt;enable_metrics_collection&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md125',1,'']]],
  ['encryption_5',['Log Encryption',['../index.html#autotoc_md52',1,'']]],
  ['engineers_6',['Performance Engineers',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md526',1,'']]],
  ['enhanced_7',['enhanced',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md243',1,'Enhanced'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md239',1,'Enhanced']]],
  ['enhanced_20architecture_20new_20in_20phase_201_8',['Enhanced Architecture (New in Phase 1)',['../index.html#autotoc_md23',1,'']]],
  ['enhancement_9',['Phase 2: Enhancement',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md232',1,'']]],
  ['enhancements_10',['enhancements',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md465',1,'Future Enhancements'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md255',1,'Test Coverage Enhancements']]],
  ['enterprise_20ready_20features_20strong_11',['📈 &lt;strong&gt;Enterprise-Ready Features&lt;/strong&gt;',['../index.html#autotoc_md14',1,'']]],
  ['entry_20structure_12',['5. Log Entry Structure',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md442',1,'']]],
  ['environment_13',['Test Environment',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md403',1,'']]],
  ['environment_20based_20configuration_14',['environment based configuration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md182',1,'Environment-based Configuration'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md373',1,'Environment-based Configuration']]],
  ['environment_20setup_15',['1. Development Environment Setup',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md222',1,'']]],
  ['environment_20specific_20configuration_16',['Environment-Specific Configuration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md306',1,'']]],
  ['error_20codes_17',['Error Codes',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md157',1,'']]],
  ['error_20handling_18',['error handling',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md156',1,'Error Handling'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md314',1,'Error Handling'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md173',1,'Error Handling']]],
  ['error_20handling_20migration_19',['1. Error Handling Migration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md363',1,'']]],
  ['error_20handling_20with_20result_20pattern_20',['error handling with result pattern',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md445',1,'2. Error Handling with Result Pattern'],['../index.html#autotoc_md43',1,'Error Handling with Result Pattern']]],
  ['error_20recovery_21',['Error Recovery',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md316',1,'']]],
  ['errors_22',['Issue: Circular Dependency Errors',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md505',1,'']]],
  ['evaluation_23',['2. Lazy Evaluation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md311',1,'']]],
  ['evolution_3a_20monolithic_20→_20modular_24',['🔄 Evolution: Monolithic → Modular',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md217',1,'']]],
  ['example_25',['Unit Test Example',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md497',1,'']]],
  ['example_201_3a_20basic_20monitor_20injection_26',['Example 1: Basic Monitor Injection',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md480',1,'']]],
  ['example_202_3a_20runtime_20monitor_20injection_27',['Example 2: Runtime Monitor Injection',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md481',1,'']]],
  ['example_203_3a_20optional_20monitoring_28',['Example 3: Optional Monitoring',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md482',1,'']]],
  ['example_204_3a_20using_20imonitorable_20interface_29',['Example 4: Using IMonitorable Interface',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md483',1,'']]],
  ['examples_30',['examples',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md513',1,'Examples'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md479',1,'Migration Examples'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md106',1,'Simple Examples'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md171',1,'Usage Examples']]],
  ['excellence_20strong_31',['🚀 &lt;strong&gt;Performance Excellence&lt;/strong&gt;',['../index.html#autotoc_md10',1,'']]],
  ['exception_20safety_32',['Issue 2: Exception Safety',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md391',1,'']]],
  ['excessive_20string_20formatting_33',['2. Excessive String Formatting',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md419',1,'']]],
  ['execution_20stats_20last_2030_20days_34',['Workflow Execution Stats (Last 30 Days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md96',1,'']]],
  ['execution_20summary_35',['Test Execution Summary',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md85',1,'']]],
  ['existing_20users_36',['Existing Users',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md524',1,'']]],
  ['existing_20users_202025_2009_2010_37',['[2.9.0] - Phase 5 P2 Migration Guide for Existing Users (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md236',1,'']]],
  ['expansion_38',['Phase 3: Ecosystem Expansion',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md233',1,'']]],
  ['extension_20points_39',['Extension Points',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md461',1,'']]],
  ['extensions_40',['Platform Extensions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md468',1,'']]],
  ['external_20dependencies_41',['External Dependencies',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md94',1,'']]],
  ['external_20profiling_42',['External Profiling',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md423',1,'']]],
  ['external_20resources_43',['📖 External Resources',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md529',1,'']]]
];
