var searchData=
[
  ['safety_0',['safety',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md360',1,'Issue 2: Exception Safety'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md361',1,'Issue 3: Thread Safety'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md145',1,'Thread Safety']]],
  ['safety_20guarantees_1',['Thread Safety Guarantees',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md420',1,'']]],
  ['sanitization_2',['Sensitive Data Sanitization',['../index.html#autotoc_md32',1,'']]],
  ['sanitize_20sensitive_20data_3',['1. Sanitize Sensitive Data',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md288',1,'']]],
  ['sanitizer_20results_4',['🔥 Sanitizer Results',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md56',1,'']]],
  ['sanitizers_202025_2009_2009_5',['[2.6.0] - Phase 5 P5 CI/CD Pipeline with Sanitizers (2025-09-09)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md217',1,'']]],
  ['scope_6',['Threat Model (Scope)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html#autotoc_md458',1,'']]],
  ['secure_20configuration_20checklist_7',['Secure Configuration Checklist',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html#autotoc_md462',1,'']]],
  ['security_20considerations_8',['Security Considerations',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md287',1,'']]],
  ['security_20features_9',['Security Features',['../index.html#autotoc_md30',1,'']]],
  ['security_20guide_10',['Security Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html',1,'']]],
  ['security_2emd_11',['SECURITY.md',['../SECURITY_8md.html',1,'']]],
  ['segregation_12',['segregation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md273',1,'3. Interface Segregation'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md407',1,'4. Interface Segregation']]],
  ['sensitive_20data_13',['1. Sanitize Sensitive Data',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md288',1,'']]],
  ['sensitive_20data_20sanitization_14',['Sensitive Data Sanitization',['../index.html#autotoc_md32',1,'']]],
  ['service_20container_15',['Using Service Container',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md323',1,'']]],
  ['service_20container_20integration_16',['Service Container Integration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md428',1,'']]],
  ['set_5fmin_5flevel_20tt_17',['&lt;tt&gt;set_min_level&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md93',1,'']]],
  ['setup_18',['1. Development Environment Setup',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md191',1,'']]],
  ['shutdown_19',['3. Graceful Shutdown',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md298',1,'']]],
  ['simple_20console_20logging_20',['Simple Console Logging',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md312',1,'']]],
  ['simple_20examples_21',['Simple Examples',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md75',1,'']]],
  ['single_20responsibility_22',['1. Single Responsibility',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md271',1,'']]],
  ['single_20thread_20performance_23',['Single Thread Performance',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md373',1,'']]],
  ['size_20considerations_24',['2.1 Batch Size Considerations',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md379',1,'']]],
  ['size_20tuning_25',['2. Buffer Size Tuning',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md378',1,'']]],
  ['small_20string_20optimization_20o3_26',['Small String Optimization (O3)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md231',1,'']]],
  ['solutions_27',['Common Issues and Solutions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md358',1,'']]],
  ['source_28',['Building from Source',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md309',1,'']]],
  ['source_20location_29',['Logging with Source Location',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md313',1,'']]],
  ['spdlog_30',['From spdlog',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md344',1,'']]],
  ['spdlog_20pattern_20migration_31',['spdlog Pattern Migration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md345',1,'']]],
  ['specific_20configuration_32',['Environment-Specific Configuration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md275',1,'']]],
  ['specific_20optimizations_33',['Platform-Specific Optimizations',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md394',1,'']]],
  ['stabilization_20current_34',['Phase 1: Stabilization (Current)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md200',1,'']]],
  ['start_35',['start',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md250',1,'1. Before You Start'],['../index.html#autotoc_md18',1,'Quick Start']]],
  ['start_20with_20builder_20pattern_20recommended_36',['Quick Start with Builder Pattern (Recommended)',['../index.html#autotoc_md19',1,'']]],
  ['started_37',['started',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md190',1,'🚀 Getting Started'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md248',1,'Getting Started']]],
  ['started_20with_20logger_20system_38',['Getting Started with Logger System',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html',1,'']]],
  ['static_20analysis_39',['Static Analysis',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md51',1,'']]],
  ['static_20factory_20methods_40',['Static Factory Methods',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md101',1,'']]],
  ['stats_20last_2030_20days_41',['Workflow Execution Stats (Last 30 Days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md65',1,'']]],
  ['status_42',['status',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md62',1,'📝 Dependency Status'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md45',1,'🚀 Build Status']]],
  ['step_20by_20step_20migration_43',['Step-by-Step Migration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md352',1,'']]],
  ['steps_44',['Next Steps',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md325',1,'']]],
  ['strategies_45',['strategies',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md416',1,'4. Configuration Strategies'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md426',1,'Optimization Strategies'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md376',1,'Optimization Strategies'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md291',1,'Testing Strategies']]],
  ['strategy_46',['2. Log Rotation Strategy',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md297',1,'']]],
  ['stress_20testing_47',['3. Stress Testing',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md294',1,'']]],
  ['string_20formatting_48',['2. Excessive String Formatting',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md388',1,'']]],
  ['string_20optimization_20o3_49',['Small String Optimization (O3)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md231',1,'']]],
  ['structure_50',['structure',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md194',1,'📚 Documentation Structure'],['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md443',1,'📚 Documentation Structure'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md411',1,'5. Log Entry Structure']]],
  ['structured_20json_20output_51',['Structured JSON Output',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md314',1,'']]],
  ['structured_20logging_52',['structured logging',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md148',1,'Structured Logging'],['../index.html#autotoc_md25',1,'Structured Logging']]],
  ['style_53',['Code Style',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md253',1,'']]],
  ['submitting_20changes_54',['Submitting Changes',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md264',1,'']]],
  ['suite_202025_2009_2009_55',['[2.5.0] - Phase 5 P1 Comprehensive Test Suite (2025-09-09)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md222',1,'']]],
  ['suite_20o4_56',['Benchmark Suite (O4)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md232',1,'']]],
  ['summary_57',['summary',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md393',1,'Best Practices Summary'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md303',1,'Summary'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md54',1,'Test Execution Summary']]],
  ['summary_20v2_200_58',['Breaking Changes Summary (v2.0+)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md329',1,'']]],
  ['support_59',['support',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md455',1,'🤝 Help &amp; Support'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md207',1,'Migration Support'],['../index.html#autotoc_md38',1,'Platform Support'],['../index.html#autotoc_md21',1,'Traditional API (Legacy Support)']]],
  ['support_20and_20resources_60',['Support and Resources',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md365',1,'']]],
  ['synchronous_20i_20o_20in_20hot_20paths_61',['1. Synchronous I/O in Hot Paths',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md387',1,'']]],
  ['synchronous_20mode_62',['synchronous mode',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md369',1,'Synchronous Mode'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md418',1,'Synchronous Mode']]],
  ['synchronous_20vs_20asynchronous_20logging_63',['Synchronous vs Asynchronous Logging',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md318',1,'']]],
  ['system_64',['system',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html',1,'Contributing to Logger System'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html',1,'Getting Started with Logger System'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md322',1,'Integration with Thread System'],['../index.html#autotoc_md17',1,'Integration with Thread System'],['../index.html',1,'Logger System']]],
  ['system_20architecture_65',['Logger System Architecture',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html',1,'']]],
  ['system_20best_20practices_20guide_66',['Logger System Best Practices Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html',1,'']]],
  ['system_20ci_20cd_20dashboard_67',['Logger System CI/CD Dashboard',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html',1,'']]],
  ['system_20implementation_202025_2009_2010_68',['[2.3.0] - Phase 3 Overflow Policy System Implementation (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md234',1,'']]],
  ['system_20migration_20guide_69',['Logger System Migration Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html',1,'']]],
  ['system_20performance_20guide_70',['Logger System Performance Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html',1,'']]],
  ['systems_20complete_20100_20✅_71',['Phase 2 - Core Systems (Complete - 100% ✅)',['../index.html#autotoc_md3',1,'']]],
  ['systems_20complete_202025_2009_2009_72',['[2.2.0] - Phase 2 Core Systems Complete (2025-09-09)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md237',1,'']]]
];
