var searchData=
[
  ['table_20of_20contents_0',['table of contents',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md302',1,'Table of Contents'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md338',1,'Table of Contents'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md360',1,'Table of Contents'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md279',1,'Table of Contents'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md119',1,'Table of Contents']]],
  ['task_20a4_20complete_1',['Added - Phase 3 Task A4 Complete',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md268',1,'']]],
  ['task_20p1_20partial_20implementation_2',['Added - Phase 5 Task P1 Partial Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md256',1,'']]],
  ['task_20p2_20complete_20implementation_3',['Added - Phase 5 Task P2 Complete Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md239',1,'']]],
  ['task_20p3_20complete_20implementation_4',['Added - Phase 5 Task P3 Complete Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md243',1,'']]],
  ['task_20p4_20complete_20implementation_5',['Added - Phase 5 Task P4 Complete Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md247',1,'']]],
  ['task_20p5_20complete_20implementation_6',['Added - Phase 5 Task P5 Complete Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md251',1,'']]],
  ['tasks_20complete_7',['Added - All Phase 2 Tasks Complete',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md271',1,'']]],
  ['tasks_20o1_20o3_20o4_20complete_8',['Added - Phase 4 Tasks O1, O3 &amp; O4 Complete',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md262',1,'']]],
  ['technical_20debt_9',['Technical Debt',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md260',1,'']]],
  ['technical_20details_10',['technical details',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md266',1,'Technical Details'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md269',1,'Technical Details']]],
  ['technology_20stack_20architecture_11',['Technology Stack &amp; Architecture',['../index.html#autotoc_md27',1,'']]],
  ['templates_12',['templates',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md438',1,'Configuration Templates'],['../index.html#autotoc_md43',1,'Configuration Templates']]],
  ['test_20coverage_13',['Test Coverage',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md85',1,'']]],
  ['test_20coverage_20enhancements_14',['Test Coverage Enhancements',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md257',1,'']]],
  ['test_20environment_15',['Test Environment',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md405',1,'']]],
  ['test_20execution_20summary_16',['Test Execution Summary',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md87',1,'']]],
  ['test_20failures_17',['Recent Test Failures',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md88',1,'']]],
  ['test_20results_18',['🧪 Test Results',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md86',1,'']]],
  ['test_20suite_202025_2009_2009_19',['[2.5.0] - Phase 5 P1 Comprehensive Test Suite (2025-09-09)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md255',1,'']]],
  ['testing_20',['testing',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md325',1,'1. Mock Logger for Testing'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md326',1,'2. Performance Testing'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md327',1,'3. Stress Testing'],['../index.html#autotoc_md60',1,'Testing'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md290',1,'Testing']]],
  ['testing_20custom_20writers_21',['Testing Custom Writers',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md117',1,'']]],
  ['testing_20strategies_22',['Testing Strategies',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md324',1,'']]],
  ['tests_23',['tests',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md292',1,'Running Tests'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md291',1,'Unit Tests']]],
  ['the_20right_20mode_24',['1. Choose the Right Mode',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md410',1,'']]],
  ['their_20purpose_20strong_25',['📖 &lt;strong&gt;Key Files and Their Purpose&lt;/strong&gt;',['../index.html#autotoc_md32',1,'']]],
  ['thread_20performance_26',['Single Thread Performance',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md406',1,'']]],
  ['thread_20safety_27',['thread safety',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md394',1,'Issue 3: Thread Safety'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md178',1,'Thread Safety']]],
  ['thread_20safety_20guarantees_28',['Thread Safety Guarantees',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md453',1,'']]],
  ['thread_20system_29',['thread system',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md355',1,'Integration with Thread System'],['../index.html#autotoc_md40',1,'Integration with Thread System']]],
  ['thread_5fsystem_30',['thread_system',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md228',1,'']]],
  ['thread_5fsystem_20foundation_31',['1. thread_system (Foundation)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md189',1,'']]],
  ['threaded_20performance_32',['Multi-threaded Performance',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md407',1,'']]],
  ['threading_20ecosystem_20architecture_33',['Threading Ecosystem Architecture',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html',1,'']]],
  ['threading_20model_34',['Threading Model',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md450',1,'']]],
  ['threat_20model_20scope_35',['Threat Model (Scope)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html#autotoc_md491',1,'']]],
  ['tight_20loops_36',['3. Logging in Tight Loops',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md422',1,'']]],
  ['time_20analysis_37',['time analysis',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md90',1,'📈 Build Time Analysis'],['../index.html#autotoc_md52',1,'Real-time Analysis']]],
  ['times_38',['Average Build Times',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md91',1,'']]],
  ['to_20logger_20system_39',['Contributing to Logger System',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html',1,'']]],
  ['to_20v2_20x_40',['From v1.x to v2.x',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md364',1,'']]],
  ['topics_20tt_20docs_20advanced_20tt_41',['Advanced Topics (&lt;tt&gt;docs/advanced/&lt;/tt&gt;)',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md479',1,'']]],
  ['traditional_20api_20legacy_20support_42',['Traditional API (Legacy Support)',['../index.html#autotoc_md44',1,'']]],
  ['trends_43',['Performance Trends',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md82',1,'']]],
  ['tt_20add_5ffilter_20tt_44',['&lt;tt&gt;add_filter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md150',1,'']]],
  ['tt_20add_5fwriter_20tt_45',['tt add_writer tt',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md149',1,'&lt;tt&gt;add_writer&lt;/tt&gt;'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md125',1,'&lt;tt&gt;add_writer&lt;/tt&gt;']]],
  ['tt_20build_20tt_46',['&lt;tt&gt;build&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md152',1,'']]],
  ['tt_20debug_5fconfig_20tt_47',['&lt;tt&gt;debug_config&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md137',1,'']]],
  ['tt_20default_5fconfig_20tt_48',['&lt;tt&gt;default_config&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md135',1,'']]],
  ['tt_20docs_20advanced_20tt_49',['Advanced Topics (&lt;tt&gt;docs/advanced/&lt;/tt&gt;)',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md479',1,'']]],
  ['tt_20docs_20guides_20tt_50',['Guides (&lt;tt&gt;docs/guides/&lt;/tt&gt;)',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md478',1,'']]],
  ['tt_20enable_5fmetrics_5fcollection_20tt_51',['&lt;tt&gt;enable_metrics_collection&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md127',1,'']]],
  ['tt_20flush_20tt_52',['&lt;tt&gt;flush&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md128',1,'']]],
  ['tt_20high_5fperformance_20tt_53',['&lt;tt&gt;high_performance&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md138',1,'']]],
  ['tt_20log_20tt_54',['&lt;tt&gt;log&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md124',1,'']]],
  ['tt_20logger_5fmodule_3a_3acompact_5fformatter_20tt_55',['&lt;tt&gt;logger_module::compact_formatter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md172',1,'']]],
  ['tt_20logger_5fmodule_3a_3aconsole_5fwriter_20tt_56',['&lt;tt&gt;logger_module::console_writer&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md162',1,'']]],
  ['tt_20logger_5fmodule_3a_3afile_5fwriter_20tt_57',['&lt;tt&gt;logger_module::file_writer&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md163',1,'']]],
  ['tt_20logger_5fmodule_3a_3afunction_5ffilter_20tt_58',['&lt;tt&gt;logger_module::function_filter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md168',1,'']]],
  ['tt_20logger_5fmodule_3a_3ajson_5fformatter_20tt_59',['&lt;tt&gt;logger_module::json_formatter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md171',1,'']]],
  ['tt_20logger_5fmodule_3a_3alevel_5ffilter_20tt_60',['&lt;tt&gt;logger_module::level_filter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md166',1,'']]],
  ['tt_20logger_5fmodule_3a_3alog_5fentry_20tt_61',['&lt;tt&gt;logger_module::log_entry&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md157',1,'']]],
  ['tt_20logger_5fmodule_3a_3alog_5ffilter_5finterface_20tt_62',['&lt;tt&gt;logger_module::log_filter_interface&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md155',1,'']]],
  ['tt_20logger_5fmodule_3a_3alog_5fformatter_5finterface_20tt_63',['&lt;tt&gt;logger_module::log_formatter_interface&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md156',1,'']]],
  ['tt_20logger_5fmodule_3a_3alog_5fwriter_5finterface_20tt_64',['&lt;tt&gt;logger_module::log_writer_interface&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md154',1,'']]],
  ['tt_20logger_5fmodule_3a_3alogger_20tt_65',['&lt;tt&gt;logger_module::logger&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md121',1,'']]],
  ['tt_20logger_5fmodule_3a_3alogger_5fbuilder_20tt_66',['&lt;tt&gt;logger_module::logger_builder&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md141',1,'']]],
  ['tt_20logger_5fmodule_3a_3alogger_5fconfig_20tt_67',['&lt;tt&gt;logger_module::logger_config&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md130',1,'']]],
  ['tt_20logger_5fmodule_3a_3aplain_5fformatter_20tt_68',['&lt;tt&gt;logger_module::plain_formatter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md170',1,'']]],
  ['tt_20logger_5fmodule_3a_3aregex_5ffilter_20tt_69',['&lt;tt&gt;logger_module::regex_filter&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md167',1,'']]],
  ['tt_20logger_5fmodule_3a_3arotating_5ffile_5fwriter_20tt_70',['&lt;tt&gt;logger_module::rotating_file_writer&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md164',1,'']]],
  ['tt_20low_5flatency_20tt_71',['&lt;tt&gt;low_latency&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md139',1,'']]],
  ['tt_20production_20tt_72',['&lt;tt&gt;production&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md136',1,'']]],
  ['tt_20set_5fmin_5flevel_20tt_73',['&lt;tt&gt;set_min_level&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md126',1,'']]],
  ['tt_20use_5ftemplate_20tt_74',['&lt;tt&gt;use_template&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md144',1,'']]],
  ['tt_20validate_20tt_75',['tt validate tt',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md151',1,'&lt;tt&gt;validate&lt;/tt&gt;'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md133',1,'&lt;tt&gt;validate&lt;/tt&gt;']]],
  ['tt_20with_5fasync_20tt_76',['&lt;tt&gt;with_async&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md145',1,'']]],
  ['tt_20with_5fbuffer_5fsize_20tt_77',['&lt;tt&gt;with_buffer_size&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md146',1,'']]],
  ['tt_20with_5fconfig_20tt_78',['&lt;tt&gt;with_config&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md143',1,'']]],
  ['tt_20with_5fmetrics_20tt_79',['&lt;tt&gt;with_metrics&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md148',1,'']]],
  ['tt_20with_5fmin_5flevel_20tt_80',['&lt;tt&gt;with_min_level&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md147',1,'']]],
  ['tuning_81',['2. Buffer Size Tuning',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md411',1,'']]]
];
