var searchData=
[
  ['safety_0',['safety',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md393',1,'Issue 2: Exception Safety'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md394',1,'Issue 3: Thread Safety'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md178',1,'Thread Safety']]],
  ['safety_20guarantees_1',['Thread Safety Guarantees',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md453',1,'']]],
  ['sanitization_2',['Sensitive Data Sanitization',['../index.html#autotoc_md55',1,'']]],
  ['sanitize_20sensitive_20data_3',['1. Sanitize Sensitive Data',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md321',1,'']]],
  ['sanitizer_20results_4',['🔥 Sanitizer Results',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md89',1,'']]],
  ['sanitizers_202025_2009_2009_5',['[2.6.0] - Phase 5 P5 CI/CD Pipeline with Sanitizers (2025-09-09)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md250',1,'']]],
  ['scope_6',['Threat Model (Scope)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html#autotoc_md535',1,'']]],
  ['secure_20configuration_20checklist_7',['Secure Configuration Checklist',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html#autotoc_md539',1,'']]],
  ['security_20considerations_8',['Security Considerations',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md320',1,'']]],
  ['security_20features_9',['Security Features',['../index.html#autotoc_md53',1,'']]],
  ['security_20guide_10',['Security Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html',1,'']]],
  ['security_2emd_11',['SECURITY.md',['../SECURITY_8md.html',1,'']]],
  ['segregation_12',['segregation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md306',1,'3. Interface Segregation'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md440',1,'4. Interface Segregation']]],
  ['sensitive_20data_13',['1. Sanitize Sensitive Data',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md321',1,'']]],
  ['sensitive_20data_20sanitization_14',['Sensitive Data Sanitization',['../index.html#autotoc_md55',1,'']]],
  ['service_20container_15',['Using Service Container',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md356',1,'']]],
  ['service_20container_20integration_16',['Service Container Integration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md461',1,'']]],
  ['set_5fmin_5flevel_20tt_17',['&lt;tt&gt;set_min_level&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md126',1,'']]],
  ['setup_18',['setup',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md224',1,'1. Development Environment Setup'],['../index.html#autotoc_md70',1,'Development Setup']]],
  ['shutdown_19',['3. Graceful Shutdown',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md331',1,'']]],
  ['simple_20console_20logging_20',['Simple Console Logging',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md345',1,'']]],
  ['simple_20examples_21',['Simple Examples',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md108',1,'']]],
  ['single_20responsibility_22',['1. Single Responsibility',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md304',1,'']]],
  ['single_20thread_20performance_23',['Single Thread Performance',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md406',1,'']]],
  ['size_20considerations_24',['2.1 Batch Size Considerations',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md412',1,'']]],
  ['size_20tuning_25',['2. Buffer Size Tuning',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md411',1,'']]],
  ['small_20string_20optimization_20o3_26',['Small String Optimization (O3)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md264',1,'']]],
  ['solutions_27',['Common Issues and Solutions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md391',1,'']]],
  ['source_28',['Building from Source',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md342',1,'']]],
  ['source_20location_29',['Logging with Source Location',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md346',1,'']]],
  ['spdlog_30',['From spdlog',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md377',1,'']]],
  ['spdlog_20pattern_20migration_31',['spdlog Pattern Migration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md378',1,'']]],
  ['specific_20configuration_32',['Environment-Specific Configuration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md308',1,'']]],
  ['specific_20optimizations_33',['Platform-Specific Optimizations',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md427',1,'']]],
  ['stabilization_20current_34',['Phase 1: Stabilization (Current)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md233',1,'']]],
  ['stack_20architecture_35',['Technology Stack &amp; Architecture',['../index.html#autotoc_md27',1,'']]],
  ['standards_36',['Performance Comparison with Industry Standards',['../index.html#autotoc_md21',1,'']]],
  ['start_37',['start',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md283',1,'1. Before You Start'],['../index.html#autotoc_md41',1,'Quick Start']]],
  ['start_20with_20builder_20pattern_20recommended_38',['Quick Start with Builder Pattern (Recommended)',['../index.html#autotoc_md42',1,'']]],
  ['started_39',['started',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md223',1,'🚀 Getting Started'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md281',1,'Getting Started']]],
  ['started_20with_20logger_20system_40',['Getting Started with Logger System',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html',1,'']]],
  ['static_20analysis_41',['Static Analysis',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md84',1,'']]],
  ['static_20factory_20methods_42',['Static Factory Methods',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md134',1,'']]],
  ['stats_20last_2030_20days_43',['Workflow Execution Stats (Last 30 Days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md98',1,'']]],
  ['status_44',['status',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md95',1,'📝 Dependency Status'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md78',1,'🚀 Build Status']]],
  ['step_20by_20step_20migration_45',['Step-by-Step Migration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md385',1,'']]],
  ['steps_46',['Next Steps',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md358',1,'']]],
  ['strategies_47',['strategies',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md449',1,'4. Configuration Strategies'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md459',1,'Optimization Strategies'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md409',1,'Optimization Strategies'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md324',1,'Testing Strategies']]],
  ['strategy_48',['2. Log Rotation Strategy',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md330',1,'']]],
  ['stress_20testing_49',['3. Stress Testing',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md327',1,'']]],
  ['string_20formatting_50',['2. Excessive String Formatting',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md421',1,'']]],
  ['string_20optimization_20o3_51',['Small String Optimization (O3)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md264',1,'']]],
  ['strong_20cross_20platform_20compatibility_20strong_52',['🌐 &lt;strong&gt;Cross-Platform Compatibility&lt;/strong&gt;',['../index.html#autotoc_md15',1,'']]],
  ['strong_20design_20patterns_20implementation_20strong_53',['🔄 &lt;strong&gt;Design Patterns Implementation&lt;/strong&gt;',['../index.html#autotoc_md29',1,'']]],
  ['strong_20developer_20productivity_20strong_54',['🔧 &lt;strong&gt;Developer Productivity&lt;/strong&gt;',['../index.html#autotoc_md14',1,'']]],
  ['strong_20directory_20organization_20strong_55',['📁 &lt;strong&gt;Directory Organization&lt;/strong&gt;',['../index.html#autotoc_md31',1,'']]],
  ['strong_20enterprise_20ready_20features_20strong_56',['📈 &lt;strong&gt;Enterprise-Ready Features&lt;/strong&gt;',['../index.html#autotoc_md16',1,'']]],
  ['strong_20ideal_20applications_20strong_57',['🎯 &lt;strong&gt;Ideal Applications&lt;/strong&gt;',['../index.html#autotoc_md18',1,'']]],
  ['strong_20key_20files_20and_20their_20purpose_20strong_58',['📖 &lt;strong&gt;Key Files and Their Purpose&lt;/strong&gt;',['../index.html#autotoc_md32',1,'']]],
  ['strong_20modern_20c_20foundation_20strong_59',['🏗️ &lt;strong&gt;Modern C++ Foundation&lt;/strong&gt;',['../index.html#autotoc_md28',1,'']]],
  ['strong_20module_20dependencies_20strong_60',['🔗 &lt;strong&gt;Module Dependencies&lt;/strong&gt;',['../index.html#autotoc_md36',1,'']]],
  ['strong_20performance_20benchmarks_20strong_61',['📊 &lt;strong&gt;Performance Benchmarks&lt;/strong&gt;',['../index.html#autotoc_md19',1,'']]],
  ['strong_20performance_20excellence_20strong_62',['🚀 &lt;strong&gt;Performance Excellence&lt;/strong&gt;',['../index.html#autotoc_md12',1,'']]],
  ['strong_20production_20grade_20reliability_20strong_63',['🛡️ &lt;strong&gt;Production-Grade Reliability&lt;/strong&gt;',['../index.html#autotoc_md13',1,'']]],
  ['structure_64',['structure',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md520',1,'📚 Documentation Structure'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md227',1,'📚 Documentation Structure'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md444',1,'5. Log Entry Structure'],['../index.html#autotoc_md30',1,'Project Structure']]],
  ['structured_20json_20output_65',['Structured JSON Output',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md347',1,'']]],
  ['structured_20logging_66',['structured logging',['../index.html#autotoc_md48',1,'Structured Logging'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md181',1,'Structured Logging']]],
  ['style_67',['style',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md286',1,'Code Style'],['../index.html#autotoc_md71',1,'Code Style']]],
  ['submitting_20changes_68',['Submitting Changes',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md297',1,'']]],
  ['suite_202025_2009_2009_69',['[2.5.0] - Phase 5 P1 Comprehensive Test Suite (2025-09-09)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md255',1,'']]],
  ['suite_20o4_70',['Benchmark Suite (O4)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md265',1,'']]],
  ['summary_71',['summary',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md426',1,'Best Practices Summary'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md336',1,'Summary'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md517',1,'Summary'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md87',1,'Test Execution Summary']]],
  ['summary_20v2_200_72',['Breaking Changes Summary (v2.0+)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md362',1,'']]],
  ['support_73',['support',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md532',1,'🤝 Help &amp; Support'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md240',1,'Migration Support'],['../index.html#autotoc_md61',1,'Platform Support'],['../index.html#autotoc_md73',1,'Support'],['../index.html#autotoc_md44',1,'Traditional API (Legacy Support)']]],
  ['support_20and_20resources_74',['Support and Resources',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md398',1,'']]],
  ['synchronous_20i_20o_20in_20hot_20paths_75',['1. Synchronous I/O in Hot Paths',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md420',1,'']]],
  ['synchronous_20mode_76',['synchronous mode',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md451',1,'Synchronous Mode'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md402',1,'Synchronous Mode']]],
  ['synchronous_20vs_20asynchronous_20logging_77',['Synchronous vs Asynchronous Logging',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md351',1,'']]],
  ['system_78',['system',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html',1,'Contributing to Logger System'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html',1,'Getting Started with Logger System'],['../index.html#autotoc_md40',1,'Integration with Thread System'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md355',1,'Integration with Thread System'],['../index.html',1,'Logger System']]],
  ['system_20architecture_79',['Logger System Architecture',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html',1,'']]],
  ['system_20best_20practices_20guide_80',['Logger System Best Practices Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html',1,'']]],
  ['system_20ci_20cd_20dashboard_81',['Logger System CI/CD Dashboard',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html',1,'']]],
  ['system_20implementation_202025_2009_2010_82',['[2.3.0] - Phase 3 Overflow Policy System Implementation (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md267',1,'']]],
  ['system_20integration_83',['Network System Integration',['../index.html#autotoc_md72',1,'']]],
  ['system_20migration_20guide_84',['Logger System Migration Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html',1,'']]],
  ['system_20performance_20guide_85',['Logger System Performance Guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html',1,'']]],
  ['system_20project_86',['Logger System Project',['../index.html#autotoc_md0',1,'']]],
  ['systems_20complete_20100_20✅_87',['Phase 2 - Core Systems (Complete - 100% ✅)',['../index.html#autotoc_md3',1,'']]],
  ['systems_20complete_202025_2009_2009_88',['[2.2.0] - Phase 2 Core Systems Complete (2025-09-09)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md270',1,'']]]
];
