var searchData=
[
  ['v1_200_0',['Migration from v1.0',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_202-API__REFERENCE.html#autotoc_md212',1,'']]],
  ['v1_20x_20to_20v2_20x_1',['From v1.x to v2.x',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md952',1,'']]],
  ['v2_200_2',['Breaking Changes Summary (v2.0+)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md950',1,'']]],
  ['v2_20x_3',['From v1.x to v2.x',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md952',1,'']]],
  ['v3_200_200_4',['🔒 Security Features (v3.0.0)',['../index.html#autotoc_md5',1,'']]],
  ['validation_5',['validation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md532',1,'3. Builder Pattern with Validation'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2performance_2BASELINE.html#autotoc_md1059',1,'Baseline Validation'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_202-API__REFERENCE.html#autotoc_md204',1,'Configuration Validation'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md790',1,'Configuration Validation'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md530',1,'Logger Configuration with Validation'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CONDITIONAL__COMPILATION__REFACTORING.html#autotoc_md337',1,'Phase 3.5: Validation']]],
  ['validation_201_20day_6',['Phase 5: Validation (1 day)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md978',1,'']]],
  ['validation_203_20days_7',['Step 5: Testing and Validation (3 days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CONDITIONAL__COMPILATION__REFACTORING.html#autotoc_md349',1,'']]],
  ['vcpkg_20integration_8',['vcpkg Integration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2INTEGRATION.html#autotoc_md926',1,'']]],
  ['verification_9',['verification',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_201-architecture.html#autotoc_md130',1,'3. Verification'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CRITICAL__LOG__PREVENTION.html#autotoc_md405',1,'Testing &amp; Verification'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2contributing_2TRANSLATION__SUMMARY.html#autotoc_md778',1,'Verification']]],
  ['verification_20method_3a_10',['Verification Method:',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CRITICAL__LOG__PREVENTION.html#autotoc_md407',1,'']]],
  ['verification_20methods_11',['✅ Verification Methods',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CRITICAL__LOGGING__QUICK__START.html#autotoc_md448',1,'']]],
  ['verify_12',['Step 3: Verify',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CRITICAL__LOGGING__QUICK__START.html#autotoc_md439',1,'']]],
  ['version_20history_13',['Version History',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CRITICAL__LOG__PREVENTION.html#autotoc_md424',1,'']]],
  ['version_20migration_14',['Version Migration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md951',1,'']]],
  ['version_20support_20matrix_15',['Version Support Matrix',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md718',1,'']]],
  ['virtual_20function_20overhead_16',['Virtual Function Overhead',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CONDITIONAL__COMPILATION__REFACTORING.html#autotoc_md351',1,'']]],
  ['vs_20asynchronous_20logging_17',['Synchronous vs Asynchronous Logging',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md887',1,'']]]
];
