var searchData=
[
  ['handle_20management_0',['1. File Handle Management',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md680',1,'']]],
  ['handles_1',['Category 1: File Handles',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md700',1,'']]],
  ['handling_2',['handling',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md438',1,'Error Handling'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md161',1,'Error Handling'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md178',1,'Error Handling'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__3__PREPARATION.html#autotoc_md757',1,'Example 4: Async Writer with Error Handling']]],
  ['handling_20migration_3',['1. Error Handling Migration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md487',1,'']]],
  ['handling_20preparation_20logger_5fsystem_4',['Phase 3: Error Handling Preparation - logger_system',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__3__PREPARATION.html',1,'']]],
  ['handling_20status_5',['Error Handling Status',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__3__PREPARATION.html#autotoc_md739',1,'']]],
  ['handling_20with_20result_20pattern_6',['handling with result pattern',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md569',1,'2. Error Handling with Result Pattern'],['../index.html#autotoc_md43',1,'Error Handling with Result Pattern']]],
  ['hardware_20specifications_7',['Hardware Specifications',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2BASELINE.html#autotoc_md284',1,'']]],
  ['health_8',['🔄 CI/CD Pipeline Health',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md100',1,'']]],
  ['health_20check_20aggregation_9',['Pattern 3: Health Check Aggregation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md612',1,'']]],
  ['health_20check_20not_20working_10',['Issue: Health Check Not Working',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html#autotoc_md630',1,'']]],
  ['help_20support_11',['🤝 Help &amp; Support',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md795',1,'']]],
  ['helper_20functions_12',['Helper Functions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md163',1,'']]],
  ['hierarchy_13',['hierarchy',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md212',1,'Interface Hierarchy'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md708',1,'Writer Hierarchy']]],
  ['high_20impact_14',['Priority 1: Logger Lifecycle (High Impact)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__3__PREPARATION.html#autotoc_md744',1,'']]],
  ['high_20performance_20logging_15',['🎯 High-Performance Logging',['../index.html#autotoc_md3',1,'']]],
  ['high_20performance_20writer_16',['Custom High-Performance Writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md539',1,'']]],
  ['high_20priority_20p0_17',['High Priority (P0)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CURRENT__STATE.html#autotoc_md417',1,'']]],
  ['high_5fperformance_20tt_18',['&lt;tt&gt;high_performance&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md141',1,'']]],
  ['highlights_19',['🏗️ Architecture Highlights',['../index.html#autotoc_md5',1,'']]],
  ['history_20',['history',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md103',1,'📅 Release History'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2BASELINE.html#autotoc_md329',1,'Revision History']]],
  ['hot_20paths_21',['1. Synchronous I/O in Hot Paths',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md542',1,'']]],
  ['how_20to_20run_20analysis_22',['How to Run Analysis',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2STATIC__ANALYSIS__BASELINE.html#autotoc_md838',1,'']]],
  ['how_20to_20run_20benchmarks_23',['How to Run Benchmarks',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2BASELINE.html#autotoc_md314',1,'']]],
  ['how_20to_20run_20sanitizers_20locally_24',['How to Run Sanitizers Locally',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SANITIZER__BASELINE.html#autotoc_md809',1,'']]],
  ['how_20to_20verify_20baseline_25',['How to Verify Baseline',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md665',1,'']]],
  ['hub_26',['4. integrated_thread_system (Integration Hub)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md207',1,'']]]
];
