var searchData=
[
  ['factory_20functions_20with_20result_20t_20p2_20low_0',['Priority 2: Factory Functions with Result&lt;T&gt; (P2 - Low)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md813',1,'']]],
  ['factory_20methods_1',['Static Factory Methods',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md138',1,'']]],
  ['failures_2',['Recent Test Failures',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md92',1,'']]],
  ['failures_20last_207_20days_3',['Build Failures (Last 7 Days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md97',1,'']]],
  ['faq_4',['faq',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md452',1,'FAQ'],['../index.html#autotoc_md60',1,'FAQ']]],
  ['feature_20additions_5',['Feature Additions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md689',1,'']]],
  ['feature_20flags_6',['CMake Feature Flags',['../index.html#autotoc_md36',1,'']]],
  ['feature_20migration_202_203_20days_7',['Phase 3: Feature Migration (2-3 days)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md608',1,'']]],
  ['features_8',['features',['../index.html#autotoc_md2',1,'✨ Core Features'],['../index.html#autotoc_md24',1,'Advanced Features'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md665',1,'Advanced Features'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md184',1,'Advanced Features'],['../index.html#autotoc_md22',1,'Core Features'],['../index.html#autotoc_md21',1,'Features'],['../index.html#autotoc_md51',1,'Security Features'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__3__PREPARATION.html#autotoc_md872',1,'Week 2: Advanced Features']]],
  ['features_20strong_9',['📈 &lt;strong&gt;Enterprise-Ready Features&lt;/strong&gt;',['../index.html#autotoc_md14',1,'']]],
  ['features_3a_10',['features:',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md409',1,'Features:'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md405',1,'Key Features:']]],
  ['fetchcontent_20recommended_11',['Using CMake FetchContent (Recommended)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md561',1,'']]],
  ['file_20descriptor_20sync_12',['5. File Descriptor Sync',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md423',1,'']]],
  ['file_20handle_20management_13',['1. File Handle Management',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md778',1,'']]],
  ['file_20handles_14',['Category 1: File Handles',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md798',1,'']]],
  ['file_20not_20created_15',['file not created',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOGGING__QUICK__START.html#autotoc_md487',1,'&quot;WAL file not created&quot;'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md448',1,'Issue 1: WAL File Not Created']]],
  ['file_20operations_16',['Priority 2: File Operations',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__3__PREPARATION.html#autotoc_md843',1,'']]],
  ['file_20rotation_17',['file rotation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2BASELINE.html#autotoc_md297',1,'3. File Rotation'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md803',1,'Pattern: Safe File Rotation']]],
  ['file_20rotation_20resource_20management_18',['File Rotation Resource Management',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md802',1,'']]],
  ['file_20writer_19',['file writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md113',1,'1. File Writer'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md114',1,'2. Rotating File Writer']]],
  ['file_20writers_20',['File Writers',['../index.html#autotoc_md48',1,'']]],
  ['file_5fwriter_21',['4.1 file_writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md782',1,'']]],
  ['files_22',['files',['../index.html#autotoc_md33',1,'Configuration Files'],['../index.html#autotoc_md31',1,'Core Module Files'],['../index.html#autotoc_md32',1,'Writer Files']]],
  ['files_20and_20their_20purpose_20strong_23',['📖 &lt;strong&gt;Key Files and Their Purpose&lt;/strong&gt;',['../index.html#autotoc_md30',1,'']]],
  ['files_20created_20in_20phase_200_24',['Files Created in Phase 0',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md762',1,'']]],
  ['files_20impact_25',['Max Files Impact',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2BASELINE.html#autotoc_md300',1,'']]],
  ['filter_20interface_26',['Filter Interface',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md662',1,'']]],
  ['filtering_27',['3. Level Filtering',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md633',1,'']]],
  ['filtering_20and_20routing_28',['Advanced Filtering and Routing',['../index.html#autotoc_md47',1,'']]],
  ['filtering_20by_20level_29',['Filtering by Level',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md569',1,'']]],
  ['filtering_20writer_30',['1. Filtering Writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md118',1,'']]],
  ['filters_31',['filters',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md685',1,'Custom Filters'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md169',1,'Filters']]],
  ['finalization_32',['Week 3: Finalization',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__3__PREPARATION.html#autotoc_md873',1,'']]],
  ['finance_20medical_33',['2. High Reliability Configuration (Finance/Medical)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md438',1,'']]],
  ['finance_20medical_20systems_20maximum_20reliability_34',['Scenario 2: Finance/Medical Systems (Maximum Reliability)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOGGING__QUICK__START.html#autotoc_md474',1,'']]],
  ['fixed_35',['Fixed',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md344',1,'']]],
  ['flags_36',['flags',['../index.html#autotoc_md36',1,'CMake Feature Flags'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md743',1,'Integration Flags']]],
  ['flow_37',['2. Critical Write Flow',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md414',1,'']]],
  ['flow_20interface_20contracts_38',['🔄 Dependency Flow &amp; Interface Contracts',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md212',1,'']]],
  ['flush_20overhead_39',['Flush Overhead',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2BASELINE.html#autotoc_md309',1,'']]],
  ['flush_20tt_40',['&lt;tt&gt;flush&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md132',1,'']]],
  ['for_20contributors_41',['For Contributors',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md693',1,'']]],
  ['for_20existing_20users_202025_2009_2010_42',['[2.9.0] - Phase 5 P2 Migration Guide for Existing Users (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md333',1,'']]],
  ['for_20library_20users_43',['For Library Users',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md692',1,'']]],
  ['for_20logger_5fsystem_44',['Phase 2 Deliverables for logger_system',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md816',1,'']]],
  ['for_20other_20libraries_45',['Wrapper for Other Libraries',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md604',1,'']]],
  ['for_20testing_46',['1. Mock Logger for Testing',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md545',1,'']]],
  ['force_5fflush_5fon_5ferror_20tt_47',['Strategy 2: Disable &lt;tt&gt;force_flush_on_error&lt;/tt&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md432',1,'']]],
  ['format_48',['3. Commit Message Format',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md380',1,'']]],
  ['format_3a_49',['WAL Format:',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md417',1,'']]],
  ['formatter_20interface_50',['Formatter Interface',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md663',1,'']]],
  ['formatters_51',['formatters',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md686',1,'Custom Formatters'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md173',1,'Formatters'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md616',1,'Issue 5: Custom Formatters']]],
  ['formatting_52',['formatting',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md641',1,'2. Excessive String Formatting'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md383',1,'Code Formatting']]],
  ['foundation_53',['1. thread_system (Foundation)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md193',1,'']]],
  ['foundation_20complete_202025_2009_2009_54',['[2.1.0] - Phase 1 Foundation Complete (2025-09-09)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md367',1,'']]],
  ['foundation_20strong_55',['🏗️ &lt;strong&gt;Modern C++ Foundation&lt;/strong&gt;',['../index.html#autotoc_md26',1,'']]],
  ['free_20queue_20implementation_56',['Issue ARC-004: Lock-Free Queue Implementation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2ARCHITECTURE__ISSUES.html#autotoc_md252',1,'']]],
  ['from_20boost_20log_57',['From Boost.Log',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md599',1,'']]],
  ['from_20google_20glog_58',['From Google glog',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md600',1,'']]],
  ['from_20ini_20xml_20configuration_59',['From INI/XML Configuration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md594',1,'']]],
  ['from_20log4cpp_60',['From log4cpp',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md601',1,'']]],
  ['from_20other_20libraries_61',['Migration from Other Libraries',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md596',1,'']]],
  ['from_20source_62',['Building from Source',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md562',1,'']]],
  ['from_20spdlog_63',['From spdlog',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md597',1,'']]],
  ['from_20v1_200_64',['Migration from v1.0',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md189',1,'']]],
  ['from_20v1_20x_20to_20v2_20x_65',['From v1.x to v2.x',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md584',1,'']]],
  ['fsync_20overhead_20is_20too_20high_66',['Q3: fsync() overhead is too high.',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md455',1,'']]],
  ['functions_67',['Helper Functions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md164',1,'']]],
  ['functions_20with_20result_20t_20p2_20low_68',['Priority 2: Factory Functions with Result&lt;T&gt; (P2 - Low)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md813',1,'']]],
  ['further_20reading_69',['Further Reading',['../index.html#autotoc_md61',1,'']]],
  ['future_20enhancements_70',['Future Enhancements',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md687',1,'']]],
  ['future_20roadmap_71',['🔮 Future Roadmap',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md236',1,'']]]
];
