var searchData=
[
  ['gcc_20build_0',['1. Ubuntu GCC Build',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CURRENT__STATE.html#autotoc_md407',1,'']]],
  ['getting_20started_1',['getting started',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md226',1,'🚀 Getting Started'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md375',1,'Getting Started']]],
  ['getting_20started_20with_20logger_20system_2',['Getting Started with Logger System',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html',1,'']]],
  ['getting_5fstarted_2emd_3',['GETTING_STARTED.md',['../GETTING__STARTED_8md.html',1,'']]],
  ['github_20actions_20workflows_4',['GitHub Actions Workflows',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CURRENT__STATE.html#autotoc_md406',1,'']]],
  ['glog_5',['From Google glog',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md502',1,'']]],
  ['goals_6',['goals',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md662',1,'Phase 1 Goals'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__0__BASELINE.html#autotoc_md663',1,'Phase 2 Goals'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2STATIC__ANALYSIS__BASELINE.html#autotoc_md786',1,'Target Goals']]],
  ['google_20glog_7',['From Google glog',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md502',1,'']]],
  ['graceful_20degradation_8',['Graceful Degradation',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md439',1,'']]],
  ['graceful_20shutdown_9',['3. Graceful Shutdown',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md453',1,'']]],
  ['grade_20reliability_20strong_10',['🛡️ &lt;strong&gt;Production-Grade Reliability&lt;/strong&gt;',['../index.html#autotoc_md11',1,'']]],
  ['graph_11',['Dependency Graph',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md213',1,'']]],
  ['guarantees_12',['Thread Safety Guarantees',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md575',1,'']]],
  ['guard_20examples_20p2_20low_13',['Priority 1: Add Resource Guard Examples (P2 - Low)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md711',1,'']]],
  ['guide_14',['guide',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html',1,'Logger System Best Practices Guide'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html',1,'Logger System Migration Guide'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html',1,'Logger System Performance Guide'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE4__DI__MIGRATION__GUIDE.html',1,'Phase 4: Dependency Injection Pattern Migration Guide'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html',1,'Security Guide']]],
  ['guide_20for_20existing_20users_202025_2009_2010_15',['[2.9.0] - Phase 5 P2 Migration Guide for Existing Users (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md332',1,'']]],
  ['guidelines_16',['guidelines',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md692',1,'Alignment with Smart Pointer Guidelines'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md381',1,'C++ Guidelines'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2PHASE__2__RESOURCE__MANAGEMENT.html#autotoc_md685',1,'Compliance with RAII Guidelines'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md433',1,'Performance Guidelines']]],
  ['guides_20tt_17',['Guides (&lt;tt&gt;docs/guides/&lt;/tt&gt;)',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md734',1,'']]],
  ['guides_20tt_20docs_20guides_20tt_18',['Guides (&lt;tt&gt;docs/guides/&lt;/tt&gt;)',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md734',1,'']]]
];
