var searchData=
[
  ['ubuntu_20clang_20build_0',['2. Ubuntu Clang Build',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CURRENT__STATE.html#autotoc_md560',1,'']]],
  ['ubuntu_20gcc_20build_1',['1. Ubuntu GCC Build',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CURRENT__STATE.html#autotoc_md559',1,'']]],
  ['undefinedbehaviorsanitizer_2',['UndefinedBehaviorSanitizer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SANITIZER__BASELINE.html#autotoc_md820',1,'']]],
  ['undefinedbehaviorsanitizer_20warnings_3',['UndefinedBehaviorSanitizer Warnings',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SANITIZER__BASELINE.html#autotoc_md815',1,'']]],
  ['unit_20tests_4',['Unit Tests',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md426',1,'']]],
  ['update_5',['📊 Dashboard Update',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md116',1,'']]],
  ['update_20this_20document_6',['Update This Document',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2BASELINE.html#autotoc_md350',1,'']]],
  ['updated_20by_20ci_20cd_20workflows_20for_20real_20time_20data_20check_20the_20a_20href_20https_3a_20github_20com_20kcenon_20logger_5fsystem_20actions_20github_20actions_20page_20a_20em_7',['&lt;em&gt;This dashboard is automatically updated by CI/CD workflows. For real-time data, check the &lt;a href=&quot;https://github.com/kcenon/logger_system/actions&quot; &gt;GitHub Actions page&lt;/a&gt;.&lt;/em&gt;',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md118',1,'']]],
  ['updates_8',['Documentation Updates',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md431',1,'']]],
  ['usage_9',['usage',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md626',1,'Basic Usage'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md195',1,'Basic Usage'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md698',1,'Memory Usage'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md112',1,'Resource Usage']]],
  ['usage_20example_3a_10',['usage example:',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md452',1,'Usage Example:'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md455',1,'Usage Example:']]],
  ['usage_20examples_11',['Usage Examples',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html#autotoc_md194',1,'']]],
  ['usage_20scenarios_12',['📊 3 Usage Scenarios',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOGGING__QUICK__START.html#autotoc_md522',1,'']]],
  ['usage_3a_13',['WAL Usage:',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md463',1,'']]],
  ['use_14',['This architecture provides a solid foundation for high-performance logging while maintaining flexibility, extensibility, and ease of use.',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md770',1,'']]],
  ['use_20cases_15',['Real-World Impact &amp; Use Cases',['../index.html#autotoc_md15',1,'']]],
  ['use_20hybrid_20writer_16',['Strategy 3: Use Hybrid Writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md478',1,'']]],
  ['use_20wal_17',['Q2: When should I use WAL?',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CRITICAL__LOG__PREVENTION.html#autotoc_md499',1,'']]],
  ['users_18',['users',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md781',1,'Existing Users'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md767',1,'For Library Users'],['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md780',1,'New Users']]],
  ['users_202025_2009_2010_19',['[2.9.0] - Phase 5 P2 Migration Guide for Existing Users (2025-09-10)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md369',1,'']]],
  ['using_20as_20a_20package_20',['Using as a Package',['../index.html#autotoc_md37',1,'']]],
  ['using_20as_20installed_20package_21',['Using as Installed Package',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md625',1,'']]],
  ['using_20cmake_20fetchcontent_20recommended_22',['Using CMake FetchContent (Recommended)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md623',1,'']]],
  ['using_20service_20container_23',['Using Service Container',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md638',1,'']]]
];
