var searchData=
[
  ['raw_20pointers_0',['Issue 1: Memory Leaks with Raw Pointers',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md391',1,'']]],
  ['reading_1',['Further Reading',['../index.html#autotoc_md63',1,'']]],
  ['readme_2emd_2',['readme.md',['../README_8md.html',1,'(Global Namespace)'],['../docs_2README_8md.html',1,'(Global Namespace)']]],
  ['ready_20features_20strong_3',['📈 &lt;strong&gt;Enterprise-Ready Features&lt;/strong&gt;',['../index.html#autotoc_md16',1,'']]],
  ['real_20time_20analysis_4',['Real-time Analysis',['../index.html#autotoc_md52',1,'']]],
  ['real_20world_20impact_20use_20cases_5',['Real-World Impact &amp; Use Cases',['../index.html#autotoc_md17',1,'']]],
  ['recent_20changes_6',['Recent Changes',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md485',1,'']]],
  ['recent_20improvements_7',['🚀 Recent Improvements',['../index.html#autotoc_md2',1,'']]],
  ['recent_20issues_8',['🚨 Recent Issues',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md91',1,'']]],
  ['recent_20releases_9',['Recent Releases',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md100',1,'']]],
  ['recent_20test_20failures_10',['Recent Test Failures',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md87',1,'']]],
  ['recommendations_20production_11',['Recommendations (Production)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html#autotoc_md493',1,'']]],
  ['recommended_12',['recommended',['../index.html#autotoc_md42',1,'Quick Start with Builder Pattern (Recommended)'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md340',1,'Using CMake FetchContent (Recommended)']]],
  ['reconfiguration_13',['Dynamic Reconfiguration',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md309',1,'']]],
  ['recovery_14',['Error Recovery',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md317',1,'']]],
  ['refactoring_202025_2007_2026_15',['[2.0.0] - Major Refactoring (2025-07-26)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md273',1,'']]],
  ['reference_16',['reference',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2API__REFERENCE.html',1,'API Reference'],['../index.html#autotoc_md67',1,'Core API Reference']]],
  ['regressions_17',['Performance Regressions',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md93',1,'']]],
  ['related_20projects_18',['Related Projects',['../index.html#autotoc_md7',1,'']]],
  ['release_202025_2007_2001_19',['[1.0.0] - Initial Release (2025-07-01)',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CHANGELOG.html#autotoc_md275',1,'']]],
  ['release_20history_20',['📅 Release History',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md99',1,'']]],
  ['releases_21',['Recent Releases',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md100',1,'']]],
  ['reliability_20strong_22',['🛡️ &lt;strong&gt;Production-Grade Reliability&lt;/strong&gt;',['../index.html#autotoc_md13',1,'']]],
  ['request_20process_23',['Pull Request Process',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md297',1,'']]],
  ['requirements_24',['requirements',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md210',1,'Build Order Requirements'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2GETTING__STARTED.html#autotoc_md338',1,'Requirements']]],
  ['resource_20usage_25',['Resource Usage',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md98',1,'']]],
  ['resources_26',['resources',['..//home/runner/work/logger_system/logger_system/docs/README.md#autotoc_md486',1,'📖 External Resources'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2MIGRATION__GUIDE.html#autotoc_md397',1,'Support and Resources']]],
  ['responsibilities_27',['📋 Project Roles &amp; Responsibilities',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md187',1,'']]],
  ['responsibilities_3a_28',['responsibilities:',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md204',1,'Responsibilities:'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md199',1,'Responsibilities:'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md194',1,'Responsibilities:'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md189',1,'Responsibilities:']]],
  ['responsibility_29',['1. Single Responsibility',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md303',1,'']]],
  ['result_20pattern_30',['result pattern',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2LOGGER__SYSTEM__ARCHITECTURE.html#autotoc_md446',1,'2. Error Handling with Result Pattern'],['../index.html#autotoc_md45',1,'Error Handling with Result Pattern']]],
  ['results_31',['results',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md88',1,'🔥 Sanitizer Results'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md85',1,'🧪 Test Results'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CI__CD__DASHBOARD.html#autotoc_md80',1,'Latest Benchmark Results']]],
  ['review_20process_32',['Review Process',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md298',1,'']]],
  ['right_20mode_33',['1. Choose the Right Mode',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2PERFORMANCE.html#autotoc_md409',1,'']]],
  ['roadmap_34',['roadmap',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md231',1,'🔮 Future Roadmap'],['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2SECURITY.html#autotoc_md495',1,'Roadmap']]],
  ['roles_20responsibilities_35',['📋 Project Roles &amp; Responsibilities',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2architecture.html#autotoc_md187',1,'']]],
  ['rotating_20file_20writer_36',['2. Rotating File Writer',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2advanced_2CUSTOM__WRITERS.html#autotoc_md109',1,'']]],
  ['rotation_20strategy_37',['2. Log Rotation Strategy',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2guides_2BEST__PRACTICES.html#autotoc_md329',1,'']]],
  ['routing_38',['Advanced Filtering and Routing',['../index.html#autotoc_md49',1,'']]],
  ['running_20tests_39',['Running Tests',['../md__2home_2runner_2work_2logger__system_2logger__system_2docs_2CONTRIBUTING.html#autotoc_md291',1,'']]]
];
